### ISSUE TITLE
[Deprecation Notice] Sunsetting Hadoop 1.x Support and the Elasticsearch on YARN Project

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#1000]
Elastic is officially announcing two deprecations in the Elasticsearch-Hadoop project. Feedback and comments are welcome.

## Deprecating Hadoop 1.x Support
Support for Hadoop 1.x in the Elasticsearch-Hadoop connector will be deprecated in 5.5, and completely removed in 6.0. In striving to maintain the strongest integrations for the most popular Hadoop ecosystem components, we’re moving forward with only supporting Hadoop 2.x which is largely ubiquitous today. Most vendors no longer support Hadoop 1.x, and projects like Spark will no longer depend on Hadoop 1.x libraries going forward. Hadoop 1.x users are recommended to upgrade to a Hadoop 2.x based distribution for continued bug fixes and enhancements to the Elasticsearch-Hadoop connector.

## Deprecating Elasticsearch on YARN
The Elasticsearch on YARN project ([Documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/es-yarn.html), [Github](https://github.com/elastic/elasticsearch-hadoop/tree/master/yarn)) will be deprecated in 5.5, and completely removed in 6.0. Elasticsearch on YARN was an experiment for deploying Elasticsearch on top of Hadoop YARN, the resource management platform for Hadoop 2.x. The project was never recommended for production use and has been in beta status since its inception. The core limitation has been YARN’s lack of formal support for long-running services, which is a requirement for Elasticsearch to achieve production level stability. For enterprises looking to easily orchestrate and manage a fleet of Elasticsearch clusters either on-prem or in the cloud, [Elastic Cloud Enterprise](https://www.elastic.co/cloud/enterprise) is the key.

**Comment by jbaiera** [comment]
I'm closing this out as the requisite work has already occurred. ES-YARN is removed in 6.0 and testing on Hadoop versions before 2.2.0 has ceased in 6.0.
