### ISSUE TITLE
Spark saveToES overloading error, exception handling

### ISSUE THREAD

**Issue by aaditya89** [elastic/elasticsearch-hadoop#1003]
Hello,

We have spark cluster writing data to kafka and Elastic search

When we get error while writing to ES, the call to kafka also stops and not data is getting inserted on the kafka side as well.

If ES call fails, I tried adding exception handling on saveToES call. Even after this the call to kafka stops totally and data does not get ingested.

Can someone help me here on how to handle these 2 calls in spark where if one job fails, the other should keep running

If there's already a solution, please point me there.

Code Snippet : 

    val encrichedStream = rawDStream.foreachRDD{

      rdd =>{
        val enrichedRDD = rdd.map(vpcParser.mapRecord).map(vpcParser.enrichRecord)

        enrichedRDD.foreachPartition{
          recordsInPartition => recordsInPartition.foreach{
            element => kafkaWriterBC.value.send(_vpcTopicEnriched, parsingUtil.convertCaseToJson(element.asInstanceOf[VPCEnrichedData]))
          }
        }

        try {
          enrichedRDD.saveToEs(_esOutputType)
        }
        catch{
          case exp:Exception => {
            println("Elastic search ingestion failed")
            exp.printStackTrace()
            println(enrichedRDD.toDebugString)//.collect.mkString("\n\n\n\n\n"))

          }
          case _ => "Generic Elastic Search error"
        }
      }
    }

**Comment by jbaiera** [comment]
We do not support combining `foreachRDD` with `saveToEs` on DStreams. Issues occur when saving data in this way as the embedded es-hadoop http client exhausts connection resources on the worker machines due to the high amount of worker stand up and tear down operations that occur with Spark's micro batching. I would advise using the native `saveToEs` on the DStream itself.

**Comment by jbaiera** [comment]
Closing this as there's been no further conversation.
