### ISSUE TITLE
EsSpark.esJsonRDD(SparkContext,...) is failing to run at worker nodes with SparkContext null

### ISSUE THREAD

**Issue by ckayay** [elastic/elasticsearch-hadoop#1005]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

EsSpark.esJsonRDD is throwing Null Exception for SparkContext on worker nodes.

### Steps to reproduce

Code:

import org.apache.spark.streaming.dstream.DStream
import org.elasticsearch.spark.rdd.EsSpark
import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.apache.spark.SparkContext
import org.apache.spark.rdd.RDD

class EsLookUp (resource : String, query : String, sc : SparkContext, esProperties : Map[String, String]){
                def lookUp : RDD[String] = {
                                                Try(result = EsSpark.esJsonRDD(sc, resource, query, esProperties).map(record => record._2)) match {
                                                case Failure(exception) => throw exception
                                                case Success(_)         => println("Success")
                                                }
                    result
                }
}

Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :  

<!--
If you are filing a feature request, please remove the above bug
report block and provide responses for all of the below items.
-->

### Feature description

**Comment by jbaiera** [comment]
Could you please pay attention to the issue template and fill it out fully? It requests important information for reproducing bugs and for classifying them. We require version numbers of the library and the framework being used, the reproducing steps and the exception and stack trace from the error at the very minimum.

**Comment by jbaiera** [comment]
Closing this for now since there's been no response.
