### ISSUE TITLE
No way to define spark MapType from ES index schema

### ISSUE THREAD

**Issue by umnick84** [elastic/elasticsearch-hadoop#1010]
I would like my index fields to be converted into spark MapType rather than StructType. So that spark can in turn map this type to Map[String, String] or Map[String, Object]. I didn't find any configuration to mark a field as Map.
Is it possible?

**Comment by jbaiera** [comment]
Please try to keep questions like these to the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop). We reserve Github for reproducible bugs and feature tracking.

When ES-Hadoop reads data from Elasticsearch in SparkSQL, it converts nested objects into Rows under a StructType data type in the schema. Getting the data as a Map should be fairly straightforward as all you will need to do is convert the underlying Row object into a Map using a transformation.
