### ISSUE TITLE
pom.xml not marking optional dependencies correctly

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch-hadoop#1014]
The pom.xml in the Maven distribution of this package does not appear to be well formed.

For example:
https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-hadoop/5.5.0/elasticsearch-hadoop-5.5.0.pom

Has this dependency:
```xml
<dependency>
  <groupId>cascading</groupId>
  <artifactId>cascading-hadoop</artifactId>
  <version>2.6.3</version>
  <scope>optional</scope>
</dependency>
```
However, there is no such thing as an _optional_ scope:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

Instead, to mark a dependency as optional you need to use an optional tag:
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

So the above should probably look like:
```xml
<dependency>
  <groupId>cascading</groupId>
  <artifactId>cascading-hadoop</artifactId>
  <version>2.6.3</version>
  <optional>true</optional>
</dependency>
```

A valid example of this can be seen in Log4j's pom.xml:
https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-core/2.8.2/log4j-core-2.8.2.pom

**Comment by jbaiera** [comment]
This was fixed some time in the 6.2.X line with f8e1f25. Closing
