### ISSUE TITLE
ES-Hadoop Yarn

### ISSUE THREAD

**Issue by splikhita** [elastic/elasticsearch-hadoop#1028]
- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

I am working on ES-Hadoop Yarn. I have trouble uploading elasticsearch yarn jar file to HDFS.

### Steps to reproduce

This is what I did:

Downloaded elasticsearch yarn
```
$ sudo wget -O /opt/lib/elasticsearh-yarn-2.1.1.jar http://central.maven.org/maven2/org/elasticsearch/elasticsearch-yarn/2.1.1/elasticsearch-yarn-2.1.1.jar
```
Downloaded the elasticsearch version with elasticsearch yarn
```
$ hadoop jar /opt/lib/elasticsearch-yarn-2.1.1.jar -download-es download.local.dir=./downloads es.version=1.6.0
```
Uploading the Elasticsearch and Elasticsearch-yarn JAR file to HDFS (gives an error)
```
$ hadoop jar /opt/lib/elasticsearch-yarn-2.1.1.jar -install-es hdfs.upload.dir=/apps/elasticsearch
```

### Version Info

OS: : CentOS 7
JVM : 1.8.0_131
Hadoop: Hadoop 2.7.3
ES : 1.7.1

**Comment by jbaiera** [comment]
@splikhita The YARN integration for ES is currently deprecated and will be removed in 6.0.0. I would advise using a different way to deploy Elasticsearch as there will likely be no further updates to it.
