### ISSUE TITLE
sc.esRDD change ip address after SparkContext

### ISSUE THREAD

**Issue by gnh1201** [elastic/elasticsearch-hadoop#1031]
I want change sc.esRDD ip address after run SparkContext.

According to documentation, IP(es.nodes) address are changeable before run SparkContext.
but, I want change ip address after run SparkContext.

=== case 1 ===
conf: SparkConf
conf.set("es.nodes", "ip-address")    -> possible
sc: SparkContext(conf) 

=== case 2 ===
conf: SparkConf
sc: SparkContext(conf)
conf.set("es.nodes", "ip-address")    -> impossible
sc.set("es.nodes", "ip-address")        -> impossible

How can I change it (like case 2)?

#496

**Comment by jbaiera** [comment]
Hi @gnh1201, we reserve Github for bug reports and feature requests only. In the future, please ask questions like these in the [ES-Hadoop forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) instead. You should be able to apply settings to a job on the SparkContext, AND [via the save commands](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-write-scala) (from the documentation):
```
EsSpark.saveToEs(rdd, "spark/docs", Map("es.nodes" -> "ip-address"))
```

**Comment by ighack** [comment]
@jbaiera 

> 
> 
> Hi @gnh1201, we reserve Github for bug reports and feature requests only. In the future, please ask questions like these in the [ES-Hadoop forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) instead. You should be able to apply settings to a job on the SparkContext, AND [via the save commands](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-write-scala) (from the documentation):
> 
> ```
> EsSpark.saveToEs(rdd, "spark/docs", Map("es.nodes" -> "ip-address"))
> ```
How can I change IP when reading
How can I code "Index" and "Type".

JavaEsSpark.esRDD(javaSparkContext,cfg);
That doesn't has reo
