### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by hyitclj** [elastic/elasticsearch-hadoop#1043]
the error:
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'lxdh' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'imei' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'imsi' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'cardno' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'mac' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'lxdh' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'imei' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'imsi' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'cardno' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 
17/08/25 18:18:08 WARN ScalaRowValueReader: Field 'mac' is backed by an array but the associated Spark Schema does not reflect this;
              (use es.read.field.as.array.include/exclude) 

the code as follows:

SparkConf conf = new SparkConf();
		conf.set("es.index.auto.create", "true");
		conf.set("es.nodes", "192.168.1.228");
		conf.set("es.port", "9200");
		conf.setAppName(VMAnalyse.class.getName());
		if (Shell.WINDOWS) {
            conf.setMaster("local");
        }
		JavaSparkContext sc = new JavaSparkContext(conf);
        SQLContext sqlContext = new SQLContext(sc);
        Map<String,String> esOptions =new HashMap<String, String>();
        esOptions.put("es.nodes", "192.168.1.228");
        esOptions.put("es.port", "9200");
        esOptions.put("es.index.auto.create", "true");
        esOptions.put("es.scroll.size", "10000");
        esOptions.put("es.field.read.as.array.include", "mac");
        esOptions.put("es.field.read.as.array.include", "lxdh");
        esOptions.put("es.field.read.as.array.include", "imsi");
        esOptions.put("es.field.read.as.array.include", "imei");
        esOptions.put("es.field.read.as.array.include", "cardno");
        
        String trs_info_relations="wsx_trs_info_relations";
      
        sqlContext.read().format("org.elasticsearch.spark.sql").options(esOptions)
      		.load(trs_info_relations+"/"+trs_info_relations).show();

**Comment by jbaiera** [comment]
Please fill out the template provided for Github issues. Issues with the title "I can't use it" are not helpful to contributors on the project and your post lacks important information, like what versions of the connector and Spark that you are using. If you are unsure of what to put in the github issue then please post on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) and the community will attempt to assist you. Github is reserved for confirmed bugs and feature tracking only.

You are using `es.field.read.as.array.include` but the property is `es.read.field.as.array.include`.
