### ISSUE TITLE
Create a new timestamp on the fly to generate dynamic indices

### ISSUE THREAD

**Issue by gsaxam** [elastic/elasticsearch-hadoop#1045]
According to the ES docs, I can see that you can map a field in hive to add to the index prefix while generating multiple indexes.

```
# index the documents based on their date
es.resource.write = my-collection/{@timestamp:YYYY.MM.dd}
```

My issue is that I do not have such date or timestamp field in hive and I need to generate one on the fly. I am looking at something like this (if possible?)...

`es.resource.write = my-collection/{now():YYYY.MM.dd}`

**Comment by jbaiera** [comment]
@gsaxam This a great question for our [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop). Github is normally reserved for tracking confirmed bug reports and discussed feature requests.

You could try generating a field in your hive data during your write operation using something like Hive's [current_timestamp](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-DateFunctions) constant and using that generated field as the one to use for formatting the dynamic resource pattern.
