### ISSUE TITLE
Incorrect schema detected for nested geo_point

### ISSUE THREAD

**Issue by ProTip** [elastic/elasticsearch-hadoop#1047]
I'm using the string ```"lat,lon"``` representation due to cast errors when a whole number gets store into a double field. The outer location is properly detected as string type, however the location of the nested user doc is detected as a struct with doubles.

```
scala> df.printSchema
root
 |-- id: string (nullable = true)
 |-- location: string (nullable = true)
 |-- user: struct (nullable = true)
 |    |-- location: struct (nullable = true)
 |    |    |-- lat: double (nullable = true)
 |    |    |-- lon: double (nullable = true)
```

**Comment by jbaiera** [comment]
@ProTip Could you please observe and follow the issue template provided during issue creation? It is unclear which version of Elasticsearch and ES-Hadoop you are running against. It is also unclear what your mappings are or even how to reproduce the error you are describing.

**Comment by kokorin** [comment]
Also I noticed, that on ES 5.5 GeoPoint is read by Spark in a wrong manner: while in ES geoip is stored as
```
...
"geoip":{
   ...
   "location":[32.6, 42.3],
   ...
}
...
```
In Spark it comes as array of strings:
```
...
"geoip":{
   ...
   "location":["32.6", "42.3"], #notice strings
   ...
}
...
```

This leads to an error, while trying to save such event back to ES. Currently we have to convert **location** back to array of numbers.

**Comment by jbaiera** [comment]
@kokorin Could you open a new issue for those type castings? I've left this issue open based on your comment, but I'm going to go ahead and close this as the initial post is vague and there has been no response from the original author.
