### ISSUE TITLE
Missing data in Elastisearch when writing data with elasticsearch-spark connector

### ISSUE THREAD

**Issue by sixers** [elastic/elasticsearch-hadoop#1057]
### What kind an issue is this?

- [x] Bug report.

### Issue description

We have an issue with data consistency when storing data in Elasticsearch using Spark and elasticsearch-spark connector. Job finishes successfully, but when we compare the original data (stored in S3), with the data stored in ES, some documents are not present in Elasticsearch.

I'm looking for some guidance in order to debug this issue.

1) I want to understand why Elasticsearch doesn't have all the data although Spark says it finished the job and saved the data
2) What can we do to ensure that we write data to ES in a consistent manner?

### Steps to reproduce

This issue doesn't always happen and unfortunately we cannot reproduce it on demand. The only indicator we found that correlates with occurrences of this bug, is the presence of the failed stage while saving data in Elasticsearch.  Jobs which have this stage failure eventually complete successfully, but the data is inconsistent. 

![extractobjectstoelasticsearchnested maxruntimsec 43200 yarn_queue default date 2017-10-09 object_type leads env production 2017-10-09 15-08-26](https://user-images.githubusercontent.com/1457102/31339713-0f724bca-ad04-11e7-993d-3a9a311f1094.png)

We use the following configuration:
- Elasticsearch:
  - "es.write.operation": "index"
  - "es.nodes.discovery": "false"
  - "es.nodes.wan.only": "true"
- Spark:
  - write mode: "append"

### Version Info

OS:         :  Amazon Linux
JVM         :  1.8
Hadoop/Spark:  Hadoop 2.7.3 (Amazon), Spark 2.2.0
ES-Hadoop   :  elasticsearch-spark-20_2.11:5.5.2
ES          :  5.3 (Amazon Elasticsearch Service).

**Comment by jbaiera** [comment]
@sixers Have you tried loading data using a pre-calculated ID for each record? In the event of a task failure, having an ID for each document can enhance your write consistency.

You mention that you are only seeing the inconsistency when a task is lost. Could you share the details for the errors your tasks are experiencing?

**Comment by jbaiera** [comment]
Closing this as no further feedback provided. We can re-open if anything comes up.

**Comment by cclient** [comment]
same question

i use 

"es.batch.write.retry.count" -> "-1",
"es.batch.write.retry.wait" -> "60s",
"es.batch.size.entries" -> "50"

just work on whether  records version's conflict or request body is to large(nginx frontend)

ref https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html

**Comment by jbaiera** [comment]
@cclient I'm not sir what you're asking here. Perhaps starting thread on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) would be a good idea?
