### ISSUE TITLE
Hive insert overwrite command is not overwriting documents in elasticsearch.

### ISSUE THREAD

**Issue by pattanib** [elastic/elasticsearch-hadoop#1060]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [x] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

After serialising with Hive, when we ran Insert overwrite command it will overwrite hive data but elasticsearch data will be appended

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by jbaiera** [comment]
Please ask these sorts of questions on the forums, as conversations that pertain to your issue [may have already occurred](https://discuss.elastic.co/t/es-hadoop-2-0-2-jars-and-insert-overwrite/24091/3). Github is reserved for feature requests and confirmed bug reports only.

As I linked above, Hive's overwrite statement is not something that we can intercept at this time in the connector, as it is a part of the query syntax and not passed to the table implementation.
