### ISSUE TITLE
how to update about JavaEsSpark.saveToEs

### ISSUE THREAD

**Issue by hyitclj** [elastic/elasticsearch-hadoop#1067]
My test ES data:
#! Deprecation: query malformed, empty clause found at [2:13]
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "face_imsi_test",
        "_type": "face_imsi_test",
        "_id": "123",
        "_score": 1,
        "_source": {
          "img_id": "11",
          "img_url": "11",
          "pid": "123",
          "imsis": [
            {
              "imsi114": "10"
            }
          ],
          "update_time": "2017-10-12 19:49:04"
        }
      }
    ]
  }
}

if My new data is "pid:123,imsis{imsi113:10}" I want update or not replace
I want data as follow:
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "face_imsi_test",
        "_type": "face_imsi_test",
        "_id": "123",
        "_score": 1,
        "_source": {
          "img_id": "11",
          "img_url": "11",
          "pid": "123",
          "imsis": [
            {
              "imsi114": "10",
              "imsi113": "10"
            }
          ],
          "update_time": "2017-10-12 19:49:04"
        }
      }
    ]
  }
}

if My new data is "pid:123,imsis{imsi114:20}" I want update or not replace
I want data as follow:
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "face_imsi_test",
        "_type": "face_imsi_test",
        "_id": "123",
        "_score": 1,
        "_source": {
          "img_id": "11",
          "img_url": "11",
          "pid": "123",
          "imsis": [
            {
              "imsi114": "20",
              "imsi113": "10"
            }
          ],
          "update_time": "2017-10-12 19:49:04"
        }
      }
    ]
  }
}

but now it's replace : My new data is "pid:123,imsis{imsi113:10}"
the result as follow
#! Deprecation: query malformed, empty clause found at [2:13]
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "face_imsi_test",
        "_type": "face_imsi_test",
        "_id": "123",
        "_score": 1,
        "_source": {
          "img_id": "11",
          "img_url": "11",
          "pid": "123",
          "imsis": [
            {
              "imsi113": "10"
            }
          ],
          "update_time": "2017-10-12 19:49:04"
        }
      }
    ]
  }
}

**Comment by hyitclj** [comment]
My code ：
Map<String, String> vmId = new HashMap<>();
        vmId.put("es.mapping.id", "pid");
        JavaEsSpark.saveToEs(esRdd, "face_imsi_test/face_imsi_test",vmId);

**Comment by ebuildy** [comment]
Hello, I think you can use elastic forum or stackoverflow to ask help.

**Comment by jbaiera** [comment]
In this case, @ebuildy is correct. Please post questions on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) as github is reserved for confirmed bug reports and feature tracking.
