### ISSUE TITLE
 Could not initialize class org.elasticsearch.hadoop.util.Version

### ISSUE THREAD

**Issue by starbow727** [elastic/elasticsearch-hadoop#1072]
hi,
The elasticserch-hadoop version I use is 2.4.4
My jar package is elasticsearch-hadoop-2.4.4.jar
When I use hive es data query error message is as follows

Bad status for request TFetchResultsReq (fetchType = 0, operationHandle = TOperationHandle (hasResultSet = True, modifiedRowCount = None, operationType = 0, operationId = THandleIdentifier (secret = 'U \ x8d \ x01 _, \ xe6 @ \ xcc \ xb0K) HT \ x07 orientation = 4, maxRows = 100): TFetchResultsResp (status = TStatus (errorCode = None , errorMessage = 'java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version', sqlState = None, infoMessages = ['* java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version: 19: 18 ',' org.apache.hive.service.cli.session.HiveSessionProxy: invoke: HiveSessionProxy.java: 83 ',' org.apache.hive.service.cli. session.HiveSessionProxy: access $ 000: HiveSessionProxy.java: 36 ',' org.apache.hive.service.cli.session.HiveSessionProxy $ 1: run: HiveSessionProxy.java: 63 ',' java.security.AccessController: doPrivileged: AccessController. java: -2 ',' javax.security.auth.Subjec t: doAs: Subject.java: 415 ',' org.apache.hadoop.security.UserGroupInformation: doAs: UserGroupInformation.java: 1783 ',' org.apache.hive.service.cli.session.HiveSessionProxy: invoke: HiveSessionProxy. java: 59 ',' com.sun.proxy. $ Proxy27: fetchResults :: - 1 ',' org.apache.hive.service.cli.CLIService: fetchResults: CLIService.java: 440 ',' org.apache.hive .service.cli.thrift.ThriftCLIService: FetchResults: ThriftCLIService.java: 686 ',' org.apache.hive.service.cli.thrift.TCLIService $ Processor $ FetchResults: getResult: TCLIService.java: 1553 ',' org.apache .hive.service.cli.thrift.TCLIService $ Processor $ FetchResults: getResult: TCLIService.java: 1538 ',' org.apache.thrift.ProcessFunction: process: ProcessFunction.java: 39 ',' org.apache.thrift.TBaseProcessor : process: TBaseProcessor.java: 39 ',' org.apache.hive.service.auth.TSetIpAddressProcessor: process: TSetIpAddressProcessor.java: 56 ',' org.apache.thrift.server.TThreadPoolServer $ WorkerProcess: run: TThreadPoolServer.java : 286 ',' java.util.concurrent.ThreadPoolExecutor: runWorker: Threa dPoolExecutor.java:1145 ',' java.util.concurrent.ThreadPoolExecutor $ Worker: run: ThreadPoolExecutor.java: 615 ',' java.lang.Thread: run: Thread.java: 745 ',' * java.lang.NoClassDefFoundError : Could not initialize class org.elasticsearch.hadoop.util.Version: 35: 16 ',' org.elasticsearch.hadoop.rest.RestService: findPartitions: RestService.java: 225 ',' org.elasticsearch.hadoop.mr.EsInputFormat : getSplits: EsInputFormat.java: 457 ',' org.elasticsearch.hadoop.hive.EsHiveInputFormat: getSplits: EsHiveInputFormat.java: 111 ',' org.elasticsearch.hadoop.hive.EsHiveInputFormat: getSplits: EsHiveInputFormat.java: 50 ', 'org.apache.hadoop.hive.ql.exec.FetchOperator: getNextSplits: FetchOperator.java: 363', 'org.apache.hadoop.hive.ql.exec.FetchOperator: getRecordReader: FetchOperator.java: 295', 'org .apache.hadoop.hive.ql.exec.FetchOperator: getNextRow: FetchOperator.java: 446 ',' org.apache.hadoop.hive.ql.exec.FetchOperator: pushRow: FetchOperator.java: 415 ',' org.apache .hadoop.hive.ql.exec.FetchTask: fetch: FetchTask.java: 138 ',' org.apach e.hadoop.hive.ql.Driver: getResults: Driver.java: 1987 ',' org.apache.hive.service.cli.operation.SQLOperation: getNextRowSet: SQLOperation.java: 361 ',' org.apache.hive. service.cli.operation.OperationManager: getOperationNextRowSet: OperationManager.java: 277 ',' org.apache.hive.service.cli.session.HiveSessionImpl: fetchResults: HiveSessionImpl.java: 753 ',' sun.reflect.GeneratedMethodAccessor12: invoke: : -1 ',' sun.reflect.DelegatingMethodAccessorImpl: invoke: DelegatingMethodAccessorImpl.java: 43 ',' java.lang.reflect.Method: invoke: Method.java: 606 ',' org.apache.hive.service.cli. session.HiveSessionProxy: invoke: HiveSessionProxy.java: 78 '], statusCode = 3), results = None, hasMoreRows = None)

**Comment by jbaiera** [comment]
@starbow727 If you extract the class files, can you see if the Version class is present in the artifacts you are using? Do you see ExceptionInInitializerError anywhere in your logs that might indicate that the Version class is breaking on initialization?
