### ISSUE TITLE
Caused by: java.lang.IndexOutOfBoundsException: Index: 102, Size: 102

### ISSUE THREAD

**Issue by starbow727** [elastic/elasticsearch-hadoop#1073]
hi
My hive wide table has 102 fields, data written elasticsercher MR error
Caused by: java.lang.IndexOutOfBoundsException: Index: 102, Size: 102
Is the field too much?

**Comment by jbaiera** [comment]
@starbow727 Can you include the full stack trace and as much of a reproduction (or explanation of a reproduction) as possible? Could you also include the versions of your dependencies here?

**Comment by shuilinli** [comment]
请问你是怎么解决这个问题的？
