### ISSUE TITLE
elasticsearch spark java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by hhch** [elastic/elasticsearch-hadoop#1075]
hi

es-hadoop uses only scan-scroll, as so does the Spark support. There's no option to enable/disable it - it always relies on it.
--
why I just use JavaEsSpark.esRDD(sc, index/type).count() then throw oom.
there are 4 hundred million doc in es
and master is local, my pc

### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by jbaiera** [comment]
Github is reserved for feature requests and confirmed bug reports only. Please post questions like these on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) in the future.
