### ISSUE TITLE
 getting a wrong result when run a hive-sql that contains union-all opeartor. 

### ISSUE THREAD

**Issue by AbelChan1989** [elastic/elasticsearch-hadoop#1084]
### Issue description
I got a wrong result when run a hive-sql basic elastic-hadoop that contains union-all opeartor. 

### Steps to reproduce

Firstly, I create two table called es_test and es_test_1.

<img width="814" alt="qq20171213-004234 2x" src="https://user-images.githubusercontent.com/14013834/33899817-9c381438-dfa7-11e7-9307-ab198c2d16e3.png">
<img width="857" alt="qq20171213-004245 2x" src="https://user-images.githubusercontent.com/14013834/33899834-a41c8cf6-dfa7-11e7-8de4-51ca1023d9fe.png">

Sencod,I run a hive-sql about union-all.
`select id,title from es_test 
 WHERE id='1'
 union all
select id,title from es_test_1  
 WHERE id='A1'`

Finally, I look forward to getting two data results, but I'm actually getting one.
<img width="1026" alt="qq20171213-004037 2x" src="https://user-images.githubusercontent.com/14013834/33899964-fe98613c-dfa7-11e7-8b24-bb8866ce4f9d.png">

### Version Info

OS:         :  CentOS
JVM         :  1.8.0_112
Hadoop/Spark:  HDP2.4.2.0-258
Hive         :  1.2.1000.2.4.2.0-258
ES-Hadoop   :  7.0.0-alpha1-SNAPSHOT
ES          :  6.0.1

**Comment by jbaiera** [comment]
Thanks for the easy to reproduce error. I'll follow up on your open PR (#1085).
