### ISSUE TITLE
Fix the document error time to format the sample format

### ISSUE THREAD

**Issue by GourdErwa** [elastic/elasticsearch-hadoop#1088]
[https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html](url)
here
> `@timestamp field formatting - in this case YYYY.MM.dd`

use:YYYY.MM.dd 
org.elasticsearch.hadoop.serialization.field.DateIndexFormatter(2017.12.31->2018.12.31)

> final DateIndexFormatter esHadoop = new DateIndexFormatter();
        esHadoop.configure("YYYY.MM.dd");
        final String format = esHadoop.format("2017-12-31");
        System.out.println(format);//2018.12.31

must use JDK:yyyy.MM.dd to get it right(2017.12.31->2017.12.31)

Hope to fix this document .thx

**Comment by jbaiera** [comment]
Nice catch, I was not aware of the difference between `year` and `week year`. Learn something new every day. I'll update the docs soon.

**Comment by jbaiera** [comment]
fixed in eaab5e83aaedc01d17549280ca93cb8a1b5fcfc2
