### ISSUE TITLE
Docs for index pattern formatting should be updated to use the new `|` separator character

### ISSUE THREAD

**Issue by nilsga** [elastic/elasticsearch-hadoop#1091]
According to the documentation in https://github.com/elastic/elasticsearch-hadoop/blob/master/docs/src/reference/asciidoc/core/configuration.adoc, one can use a pattern like `my-collection/{@timestamp:YYYY.MM.dd}` to format an index name based on the date format of a field. However, this seems to have been replaced by the syntax `my-collection/{@timestamp|YYYY.MM.dd}` instead, which is also mentioned in the breaking changes docs. The configuration reference should also be updated to reflect this.

**Comment by jbaiera** [comment]
Nice catch. It seems some instances of this eluded our gaze. We'll update the docs soon.

**Comment by jbaiera** [comment]
fixed in 9a638c7d8b0329dca354c62f9690de9c4a7404c1
