### ISSUE TITLE
ES-Hadoop provides native (Java and Scala) integration with Spark: delete from es？

### ISSUE THREAD

**Issue by liansghuaifan** [elastic/elasticsearch-hadoop#1096]
i use ES-Hadoop integration with Spark ,i can read from es and write to es,but how do I delete from es? Can you help me

**Comment by jbaiera** [comment]
Please ask these sorts of questions on the [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop). Github is reserved for feature requests and confirmed bug reports only.
