### ISSUE TITLE
Using alias from spark SQL

### ISSUE THREAD

**Issue by frederic-boissiere** [elastic/elasticsearch-hadoop#1102]
Hello, I'm using spark SQL in order to extract data from elastic into csv files.

used software versions :
- elastic 5.5.2
- spark SQL 2.1.1
- elasticsearch-spark-20_2.11 5.5.2
- scala 2.11.8

I query elastic using alias.
When the alias is updated (remove and add new indices) during spark job processing, this last one fails.

Does it possible to preserve the same index from the beginning to end of the spark job execution (atomic process) ?

My workaround is searching the indices associated to the alias at the beginning of the spark job and initialize the dataframe with these indices.
Does it exist a better solution ?

my steps are
- t0 : first call to elastic via alias (here index-0 is used)
- t1 : alias update from index-0 to index-1
- t2 : second call to elastic via alias (here index-1 is used) **==> it failed**

In my case, data in elastic is schemaless. So, in case an attribute is not present after the alias updated then the second query to elastic failed.

My workaround has been successfully validated. In that case the steps become :
- init: get the indices associated to the alias (get index-0)
- t0 : first call to elastic via index-0
- t1 : alias update from index-0 to index-1
- t2 : second call to elastic via index-0 **==> it succeeded**

**Comment by jbaiera** [comment]
Since we pull aliases apart into their underlying index/shard information to determine splits, this should be something that we consider a bug until further information is collected.

**Comment by jbaiera** [comment]
> my steps are
> 
> t0 : first call to elastic via alias (here index-0 is used)
> t1 : alias update from index-0 to index-1
> t2 : second call to elastic via alias (here index-1 is used) ==> it failed
> In my case, data in elastic is schemaless. So, in case an attribute is not present after the alias updated then the second query to elastic failed.
> 
> My workaround has been successfully validated. In that case the steps become :
> 
> init: get the indices associated to the alias (get index-0)
> t0 : first call to elastic via index-0
> t1 : alias update from index-0 to index-1
> t2 : second call to elastic via index-0 ==> it succeeded

I'm trying to reproduce this behavior but the steps you've provided are not really detailed enough for me to follow what you are doing and what the connector is doing. Could you elaborate when exactly you are performing each of the given steps? Saying "Xth call to elastic" doesn't really give us much to work with.

**Comment by jbaiera** [comment]
Closing this due to lack of feedback.
