### ISSUE TITLE
Spark ES API error cause not being reported

### ISSUE THREAD

**Issue by gridcellcoder** [elastic/elasticsearch-hadoop#1112]
### What kind an issue is this?

- [ X ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Whenever Elasticsearch and Spark uses the bulk API, the `caused_by` of any error (provided by elasticsearch is always reported)

### Steps to reproduce

Code:

```scala
 val pointMap = Map[String,String](
      "es.nodes" -> elasticSearch,
      "es.resource" -> "point/point",
      "es.port" -> "80",
      "es.nodes.wan.only" -> "true"
    )
 val pointData = //any RDD that will cause a 400 error in ES, such as duplicate type, wrong type, incorrect shapes  i.e. invalid LinearRing found (coordinates are not closed)
 pointData.saveToEsWithMeta(pointMap)
```

Strack trace:
When using Postman or CURL of the bulk data, the `caused_by`  field is returned
```
{
    "took": 1644,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "shape",
                "_type": "shape",
                "_id": "shape31",
                "status": 400,
                "error": {
                    "type": "mapper_parsing_exception",
                    "reason": "failed to parse [geometry]",
                    "caused_by": {
                        "type": "parse_exception",
                        "reason": "invalid LinearRing found (coordinates are not closed)"
                    }
                }
            }
        },
``` 

but in `RestClient`

```java
 if (err == null) {
                    if (m.containsKey("reason")) {
                        error = m.get("reason").toString();
                    }
                    else if (m.containsKey("caused_by")) {
                        error += ";" + ((Map) m.get("caused_by")).get("reason");
                    }
                    else {
                        error = m.toString();
                    }
                }
```
assumes only one is populated with the `else if` and so never reports the caused_by
```java
 else if (m.containsKey("caused_by")) {
                        error += ";" + ((Map) m.get("caused_by")).get("reason");
                    }
```

### Version Info

OS:         :  Ubuntu 17.10
JVM         :  1.8_144
Spark:  2.2.0
ES-Hadoop   :  6.0.1
ES          :  6.0.1

**Comment by jbaiera** [comment]
This is a very good idea. I am however closing this as a duplicate. Please thumbs-up or leave comments on #1115.
