### ISSUE TITLE
Read GZIP documents fail.

### ISSUE THREAD

**Issue by lbadi** [elastic/elasticsearch-hadoop#1119]
Disclaimer : I'm not sure if this should be a bug or a feature request.

- [X] Feature Request.

### Feature description

We are trying to read from a ES cluster that always return the content compressed with gzip (We implement a proxy to always return the response compressed despite the headers).

This make sense because it should descompress the content  before read.

One may think that this should work because spark support reading gziped files.

Strack trace:

```
org.elasticsearch.hadoop.rest.EsHadoopParsingException: org.codehaus.jackson.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: java.io.ByteArrayInputStream@64f6dd19; line: 1, column: 2]```

**Comment by jbaiera** [comment]
This is a known issue with Apache HTTP that we have no real control of fixing: https://github.com/elastic/elasticsearch-hadoop/issues/804

> ES-Hadoop is built on top of Apache Commons HTTP v3.0.1 which does not support compression. Experimental support for compression was added in v4.1 and enabled by default in v4.3, but will not be backported to 3 in any capacity. Since we use the library versions that are provided with Hadoop to avoid conflicting jars and to facilitate simpler usage of the library this would need to wait until Hadoop updates their version of Commons HTTP.

At some point, we would like to update the project to use the low level Java rest client from the Elasticsearch project (just shade and package it with our distributions). That uses a newer version of the apache libraries which could better support this. Sadly this will have to wait for a major version (most likely 7.0.0).
