### ISSUE TITLE
Support UPDATE output mode for Spark Structured Streaming

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1123]
We now support Spark Structured Streaming as of 6.x, but only in `APPEND` mode. It would be beneficial to support `UPDATE` mode, with the requirement that the user MUST provide a field to be used for a document ID.

**Comment by kant111** [comment]
can we make this backward compatible also? That way users can use this feature while communication with ES 5.5?

**Comment by jbaiera** [comment]
While the project's official stance is that we maintain BWC with the previous major's most recent minor release, we give it our best effort to maintain backwards compatibility with as many versions of Elasticsearch as we can.

**Comment by kant111** [comment]
Any sort of timeline or release number on this?

**Comment by jbaiera** [comment]
We usually do not commit to timelines or release targets on public issues.

**Comment by kant111** [comment]
@jbaiera can I use `update mode` and `forEachSink` to write to ES for now?

**Comment by kant111** [comment]
@jbaiera Thanks. Can you please provide some more details on how to do that? For example, should I use elastic-hadoop connector or elastic search java driver? Any examples because I dont see in docs on how to do this?

I am trying to write streaming dataset to elastic search in update mode.

**Comment by jbaiera** [comment]
If you are using the Transport client you will need to construct the client objects lazily and mark them as transient as they cannot be serialized from the driver to the cluster.

**Comment by kant111** [comment]
isn't serialization from driver to cluster required for spark to work correctly? I believe I am constructing lazily from the above code, isn't it? or you mean static?

**Comment by kant111** [comment]
ok. got it.

**Comment by jbaiera** [comment]
@kant111 I'm happy to see that you've taken in interest in the code. That if-statement indeed does block off the option itself from being used, but it doesn't do anything to make sure that the Sink implementation observes the invariants set forth in the UPDATE mode, or follows what a user might expect from UPDATE mode in regards to Elasticsearch. The following things would need to be in place to accept working with UPDATE mode:

First, in UPDATE mode, the underlying connector capabilities should be fine as long as it is using the upsert method of ingestion to ES. Alongside this mode, a field must be marked as an ID in the configuration. To support UPDATE mode, it should be checked that these settings are present, or even to set them in the connector at this point, throwing an error if they have values already that are incompatible.

Second, for us to support UPDATE mode, we need sufficient testing to make sure that the connector is performing the required operations, and can see the expected outcomes. Building these tests can be time consuming, and thus they were left off of the initial implementation.

Finally, there is no plan to support any other output modes than APPEND and (eventually) UPDATE. The COMPLETE output mode (and any future ones) would need to be blocked off since Elasticsearch would not support that kind of output mode.

**Comment by toddleo** [comment]
Bump. Is there any progress here or timetable after a long wait? :cry:

**Comment by masseyke** [comment]
If anyone on this ticket is still interested (I know it's been a long wait), I've got a draft PR up for this. I'd appreciate any feedback before we finalize it. See #1839
