### ISSUE TITLE
can't set "http.connection.timeout" in HttpClientParams.

### ISSUE THREAD

**Issue by realrnjs** [elastic/elasticsearch-hadoop#1124]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [x] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description
The value of "http.connection.timeout" can not be set, so it takes two minutes to connect to the next server.

### Steps to reproduce

Code:
```

    val esCfg = new PropertiesSettings()
    esCfg.setProperty(
      "es.nodes",
      "es-server1:9200,es-server2:9200,es-server3:19200")
    esCfg.setProperty("es.http.timeout", "5s")
    esCfg.setProperty("es.http.retries", "1")

    val bootstrap = new RestClient(esCfg)
    try {
      log.debug(s"bootstrap.getCurrentNode=${bootstrap.getCurrentNode}")
      val version = bootstrap.remoteEsVersion
      log.debug(s"version=$version")
    } finally {
      Try { bootstrap.close() }
    }
```

Strack trace:

```
Node [es-server1:9200] failed (연결 시간 초과 (Connection timed out)); selected next node [es-server2:9200]
``` 

### Version Info

OS: : Ubuntu 16.4
JVM : 1.8
Hadoop/Spark: 2.6/2.2.0.cloudera2
ES-Hadoop : 6.1.1
ES : 6.1.1

**Comment by realrnjs** [comment]
This problem can be solved by adding the following to the CommonsHttpTransport constructor.

params.setParameter ("http.connection.timeout", (int) settings.getHttpTimeout ());

**Comment by jbaiera** [comment]
Thanks for opening this. I have fix that will be going in soon for it.
