### ISSUE TITLE
Insert slowdowns on Master branch

### ISSUE THREAD

**Issue by nmaillard** [elastic/elasticsearch-hadoop#113]
Hello 

I'm playing with the master branch to test the unique ID or parent child features.
Testing it out I was surprised to see huge slowdowns in hive insertion queries. 
My test I have a table with 30 columns and I want to insert 4M entries.
I have the same insert overwrite query but I have changed the deployed jar.
CREATE EXTERNAL TABLE es_test( values String..STORED BY 'org.elasticsearch.hadoop.hive.ESStorageHandler'
TBLPROPERTIES('es.resource' = 'test/test','es.host' = 'myhost')

When I insert with current release I get a thoughput of 12k/s so 5 minutes for insertion with on or 2 map tasks failed on:

java.lang.IllegalStateException: Cannot get response body for [POST]test/test/_bulk]
    at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:189)

When I insert with the master the same data takes about 57 minutes for insertion
I get around 50-60% failed map tasks with a lot of:

java.lang.IllegalStateException: Cannot get response body for [PUT][test]
    at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:221)

I/O exception (java.net.ConnectException) caught when processing request: Connection timed out
 and some EsRejectedExecutionExceptions bulk thread pool 50.

I'll keep investigating to find a more usefull error or a more definite reason.
Hope this posts helps.

**Comment by jbaiera** [comment]
Closing this out as there do not seem to be any actionable items any longer.
