### ISSUE TITLE
Unable to load bulk data into Elasticsearch. Getting eshadoopnonodesleftexception: connection error (check network and/or proxy settings).

### ISSUE THREAD

**Issue by KrishnaShah123** [elastic/elasticsearch-hadoop#1138]
I am currently trying to load 433 gb of data using Hive. And my data size can grow till few TB in near future.
Hive queries are as under:

```
ADD JAR /home/ec2-user/elasticsearch-hadoop-6.2.2.jar;
``
CREATE EXTERNAL TABLE tble_es(schema)
ROW FORMAT SERDE 'org.elasticsearch.hadoop.hive.EsSerDe' STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = '2l/wlp','network.bind_host'='10.**.***.152',
 'es.nodes'='ip-10-**-**-152', 'es.port'='9200','es.chunk_size'='2000000', 'es.nodes.wan.only' = 'true','es.batch.write.retry.count'='2','es.batch.write.retry.wait'='2s',
'es.write.rest.error.handlers'='log','es.write.rest.error.handler.log.logger.name'='BulkErrors','threadpool.bulk.queue_size'='100000');

CREATE TABLE IF NOT EXISTS tble_data (schema)
row format delimited fields terminated by '|' LOCATION 's3://elasticsearch/pntable/'; 

insert into tble_es select * from tble_data;
```

======
I am making an index as:
shard=5, Replica=0, Refresh interval= -1.
I am using Tez as my execution engine.
My ES cluster specifications are:

number of nodes: 5, (1 master, 4 datanodes) cores: 8 cores RAM: 16GB Storage as per each node: Master- 1TB, 2 data nodes- 1 TB, and other 2 data nodes:- 100gb each. 

Now when I run the insert query, it completes up to 34% and then jobs fails and gives me the error:

**eshadoopnonodesleftexception: connection error (check network and/or proxy settings)**

I have enough storage for ES, still my write requests are getting rejected.
Would be grateful if anyone can show me light.

**Comment by jbaiera** [comment]
@KrishnaShah123 We reserve github for tracking confirmed bugs and feature planning. I see that you have an open thread [here](https://discuss.elastic.co/t/not-able-to-load-data-from-hive-to-elasticsearch-using-esstorage-handler/127094) but have not responded with any job logs or shared results of increasing the logging level. If we find that there is an actual issue with the code then we can open an issue on github for it, but until then, we ask that you keep these kinds of questions to the forums.
