### ISSUE TITLE
Write requests hang forever without error/exception

### ISSUE THREAD

**Issue by v4lproik** [elastic/elasticsearch-hadoop#1145]
### What kind an issue is this?
- [x] Bug report - Connection hanging forever

### Issue description
I am having an issue when my streaming application tries to write data in to ES. There's no errors or exceptions, the request just hangs forever.

My ES cluster and Spark streaming application are hosted on Google Kubernetes Engine. The write operation succeeds when all my containers are on a single node. However, if I am having a multi node cluster, the write operation hangs forever.

Unfortunately, I didn't get any useful information by activating the debug logs. Thus, I have used tcpdump to see what's happening under the hood and I can see that the connector gets an answer from the ES client node and then, nothings happen. The HEAD http request - verifying if the index exists - that should come right after the answer from the ES client node never happens.

### Steps to reproduce

Code:

Connector configuration
```
  def getElasticConf: Map[String, String] = {
      Map("es.nodes" -> s"elasticsearch:9200",
        "es.clustername" -> "my-db",
        "es.nodes.discovery" -> "true",
        "es.nodes.data.only" -> "false",
        "es.nodes.client.only" ->"true",
        "es.nodes.wan.only" -> "false",
        "es.write.operation" -> "upsert",
        "es.mapping.date.rich" -> "false",
        "es.http.timeout" -> "1m",
        "es.http.retries" -> "3",
        "es.mapping.id" -> "id")
  }
```

Write operation
```
EsSparkStreaming.saveToEs(myDataStream, s"${ELASTIC_INDEX_FINDING}/${ELASTIC_INDEX_FINDING_TYPE}", elasticConf)

```

### Version Info

OS:         :  ubuntu
JVM         :  openjdk-8
Hadoop/Spark:  2.2.1
ES-Hadoop   :  6.2.1
ES          :  6.2.3

**Comment by jbaiera** [comment]
Interesting, Could you raise the logging level for `org.elasticsearch.hadoop.rest.commonshttp` pacakge to `TRACE`? This should print out the http requests that are making it through to the process. I wonder if there's some sort of disconnect happening somewhere.

Additionally, I know you mentioned that this is running on Google Kubernetes Engine, but if you are able to collect any thread dumps on the process that may help identify where it's getting stuck.

**Comment by v4lproik** [comment]
Hi @jbaiera,

Thanks for your fast reply. I have set the verbosity to TRACE. Below, the output :

`
18/05/10 11:30:19 INFO BlockManagerInfo: Added input-1-1525951819600 in memory on 10.40.0.19:36645 (size: 688.0 B, free: 366.3 MB)
18/05/10 11:30:19 INFO BlockGenerator: Pushed block input-1-1525951819600
18/05/10 11:30:20 INFO JobScheduler: Starting job streaming job 1525951820000 ms.0 from job set of time 1525951820000 ms
18/05/10 11:30:20 INFO JobScheduler: Finished job streaming job 1525951820000 ms.0 from job set of time 1525951820000 ms
18/05/10 11:30:20 INFO JobScheduler: Starting job streaming job 1525951820000 ms.1 from job set of time 1525951820000 ms
18/05/10 11:30:20 INFO JobScheduler: Added jobs for time 1525951820000 ms
18/05/10 11:30:20 DEBUG PooledTransportManager: Creating new PooledTransportFactory for job key [11b7fe11-1d38-4318-9e29-50d405752d02]
18/05/10 11:30:20 TRACE PooledTransportManager$PoolCleaner: Started PoolCleaner...
18/05/10 11:30:20 TRACE PooledTransportManager$PoolCleaner: Waiting
18/05/10 11:30:20 DEBUG PooledHttpTransportFactory: Creating new TransportPool for job [11b7fe11-1d38-4318-9e29-50d405752d02] for host [10.43.243.182:9200]
18/05/10 11:30:20 DEBUG TransportPool: Creating new pooled CommonsHttpTransport for host [10.43.243.182:9200] belonging to job [11b7fe11-1d38-4318-9e29-50d405752d02]
18/05/10 11:30:20 TRACE CommonsHttpTransport: Opening HTTP transport to 10.43.243.182:9200
18/05/10 11:30:20 DEBUG HeaderProcessor: Added HTTP Headers to method: [Content-Type: application/json
, Accept: application/json
]
18/05/10 11:30:20 TRACE CommonsHttpTransport: Tx [GET]@[10.43.243.182:9200][]?[null] w/ payload [null]
18/05/10 11:30:20 TRACE CommonsHttpTransport: Rx @[10.40.0.19] [200-OK] [{
  "name" : "elasticsearch-elasticsearch-client-7678fb8667-sgc59",
  "cluster_name" : "my-db",
  "cluster_uuid" : "Rzad1SeHSPSe2n9y09lmVg",
  "version" : {
    "number" : "6.2.3",
    "build_hash" : "c59ff00",
    "build_date" : "2018-03-13T10:06:29.741383Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
]
18/05/10 11:30:20 DEBUG EsSpark$: Discovered Elasticsearch version [6.2.3]
18/05/10 11:30:20 INFO SparkContext: Starting job: runJob at EsSpark.scala:107
18/05/10 11:30:20 INFO DAGScheduler: Got job 2 (runJob at EsSpark.scala:107) with 3 output partitions
18/05/10 11:30:20 INFO DAGScheduler: Final stage: ResultStage 2 (runJob at EsSpark.scala:107)
18/05/10 11:30:20 INFO DAGScheduler: Parents of final stage: List()
18/05/10 11:30:20 INFO DAGScheduler: Missing parents: List()
18/05/10 11:30:20 INFO DAGScheduler: Submitting ResultStage 2 (MapPartitionsRDD[73] at map at AnalyseLogFileJobStreaming.scala:259), which has no missing parents
18/05/10 11:30:20 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 13.9 KB, free 366.2 MB)
18/05/10 11:30:20 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 3.0 KB, free 366.2 MB)
18/05/10 11:30:20 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on 10.40.0.19:36645 (size: 3.0 KB, free: 366.3 MB)
18/05/10 11:30:20 INFO SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1006
18/05/10 11:30:20 INFO DAGScheduler: Submitting 3 missing tasks from ResultStage 2 (MapPartitionsRDD[73] at map at AnalyseLogFileJobStreaming.scala:259) (first 15 tasks are for partitions Vector(0, 1, 2))
18/05/10 11:30:20 INFO TaskSchedulerImpl: Adding task set 2.0 with 3 tasks
18/05/10 11:30:23 INFO MemoryStore: Block input-1-1525951823000 stored as values in memory (estimated size 664.0 B, free 366.2 MB)
18/05/10 11:30:23 INFO BlockManagerInfo: Added input-1-1525951823000 in memory on 10.40.0.19:36645 (size: 664.0 B, free: 366.3 MB)
18/05/10 11:30:23 INFO BlockGenerator: Pushed block input-1-1525951823000
18/05/10 11:30:24 INFO MemoryStore: Block input-1-1525951823800 stored as values in memory (estimated size 640.0 B, free 366.2 MB)
18/05/10 11:30:24 INFO BlockManagerInfo: Added input-1-1525951823800 in memory on 10.40.0.19:36645 (size: 640.0 B, free: 366.3 MB)
18/05/10 11:30:24 INFO BlockGenerator: Pushed block input-1-1525951823800
18/05/10 11:30:24 INFO MemoryStore: Block input-1-1525951824000 stored as values in memory (estimated size 1144.0 B, free 366.2 MB)
18/05/10 11:30:24 INFO BlockManagerInfo: Added input-1-1525951824000 in memory on 10.40.0.19:36645 (size: 1144.0 B, free: 366.3 MB)
18/05/10 11:30:24 INFO BlockGenerator: Pushed block input-1-1525951824000
18/05/10 11:30:24 INFO JobScheduler: Added jobs for time 1525951824000 ms
18/05/10 11:30:24 INFO MemoryStore: Block input-1-1525951824400 stored as values in memory (estimated size 1352.0 B, free 366.2 MB)
18/05/10 11:30:24 INFO BlockManagerInfo: Added input-1-1525951824400 in memory on 10.40.0.19:36645 (size: 1352.0 B, free: 366.3 MB)
18/05/10 11:30:24 INFO BlockGenerator: Pushed block input-1-1525951824400
18/05/10 11:30:28 INFO JobScheduler: Added jobs for time 1525951828000 ms
18/05/10 11:30:29 INFO MemoryStore: Block input-1-1525951829600 stored as values in memory (estimated size 688.0 B, free 366.2 MB)
18/05/10 11:30:29 INFO BlockManagerInfo: Added input-1-1525951829600 in memory on 10.40.0.19:36645 (size: 688.0 B, free: 366.3 MB)
18/05/10 11:30:29 INFO BlockGenerator: Pushed block input-1-1525951829600
18/05/10 11:30:32 INFO JobScheduler: Added jobs for time 1525951832000 ms
18/05/10 11:30:33 INFO MemoryStore: Block input-1-1525951833000 stored as values in memory (estimated size 664.0 B, free 366.1 MB)
18/05/10 11:30:33 INFO BlockManagerInfo: Added input-1-1525951833000 in memory on 10.40.0.19:36645 (size: 664.0 B, free: 366.3 MB)
18/05/10 11:30:33 INFO BlockGenerator: Pushed block input-1-1525951833000
18/05/10 11:30:34 INFO MemoryStore: Block input-1-1525951833800 stored as values in memory (estimated size 640.0 B, free 366.1 MB)
18/05/10 11:30:34 INFO BlockManagerInfo: Added input-1-1525951833800 in memory on 10.40.0.19:36645 (size: 640.0 B, free: 366.3 MB)
18/05/10 11:30:34 INFO BlockGenerator: Pushed block input-1-1525951833800
18/05/10 11:30:34 INFO MemoryStore: Block input-1-1525951834000 stored as values in memory (estimated size 584.0 B, free 366.1 MB)
18/05/10 11:30:34 INFO BlockManagerInfo: Added input-1-1525951834000 in memory on 10.40.0.19:36645 (size: 584.0 B, free: 366.3 MB)
18/05/10 11:30:34 INFO BlockGenerator: Pushed block input-1-1525951834000
18/05/10 11:30:34 INFO MemoryStore: Block input-1-1525951834400 stored as values in memory (estimated size 688.0 B, free 366.1 MB)
18/05/10 11:30:34 INFO BlockManagerInfo: Added input-1-1525951834400 in memory on 10.40.0.19:36645 (size: 688.0 B, free: 366.3 MB)
18/05/10 11:30:34 INFO BlockGenerator: Pushed block input-1-1525951834400
18/05/10 11:30:36 INFO JobScheduler: Added jobs for time 1525951836000 ms
18/05/10 11:30:39 INFO MemoryStore: Block input-1-1525951839600 stored as values in memory (estimated size 688.0 B, free 366.1 MB)
18/05/10 11:30:39 INFO BlockManagerInfo: Added input-1-1525951839600 in memory on 10.40.0.19:36645 (size: 688.0 B, free: 366.3 MB)
18/05/10 11:30:39 INFO BlockGenerator: Pushed block input-1-1525951839600
18/05/10 11:30:40 INFO JobScheduler: Added jobs for time 1525951840000 ms
18/05/10 11:30:42 INFO MemoryStore: Block input-1-1525951842200 stored as values in memory (estimated size 1352.0 B, free 366.1 MB)
18/05/10 11:30:42 INFO BlockManagerInfo: Added input-1-1525951842200 in memory on 10.40.0.19:36645 (size: 1352.0 B, free: 366.3 MB)
18/05/10 11:30:42 INFO BlockGenerator: Pushed block input-1-1525951842200
18/05/10 11:30:43 INFO MemoryStore: Block input-1-1525951843000 stored as values in memory (estimated size 664.0 B, free 366.1 MB)
18/05/10 11:30:43 INFO BlockManagerInfo: Added input-1-1525951843000 in memory on 10.40.0.19:36645 (size: 664.0 B, free: 366.3 MB)
18/05/10 11:30:43 INFO BlockGenerator: Pushed block input-1-1525951843000
18/05/10 11:30:44 INFO MemoryStore: Block input-1-1525951843800 stored as values in memory (estimated size 640.0 B, free 366.1 MB)
18/05/10 11:30:44 INFO BlockManagerInfo: Added input-1-1525951843800 in memory on 10.40.0.19:36645 (size: 640.0 B, free: 366.2 MB)
18/05/10 11:30:44 INFO BlockGenerator: Pushed block input-1-1525951843800
18/05/10 11:30:44 INFO JobScheduler: Added jobs for time 1525951844000 ms
18/05/10 11:30:44 INFO MemoryStore: Block input-1-1525951844000 stored as values in memory (estimated size 584.0 B, free 366.1 MB)
18/05/10 11:30:44 INFO BlockManagerInfo: Added input-1-1525951844000 in memory on 10.40.0.19:36645 (size: 584.0 B, free: 366.2 MB)
18/05/10 11:30:44 INFO BlockGenerator: Pushed block input-1-1525951844000
18/05/10 11:30:44 INFO MemoryStore: Block input-1-1525951844400 stored as values in memory (estimated size 688.0 B, free 366.1 MB)
18/05/10 11:30:44 INFO BlockManagerInfo: Added input-1-1525951844400 in memory on 10.40.0.19:36645 (size: 688.0 B, free: 366.2 MB)
18/05/10 11:30:44 INFO BlockGenerator: Pushed block input-1-1525951844400
18/05/10 11:30:48 INFO JobScheduler: Added jobs for time 1525951848000 ms
...
...
`

**Comment by jbaiera** [comment]
Closing this as there has not been anymore responses. If anything else comes up, we can reopen.
