### ISSUE TITLE
HttpStatus.GATEWAY_TIMEOUT should be 504, is 50

### ISSUE THREAD

**Issue by thumbtack-eee** [elastic/elasticsearch-hadoop#1147]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

`org.elasticsearch.hadoop.rest.HttpStatus.GATEWAY_TIMEOUT` has the wrong value. It's `50` but should be `504`. This results in a `null` response from `org.elasticsearch.hadoop.rest.SimpleResponse.statusDescription` so the explanatory text doesn't show up in logs, but no other consequences that I'm aware of.

### Steps to reproduce

Code:

[`HttpStatus.GATEWAY_TIMEOUT`](/elastic/elasticsearch-hadoop/blob/7b8d4c9b16de8f619c74d1e1928a0918b03aa6c0/mr/src/main/java/org/elasticsearch/hadoop/rest/HttpStatus.java#L100)

Strack trace:

n/a

### Version Info

This is the original configuration it was discovered on, but the bug still exists on the current master.

OS:         :  macOS High Sierra 10.13.4
JVM         :  Oracle 1.8.0_152-b16
Hadoop/Spark:  Spark 2.0.2
ES-Hadoop   :  5.5.1
ES          :  5.5.0, Build: 260387d/2017-06-30T23:16:05.735Z

### Fix

I'd send a PR myself but I don't have a CLA yet. Meanwhile, it's a one-character fix.

**Comment by jbaiera** [comment]
Nice catch on this. I can submit a fix, or I can hold off if you're interested in doing a PR.

**Comment by thumbtack-eee** [comment]
You can submit the fix. Thanks!
