### ISSUE TITLE
[CI] Lucene snapshot detection is still broken

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch-hadoop#1148]
This build failed because it couldn't download the lucene snapshots:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+6.x+periodic/145/console

Digging into the console logs, it's trying to download from the following AWS link:
http://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/6705632810/org/apache/lucene/lucene-core/7.4.0-snapshot-1ed95c097b/lucene-core-7.4.0-snapshot-1ed95c097b.pom

This seems to be mixing up some old and new commit SHAs - the latest SHA is `6705632810`, and the previous SHA is `1ed95c097b`

**Comment by jbaiera** [comment]
Not sure what was causing this, but it seems to have passed. Builds were passing for me locally, and the correct versions were being pulled in those cases. I'll re-open this if it starts failing again, but my guess at this point is that there was some shenanigans with a new snapshot build landing.
