### ISSUE TITLE
Consider chunking the docs to break up long pages and facilitate nav & retrieval

### ISSUE THREAD

**Issue by debadair** [elastic/elasticsearch-hadoop#1150]
Some of the pages are super long, and it's hard for users to navigate to the particular pieces of information they need. For example: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html. 

Changing how the content is chunked or adding in-page nav would make it easier to use.

**Comment by jbaiera** [comment]
#1151 is merged.
