### ISSUE TITLE
how to package elasticsearch-hadoop with gradle+idea

### ISSUE THREAD

**Issue by starrysky-xian** [elastic/elasticsearch-hadoop#1152]
Elasticsearch-hadoop has some problem.
I had rewrite some code and i want to package it.
It throw the exception.
SOS, what`s wrong whit it?
![image](https://user-images.githubusercontent.com/35219069/40154885-60bc7e8a-59c3-11e8-8413-ef8412fd5975.png)

**Comment by tsouza** [comment]
This repository is for reporting specific issues. For general usage help, please use the forum https://discuss.elastic.co/c/elasticsearch-and-hadoop
