### ISSUE TITLE
If the date data in ES format is 2013-12-01 12:12:12.876 will report an error

### ISSUE THREAD

**Issue by dm520** [elastic/elasticsearch-hadoop#116]
If the date data in ES format is 2013-12-01 12:12:12.876 will report an error.

Read through the hive when reporting format error

**Comment by bobrik** [comment]
@costin `2015-05-25T22:30:00+0300` is a valid date for ISO8601, but `JavaEsSparkSQL.esDF()` complains that it's not. Should I create a separate issue for this?

**Comment by costin** [comment]
Please do
