### ISSUE TITLE
Timestamp data from Spark to Elasticsearch

### ISSUE THREAD

**Issue by dipteshnath** [elastic/elasticsearch-hadoop#1173]
Issue description- I need to send timestamp data in format "yyyy-MM-dd hh:mm:ss" from spark SQL dataframe to Elasticsearch. However, when I send the timestamp it changes to unix time format in Elasticsearch. For me, timestamp in Spark(2018-02-01 01:02:59) changes to "timestamp":1517587361000

## Code

1. scala> conf.set("es.resource.write","my-collection/{@timestamp|yyyy-MM-dd'T'HH:mm:ss}")
2. Setup sqlcontext and create dataframe
3. scala> dframe.show()
+----------------------+-------------------+-------------+-------------------+
|UserName|destination_airport|    client_ip|          timestamp|
+----------------------+-------------------+-------------+-------------------+
|            xxxxx|                      xxxx| 10.81.xx.xxx|2018-02-01 01:02:59|
|            xxxxx|                      xxxx| 10.81.xx.xxx|2018-02-01 01:02:00|
|            xxxxx|                      xxxx| 10.81.xx.xxx|2018-02-01 01:02:04|

4. scala> dframe.printSchema()
root
 |-- UserName: string (nullable = true)
 |-- destination_airport: string (nullable = true)
 |-- client_ip: string (nullable = true)
 |-- timestamp: timestamp (nullable = true)

5. scala> dframe.saveToEs("test/docs")

In elasticsearch-
1. $curl -X GET "localhost:9200/test/_search" -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_all": {}
    }
}
'

# OUTPUT-

"_source":{"destination_airport":"XXXX","client_ip":"10.XX.XX.XXX","timestamp":1517587361000}}

OS:         : Mac  
JVM         :  
Hadoop/Spark:Spark 2.3  
ES-Hadoop   :  
ES          :  6.2

**Comment by dipteshnath** [comment]
Thanks for the reply. I did set mapping type. But it did not work for me.

CODE SNIPPET:-

In ES:-
>curl -X PUT "localhost:9200/index12" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "_doc": {
      "properties": {
        "date1": {
          "type":   "date",
          "format": "yyyy-mm-dd"
        }
      }
    }
  }
}
'

In Spark:-
scala> dataOut.select($"date1").show
+----------+
|     date1|
+----------+
|2018-02-01|
|2018-02-01|

scala> dataOut.select($"date1").saveToEs("index12/_doc")

Returns error with String-"Caused by: org.elasticsearch.hadoop.EsHadoopException: Could not write all entries for bulk operation [1000/1000]. Error sample (first [5] error messages):
	failed to parse [date1]"

**Comment by jbaiera** [comment]
This is indeed a bug, but could be construed as a breaking change to fix it, depending on how many users depend on the current use of the epoch milliseconds. This is also already being tracked at https://github.com/elastic/elasticsearch-hadoop/issues/1040, so feel free to post thumbs up on the initial issue. I'll close this one as a duplicate in the mean time.

**Comment by AydinChavez** [comment]
Is there any workaround known? Tried index mapping on ES-side but it doesnt work

**Comment by AydinChavez** [comment]
Want to share my workaround, just create an ingest pipeline in ES with following http request:

```
PUT _ingest/pipeline/fix_date_1173
{
    "description": "converts from unix ms to date, workaround for https://github.com/elastic/elasticsearch-hadoop/issues/1173",
    "processors": [
      {
        "date": {
          "field": "window.start",
          "formats": ["UNIX_MS"],
          "target_field":"window.start"
        }
      },
      {
        "date": {
          "field": "window.end",
          "formats": ["UNIX_MS"],
          "target_field":"window.end"
        }
      }
    ]
  }
```

and enable it in your spark code by
`                        .option("es.ingest.pipeline", "fix_date_1173")
`

**Comment by radhikagfg** [comment]
Hi,
Does this issue Fixed?

**Comment by radhikagfg** [comment]
HI @AydinChavez ,
Is that workaround works?
If yes, then where should i write this in ES/KIbana?

**Comment by radhikagfg** [comment]
HI @dipteshnath
Got the same issue, Could you help me to understand How did you fix it ?

**Comment by vajda** [comment]
I solved it with changing column type to String and converting date to `yyyy-MM-dd'T'HH:mm:ss.SSS.Z` format.
For example, if column is in epoch_seconds, conversion looks like this:
```
df.withColumn("A", date_format(col("A").cast(TimestampType), "yyyy-MM-dd'T'HH:mm:ss.SSSZ"))
```

**Comment by patricwan** [comment]
hi @vajda,
Are you able to save spark dataframe to es with  datetime format? Not a timestamp long type?
I tried in my app(java codes, should be similar)
datasetOrigin = datasetOrigin.withColumn("timestampNew", to_timestamp(col("timestamp"), "yyyy-MM-dd HH:mm:ss,SSS"));
the original col("timestam'") is string type, this line will save to es as long type.

But this line:
datasetOrigin = datasetOrigin.withColumn("timestampNew",date_format(col("timestamp"), "yyyy-MM-dd HH:mm:ss,SSS"));
Will save to ES as null... Seems not passed. Could you give some hints here? What's your original col("A") type, and does the data look like? Just wondering why it can be cast to timestampType directly.

Thanks,

**Comment by patricwan** [comment]
It works for me as well with vajda's help. My java codes.
String esTimeStampFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";
dataset = dataset.withColumn("timestampNew",date_format(to_timestamp(col("timestampStr"), "yyyy-MM-dd HH:mm:ss,SSS"), esTimeStampFormat));

**Comment by FelipeRando** [comment]
> I solved it with changing column type to String and converting date to `yyyy-MM-dd'T'HH:mm:ss.SSS.Z` format, then Elastisearch picks it up automatically.
> For example, if column is in epoch_seconds, conversion looks like this:
> 
> ```
> df.withColumn("A", date_format(col("A").cast(TimestampType), "yyyy-MM-dd'T'HH:mm:ss.SSSZ"))
> ```

worked like a charm, thanks! @vajda

**Comment by Antriksh1234** [comment]
Just to add a little clarification to what @vajda mentioned for someone who is wondering what "A" column is, A is the string of your date. So you may have your date as "2023-02-06 16:00:04.057". Firstly you convert it to a timestamp via the to_timestamp() method and then use the date_format,() to convert it to a string which would automatically be detected as a date field in your elastic search.

to_timestamp()- https://www.google.com/amp/s/sparkbyexamples.com/spark/spark-convert-string-to-timestamp-format/%3famp=1

date_format()-https://www.google.com/amp/s/sparkbyexamples.com/spark/spark-sql-how-to-convert-date-to-string-format/%3famp=1
