### ISSUE TITLE
Support SPNEGO/Kerberos auth to Elasticsearch

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1175]
Work is wrapping up on adding a Kerberos based authentication realm to Elasticsearch. The realm will secure the rest endpoints by means of SPNEGO. Since Kerberos is used heavily in the Big Data space, we should offer an integration that allows for ES-Hadoop to use the currently logged in user and their Kerberos Ticket to authenticate to Elasticsearch over SPNEGO. This should include token authentication and appropriate refreshing mechanisms to avoid the same pitfalls that Hadoop runs into with KDC spamming and token lifetime.

**Comment by vamsi360** [comment]
@jbaiera 
This is great to know. We can now integrate ES also into a centralised Kerberos cluster. Any estimate of when this is going to be released?

**Comment by jbaiera** [comment]
There is a substantial amount of work that is already completed for this feature, but there is quite a bit more to go, including the extensive testing that we will need to eventually run to ensure correctness. 

Additionally, we are working out the best course of action for handling token authentication in worker tasks. The current token functionality in ES is based on OAuth username and password grants, which does not provide tokens that are useable in Hadoop/Spark/Storm (the tokens change between refreshes, last only an hour, can only be refreshed once, etc).

Hopefully soon I will be able to pull together a preliminary PR for the work, but until then, I have the work periodically checked into a feature branch located at https://github.com/elastic/elasticsearch-hadoop/compare/master...jbaiera:feature-kerberos

**Comment by jbaiera** [comment]
This is currently waiting on #1183

**Comment by jbaiera** [comment]
Closed in error.

**Comment by jbaiera** [comment]
This is currently waiting on https://github.com/elastic/elasticsearch/issues/34383 for further development

**Comment by jbaiera** [comment]
#1244 is merged now.
