### ISSUE TITLE
I want to compile the storm-elasticsearch source code, but how to get the pom file?

### ISSUE THREAD

**Issue by zou79189747** [elastic/elasticsearch-hadoop#1177]
I need change something in  storm-elasticsearch source code, so i use maven download elasticsearch-storm-6.3.1-sources.jar, unzip it  and do not found pom file , just a elasticsearch-storm-6.3.1.pom ,but just use elasticsearch-storm-6.3.1.pom can not compile  success , how to get the whole pom file?

**Comment by jbaiera** [comment]
You can just check out the git project, and use grade to build it. We do not use maven for compilations.

**Comment by zou79189747** [comment]
@jbaiera thinks , i got it
