### ISSUE TITLE
Add Rest Client Support for X-Opaque-ID

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1182]
Elasticsearch supports an HTTP header that is sent and returned on each request. Lately, support for this header (X-Opaque-Id) is getting more uses attached to it. Namely, the tasks api now references the opaque id of the request that led to the task, and the id now shows up in the node logs for Elasticsearch. We should make a point to generate meaningful values for this header and attach them to each request made to Elasticsearch.

**Comment by masseyke** [comment]
I forgot to close this when the PRs went in, but this will be in 7.16.0 and 8.0.0.
