### ISSUE TITLE
using storm configuration TOPOLOGY_TICK_TUPLE_FREQ_SECS to flush data to elasticsearch throw NullPointerException

### ISSUE THREAD

**Issue by miaozhongyin** [elastic/elasticsearch-hadoop#1187]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

 I want to index documents into Elasticsearch from Storm using EsBolt  with es-hadoop library,but  i find  my storm topology looks like stuck ,EsBolt can not write data to elasticsearch, while i check out storm work.log, do not find any useful information.when i read es-hadoop document again, i find    EsBolt use micro-batch  mechanism to flush data to elasticsearch,  By default, it uses the same value as es.batch.size.entries which, by default is 1000.so i change my batch size to 5,it's work. but when we setting the value for Config.TOPOLOGY_TICK_TUPLE_FREQ_SECS .it's throw an exception :java.lang.RuntimeException:java.lang.NullPointerException in bolt execute function. then we use debug mode to test my topology, I find the input tuple in bolt execute don't contain any entries, but this empty tuple is been triggered. That's what I feel confusion. Don't the tuple will be emitted according to the setting time, Even though this tuple is empty after we set Config.TOPOLOGY_TICK_TUPLE_FREQ_SECS.
### Steps to reproduce

Code:

```
builder.setBolt("es-writer", new EsBolt(target, conf), numEsBolt)
.addConfiguration(Config.TOPOLOGY_TICK_TUPLE_FREQ_SECS, 5)
.shuffleGrouping("trade-parse");
```

Strack trace:
```
java.lang.NullPointerException
	at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:192) ~[elasticsearch-hadoop-6.3.0.jar:6.3.0]
	at org.elasticsearch.storm.EsBolt.flushWithAck(EsBolt.java:148) ~[elasticsearch-hadoop-6.3.0.jar:6.3.0]
	at org.elasticsearch.storm.EsBolt.flush(EsBolt.java:137) ~[elasticsearch-hadoop-6.3.0.jar:6.3.0]
	at org.elasticsearch.storm.EsBolt.execute(EsBolt.java:110) ~[elasticsearch-hadoop-6.3.0.jar:6.3.0]
	at org.apache.storm.daemon.executor$fn__9639$tuple_action_fn__9641.invoke(executor.clj:730) ~[storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.daemon.executor$mk_task_receiver$fn__9560.invoke(executor.clj:465) ~[storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.disruptor$clojure_handler$reify__9074.onEvent(disruptor.clj:40) ~[storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:472) ~[storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	... 6 more


### Version Info

OS:         :  ubuntu18-desktop
JVM         :  1.8
Hadoop/Spark:  storm-1.1.0
ES-Hadoop   :  6.3.0
ES          :  6.3.0

<!--
If you are filing a feature request, please remove the above bug
report block and provide responses for all of the below items.
-->

### Feature description

**Comment by miaozhongyin** [comment]
when we debug the EsBolt provided by es-Hadoop lib, I find while the execute function received tick tuple, then call the flush function to send data to elasticSearch immediately, Even though the tuple list is empty , so we will get NullPointerException.  Later I overwrite the execute function and add judging conditions for tuple list. it's fine.

###Here is some of the code I overwrite:
Code:
```
public void execute(Tuple input) {
        //isTickTuple function has bugs ,
        if (this.flushOnTickTuple && TupleUtils.isTickTuple(input) && inflightTuples.size()>0) {
            this.flush();
        } else {
            if(!TupleUtils.isTickTuple(input)){
                if (this.ackWrites) {
                    this.inflightTuples.add(input);
                }

                try {
                    this.writer.repository.writeToIndex(input);
                    // numberOfEntries is batch size
                    if (this.numberOfEntries > 0 && this.inflightTuples.size() >= this.numberOfEntries) {
                        this.flush();
                    }

                    if (!this.ackWrites) {
                        this.collector.ack(input);
                    }

                } catch (RuntimeException var3) {
                    if (!this.ackWrites) {
                        this.collector.fail(input);
                    }

                    throw var3;
                }
            }
            }

    }
```

**Comment by jondoe1337** [comment]
This bug is still present in 6.2.1. 
NPE is thrown if a TickTuple is emitted before the first data is sent and the lazyInitWriting method is invoked.

**Comment by vbharghavi** [comment]
facing the same issue.

**Comment by miaozhongyin** [comment]
> facing the same issue
 you can use my methods to resolved this issue.  i have tested ,it's did work.

**Comment by skucukbay** [comment]
This bug still exist for 6.5.4. @miaozhongyin did you create pull request for it ?

**Comment by imazine** [comment]
I facing the same issue on 6.4.1. @miaozhongyin should you create a PR? It is a better solution than we waiting.
