### ISSUE TITLE
sparksql:“Group by” can be pushdown?

### ISSUE THREAD

**Issue by stupidsky** [elastic/elasticsearch-hadoop#1189]
sparksql:"group by" can be pushdown?
I did a “group by” operation, and spark pulled out all the data from es.It spent a lot of time.
Can “group by” operation be implemented in es？Spark only got the result.I think it will save a lot of time.

### Version Info

OS:         :  linux
JVM         :  1.8
Hadoop/Spark:  2.2.0
ES-Hadoop   :  6.0.0
ES          :  6.0.0

**Comment by jbaiera** [comment]
This is covered by #276. Closing as a duplicate.
