### ISSUE TITLE
Examples of MapReduce limits on the number of concurrent maps 

### ISSUE THREAD

**Issue by Downchuck** [elastic/elasticsearch-hadoop#120]
Currently we have to take an extra step of using reducers if we want to limit how many concurrent threads are sending data to ElasticSearch. Otherwise, hundreds of mappers may be hitting the backend with _bulk requests. It'd be nice to see some examples and/or tips on how to handle the situation.

**Comment by jbaiera** [comment]
Closing this as it does not have any actionable items.
