### ISSUE TITLE
Be able to specify preference query string option when querying Elasticsearch

### ISSUE THREAD

**Issue by markpavey** [elastic/elasticsearch-hadoop#1213]
### What kind an issue is this?

- [x ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Feature description
We needed greater control over the shards that elasticsearch-spark queries, in particular we needed to be able to specify the _only_nodes preference option.

We created a patch to do this, which we would ideally like to be added to the main project so we don't need to maintain our own fork, ideally to the 5.X and 6.X branches.

We welcome any comments or suggestions on the linked pull request.

**Comment by jbaiera** [comment]
@markpavey Thanks for submitting a PR for this. Could you walk me through the need for the `_only_nodes` preference option? I want to make sure I understand the underlying requirement for the added setting since this could mess up how ES-Hadoop performs searches if the wrong values are provided.

**Comment by markpavey** [comment]
@jbaiera 

Our situation is that our Elasticsearch cluster is split over two locations (not great, I know). There is one replica of each shard in each location. We have a Spark cluster in each location and to avoid network overhead we want to read the data into each from the Elasticsearch nodes in the same location.

This is more important to us than trying to read data from the same node that a Spark worker is running on but falling back to potentially any node in the cluster.

We are able to do this using Elasticsearch node attributes and specifying the relevant one using _only_nodes in the query preference parameter.
