### ISSUE TITLE
Upgrade to Spark 2.4 and support Scala 2.12

### ISSUE THREAD

**Issue by bpiper** [elastic/elasticsearch-hadoop#1224]
### Feature description

Spark 2.4.0 has recently been released, along with Scala 2.12 support.  For those of us wanting to use Spark 2.4 features or even just enjoy Scala 2.12 binary compatibility, it would be great to update elasticsearch-spark-20 to use Spark 2.4 and support Scala 2.12 builds.

I can offer a PR (currently based off the 6.5 branch) with changes that I've been using in production without issue (and which build against Scala 2.10, 2.11 and 2.12 successfully).  If there is appetite for this, please confirm which branch to target.

**Comment by bpiper** [comment]
Ok, thanks for the good info @jbaiera. I'm actually running with Hadoop 3.1 myself for what it's worth.  I'll leave the build changes in your capable hands, but if there's anything I can help with, let me know.

**Comment by mohammedi-haroune** [comment]
Any plans to merge or to support scala 2.12 and spark 2.4 ?

**Comment by koertkuipers** [comment]
@jbaiera  can you share your work? i dont know much gradle but would like to build this project for scala 2.12
thanks!

**Comment by NielsAlebregtse** [comment]
Any updates when this can be expected?

**Comment by easel** [comment]
I've been kicking the tires on Spark 2.4 + Scala 2.12 at https://github.com/easel/elasticsearch-hadoop/tree/spark24scala212 -- it seems to work but integration tests still are failing and I'm unsure how the packaging side of things is supposed to work.

**Comment by jurriaan** [comment]
The latest stable version of Spark, v2.4.2 defaults to Scala 2.12.

See https://spark.apache.org/downloads.html:

> Note that, Spark is pre-built with Scala 2.12 since version 2.4.2.

This means that the Elasticsearch plugin is incompatible with the latest Spark version. 

Hopefully a newer version will be released which does support Spark 2.4.2

**Comment by erolosty** [comment]
Now that 2.12 is the bundled default, this library really should be updated

**Comment by 0ffkilter** [comment]
Would be nice to have Spark 2.x _and_ Scala 2.12 support since that's now the default bundled version

**Comment by lemieud** [comment]
+1

**Comment by XavierCastillaCarbonell** [comment]
+1

**Comment by EmergentOrder** [comment]
+1

**Comment by EmergentOrder** [comment]
The PR is here: 
https://github.com/elastic/elasticsearch-hadoop/pull/1308

**Comment by XavierCastillaCarbonell** [comment]
Hi, when will be this PR be merged? Thanks!

**Comment by arkershaw** [comment]
Yes, any update on this? Scala 2.11 support is now deprecated in Spark and this is currently preventing us from moving to Scala 2.12.

**Comment by mwol** [comment]
Any news regarding this issue?

**Comment by jordanburke** [comment]
It's awfully quiet on this issue. Is this on the road map? We'd like to know b/c we'll move away from ES for Spark if it's not.

**Comment by cdmitri** [comment]
@jordanburke @jbaiera  I agree, it's long overdue, I was wondering also. The "manual route" as in my comment in
https://github.com/elastic/elasticsearch-hadoop/pull/1308 did work for the for this holiday season :), but it would be great to see it/support merged in one form or the other.

Also: https://github.com/elastic/elasticsearch-hadoop/issues/1412

I am doing a "greenfield" implemnetaiton with elastic at a startup and the fact that this has been unresolved in almost a year is a bit concerning as well.

The fact that 2.12 is not in the main branch is preventing me to upgrade (easily) to new versions for Elastic on elastic cloud that we're paying for :)

**Comment by jeffpicard** [comment]
+1

**Comment by anantmf** [comment]
+1

**Comment by nhiguchi-stb** [comment]
+1

**Comment by sergescc** [comment]
+1

**Comment by bry00** [comment]
+1

**Comment by kaczors** [comment]
+1

**Comment by jsteggink** [comment]
+1

**Comment by mwol** [comment]
it seems there is some progress in https://github.com/elastic/elasticsearch-hadoop/pull/1551

**Comment by mwol** [comment]
Can someone please give an update on this, it is becoming pretty annoying and this issue is now open for more than two years.

**Comment by jbaiera** [comment]
Spark 2.x support on Scala 2.12 will ship as an artifact of the 7.12.0 release. Thanks for everyone's patience and support on this issue.
