### ISSUE TITLE
Return a Java/Scala data structure instead of DataFrame for queries with Spark?

### ISSUE THREAD

**Issue by yeikel** [elastic/elasticsearch-hadoop#1233]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [x] Feature Request. 

### Feature description

Is it possible , or desirable for the connector to return a regular data structure (like a List) instead of a data frame?

For example , I have a Dataframe containing a list of cities as following :

`val cities    = sc.parallelize(Seq("New York")).toDF()`

Now , for each city , I would like to query Elastic and build a set of results similar to the following logic :

```
val cities    = sc.parallelize(Seq("New York")).toDF()
   cities.foreach(r => {
    val city = r.getString(0)
    val dfs = sqlContext.esDF("cities/docs", "?q=" + city ) //returns a DataFrame which triggers a null pointer in Spark
    })
```

Problem is that Spark does not allow nested operations that return dataframes. I think this problem could be resolved if I could get a regular data structure out of the Elastic connection (like a List)

**Comment by jbaiera** [comment]
Closing this because it's a feature that is not within scope of ES-Hadoop. For synchronous read operations within a Spark function you should use the Java Rest Client.

This is elaborated further on the forum post: https://discuss.elastic.co/t/how-do-i-build-results-dinamically-from-a-dataframe-apache-spark/162366
