### ISSUE TITLE
Is there a way to use dynamic indexing through “es.index.write = {index}/type” in writeStream method in spark sturtured streaming?

### ISSUE THREAD

**Issue by faddkhan** [elastic/elasticsearch-hadoop#1268]
I'm using Spark structured streaming to read many files recursively and writing them into elasticsearch. I want to know if there is a way to create index at runtime according to the file name spark reading from folder. Suppose Spark read file from client1 dir so it should index it in elasticsearch as client1.

I've read this article, they did quite easily but the problem is I'm using Spark structured streaming, in which there is no SavetoEs method instead there is WriteStream method.

What i want to do is reading files recursively from different directories and when I'll write them into elasticsearch I want to index them in elasticsearch as i-e file:/home/usr/client/message/single so it should be indexed like "client-message-single" in elasticsearh based on file path.

Code:
file_path= file://home/usr/client/email/message/singlemesage
file_split_path= file_path.split('/')
index = str(file_split_path[-4] + '-' + file_split_path[-3] + '-' + file_split_path[-2])
myjson['doc-index'] =index       //adding key value in my json 
df=myjson.writeStream.option("es.resource.write","{doc-index}/default").outputMode(""append").format("org.elasticsearch.spark.sql").start()
df.awaitTermination()

But using above technique I'm getting following error:

Error:

### Version Info

OS:         :  Ubuntu 16.04
JVM         :  1.8.0_191
Hadoop/Spark:  spark 2.4
ES-Hadoop   :  6.7
ES          :  5.6

**Comment by jbaiera** [comment]
Github is reserved for feature requests and confirmed bug reports only. Please post questions like these on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) in the future.
