### ISSUE TITLE
Spark Read from ES,  query not completing

### ISSUE THREAD

**Issue by arbabkhalil** [elastic/elasticsearch-hadoop#1285]
### Read query on 1 million records from ES running from two hours.

I am using elasticsearch-hadoop connector with spark. It is working but performance is really poor. Simple queries over small data taking too much time and when data size slightly increase, query time becomes huge. 

### Issue description

I have 1.4 million records each having 900 fields, one field is datetime. one is string and rest of fields are  integers. When I do a count or show query it takes hours to complete in case of count and in case of show it did not complete in multiple hours.

My elasticsearch looks like:
```bash
$ curl "localhost:9200/_cat/indices?v"
health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   test_900 yk7fz2SvRC22h3TjfYAuEQ   5   1    1455452       120148     20.5gb         20.5gb
```

### Steps to reproduce
Below is the spark code to reproduce,
Code:

```scala
import org.apache.spark.sql.SQLContext
val sqlContext = new SQLContext(sc) 
import org.elasticsearch.spark.sql._
val options13 = Map("path" -> "test_900", "pushdown" -> "true", "es.nodes" -> "127.0.0.1", "es.port" -> "9200")
 val df1 = sqlContext.load("org.elasticsearch.spark.sql", options13)
scala> val b = System.currentTimeMillis; val count = df1.count; System.currentTimeMillis-b;
b: Long = 1557152465598                                                         
count: Long = 1455452
res16: Long = 4807547 //time taken to count
```
And when I run following query it does not return in even two hours. I know query have coalesce(1) even then I usually run this query on other data bases and does not take much longer.
```scala
val b = System.currentTimeMillis; df1.withColumn("datetime",col("datetime").cast("timestamp")).coalesce(1).sort("datetime").withColumn("datetime",col("datetime").cast("string")).selectExpr("to_json(struct(*)) AS value").show(100,false); System.currentTimeMillis-b
```
### Version Info

OS:         :  Ubuntu 16.04
JVM         :  openjdk version "1.8.0_191"
Hadoop/Spark:  spark-2.3.3-bin-hadoop2.7
ES-Hadoop   :  6.6.2
ES          :  6.6.2

**Comment by jbaiera** [comment]
A key thing to remember here is that when executing a count on data living in Elasticsearch, ES-Hadoop needs to pull all of the data into spark for it to be counted. I would generally advise using a hybrid approach: Use the RDD's for calculations on a per record basis, but for aggregations like counting data, use the java rest client to submit queries directly to ES.

If you are dead set on only using Spark, I would take a look at tuning the scroll size (`es.scroll.size`) that ES-Hadoop uses when retrieving results from Elasticsearch. (See also [the configurations in the docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_network))

This doesn't seem to be a bug or feature request, so I am going to close the issue. If you have any follow up questions or comments, please post them to [the forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) and we can discuss there.
