### ISSUE TITLE
Release of 7.1.0 elasticsearch-spark-20

### ISSUE THREAD

**Issue by yogiraj99** [elastic/elasticsearch-hadoop#1289]
Hi Team,

When do you plan to release the elasticsearch-spark-20_2.11 7.1.0 version.
We are looking for a fix on #1276.

**Comment by Aarong93** [comment]
+1 here looks like its not yet available on Maven

**Comment by jbaiera** [comment]
Hey folks, Github issues are not really the best place for this sort of question. Please ask about these sorts of things on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop). We try to keep ES-Hadoop's Github limited to just feature requests and bug tracking issues only. I appreciate your understanding here!
