### ISSUE TITLE
Timeouts on Scroll Requests can lead to dropped records

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1302]
Scrolled searches are the primary avenue for retrieving data for jobs that read from Elasticsearch. Scroll sessions are started when a reader comes online, the scroll id from each request is used in the subsequent requests, and the session is closed when the scroll is exhausted.

When a node that is serving a scrolled request is overloaded, there is a decent chance that a client scroll request will time out waiting for the results. In these cases, ES-Hadoop will resubmit the scroll request to another node in the cluster. This resubmission can lead to issues if the original scroll request was being processed while the client timed out. 

The first scenario is that the client retries the request on another node and triggers a data race in Elasticsearch (https://github.com/elastic/elasticsearch/issues/35860). The server behaves as if two clients are accessing the scroll request at the same time, which is unsupported, even though it is the single client which has simply timed out waiting for the first request.

The second scenario is that the server successfully retrieves a page of scroll results and updates the internal scroll state to point to the next page of results, but the client times out waiting for the results to arrive and resubmits the request. The resubmitted request may end up succeeding, but the documents that were returned to the timed out request are essentially passed over and not retrieved. This can lead to a job reading fewer records than actually exist in Elasticsearch.

A work around to this issue is to increase the `es.http.timeout` property on ES-Hadoop to a longer time value, causing the connector to wait longer for the result of a search request instead of dropping the response and its contents due to a network timeout.

**Comment by jimczi** [comment]
> A work around to this issue is to increase the es.http.timeout property on ES-Hadoop to a longer time value, causing the connector to wait longer for the result of a search request instead of dropping the response and its contents due to a network timeout.

Another solution would be to not retry the search internally and let hadoop/spark retries the entire task . Otherwise we'd always have the race condition that the scroll request is still running when we retry after a timeout. Setting a timeout to a value greater than the scroll timeout is not enough since the execution time of the request is not taken into account when we compute the last accessed time of a scroll.

**Comment by jbaiera** [comment]
@jimczi This work around is for users who find this issue and need a work around in the interim while the issue is resolved. The plan at the moment is to throw an exception when timing out on a scroll request instead of retrying it on the same task.

**Comment by jimczi** [comment]
> The plan at the moment is to throw an exception when timing out on a scroll request instead of retrying it on the same task.

Ok, thanks for explaining.
