### ISSUE TITLE
[Feature Request]super many http(body) throws to log

### ISSUE THREAD

**Issue by GourdErwa** [elastic/elasticsearch-hadoop#1310]
### Feature description

super many http(body) throws to log.

The log file cannot be viewed normally. 
It is the HTTP body information printed. 
I hope to cut off or provide configuration parameters.

# source 
`org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:469)`

### Version Info

ES-Hadoop   :  7.2.0
ES          :  7.2.0

**Comment by jbaiera** [comment]
This issue does not include very much information that might be helpful to start to try and address it. In the future, it would be better to start a discussion on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) before opening a Github issue for enhancements or features.

**Comment by GourdErwa** [comment]
> This issue does not include very much information that might be helpful to start to try and address it. In the future, it would be better to start a discussion on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) before opening a Github issue for enhancements or features.
If I submit 10MB of data to the ES at a time, if an exception occurs, 10MB of raw data will be printed to the log file, and the entire log file will not be viewed properly. You can test it
