### ISSUE TITLE
How to authenticate with pem and key files and passwords

### ISSUE THREAD

**Issue by tzqtzq** [elastic/elasticsearch-hadoop#1312]
ES 5.4.3
ES-hadoop 5.4.3
SearchGuard 5.4.3
 
I used the security control of SearchGuard, but I used the authentication of pem, key file and password. The following is my java authentication example. How can I complete this authentication in spark?

` Settings settings = Settings.builder()
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMKEY_FILEPATH,"/home/lixiang/tzq/clinet1.key")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMCERT_FILEPATH,"/home/lixiang/tzq/clinet1.pem")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH, "/home/lixiang/tzq/root-ca.pem")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_PEMKEY_PASSWORD, "nit6hwlmtNIL")
                .put(SSLConfigConstants.SEARCHGUARD_SSL_TRANSPORT_ENFORCE_HOSTNAME_VERIFICATION, false)
                .put("client.transport.sniff",false)
                .put("cluster.name","my-es" ).build();`

All I know is to use jks files like the example below.

`conf.set(ConfigurationOptions.ES_NET_SSL_PROTOCOL, "ssl");
        conf.set(ConfigurationOptions.ES_NET_SSL_KEYSTORE_LOCATION, "adminKeystore.jks");
        conf.set(ConfigurationOptions.ES_NET_SSL_KEYSTORE_PASS, "");
        conf.set(ConfigurationOptions.ES_NET_SSL_KEYSTORE_TYPE, ConfigurationOptions.ES_NET_SSL_KEYSTORE_TYPE_DEFAULT);
        conf.set(ConfigurationOptions.ES_NET_SSL_TRUST_STORE_LOCATION, "truststore.jks");
        conf.set(ConfigurationOptions.ES_NET_SSL_TRUST_STORE_PASS, "");`

How can I implement pem certification in spark?

**Comment by jbaiera** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
