### ISSUE TITLE
gradle build  with Problem

### ISSUE THREAD

**Issue by jdbcy** [elastic/elasticsearch-hadoop#1325]
when i use gradle build 6.2.1 tag, got error
Could not resolve all files for configuration ':elasticsearch-hadoop-mr:testCompileClasspath'.
> Could not resolve org.elasticsearch:elasticsearch:6.2.1-SNAPSHOT.
  Required by:
      project :elasticsearch-hadoop-mr
   > Could not resolve org.elasticsearch:elasticsearch:6.2.1-SNAPSHOT.
      > Could not get resource 'https://oss.sonatype.org/content/groups/public/org/elasticsearch/elasticsearch/6.2.1-SNAPSHOT/elasticsearch-6.2.1-SNAPSHOT.pom'.
         > Could not GET 'https://oss.sonatype.org/content/groups/public/org/elasticsearch/elasticsearch/6.2.1-SNAPSHOT/elasticsearch-6.2.1-SNAPSHOT.pom'.
            > Read timed out
when i use  maven { url "https://clojars.org/repo" }
 maven { url "http://conjars.org/repo" }

still error ,how to resolve this problem ????

**Comment by jbaiera** [comment]
This is because the tagging process is specifically to denote the revision of the project that was released. It does not necessarily mean that the project's dependencies will be available forever for building purposes.

**Comment by jbaiera** [comment]
To resolve the error, my advice is to either work against a current version of ES-Hadoop, or set the ES dependency within ES-Hadoop to 6.2.1

**Comment by jdbcy** [comment]
@jbaiera i do as what you say ，i have already resolve ，thank you very much ！！！！！！
