### ISSUE TITLE
When java -jar execute, JavaEsSpark.esRDD raise ExceptionInInitializerError

### ISSUE THREAD

**Issue by maxmin93** [elastic/elasticsearch-hadoop#1358]
### What kind an issue is this?

- [ * ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

I am developing part of spark (v2.4.3) which reads elasticsearch (v7.3.0) on spring-boot 2 (web) using es-hadoop (v7.3.1).

** ref https://www.elastic.co/guide/en/elasticsearch/hadoop/master/spark.html

When I run it with "mvn spring-boot:run" it works fine.

But, When I run it with "java -jar output.jar", JavaEsSpark make error about accessing elasticsearch. I thought in many ways but I don't know why.

"ExceptionInInitializerError: null .. RestService" 
"sql.DefaultSource15 could not be instantiated" 
"URI is not a hierarchical .. version."

I ask for your help (-.-)

** ps. I checked packages in jar file. => OK. I tried with SparkSession, but also fail. (java -jar execution)

** my code https://github.com/maxmin93/agens-spark/blob/master/src/main/java/net/bitnine/agensspark/AgenssparkApplication.java

### Steps to reproduce

Code:

```java
LOGGER.info("SpringBootSpark To Elasticsearch Application: {}, {}, {}, {}"
                , appName, nodes, port, sparkHome);

String master = "local[*]";
SparkConf conf = new SparkConf()
        .setAppName(appName)
        .setSparkHome(sparkHome)
        .setMaster(master)
                .set("spark.executor.memory", "2g")
        .set("spark.driver.memory", "2g")
        .set("spark.eventLog.enabled","false")
        .set("es.nodes.wan.only", "true")
        .set("es.nodes", nodes)
        .set("es.port", port)
        .set("es.mapping.id", "id")
        .set("es.write.operation", "upsert")
        .set("es.index.read.missing.as.empty", "true");

        JavaSparkContext jsc = new JavaSparkContext(conf);

// for DEBUG
System.out.println("\n\n==================================\n");
System.out.println(Arrays.stream(jsc.getConf().getAll()).map(t->{
    return t._1()+"="+t._2();
}).collect(Collectors.joining(", ")));

JavaPairRDD<String, Map<String, Object>> esRDD =
    JavaEsSpark.esRDD(jsc, resource, "?q=datasource:sample");
System.out.println("\n**count = "+esRDD.count());
```

Strack trace:

```
java.lang.ExceptionInInitializerError: null
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:216) ~[elasticsearch-hadoop-7.3.1.jar!/:7.3.1]
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:79) ~[elasticsearch-hadoop-7.3.1.jar!/:7.3.1]
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:78) ~[elasticsearch-hadoop-7.3.1.jar!/:7.3.1]
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:48) ~[elasticsearch-hadoop-7.3.1.jar!/:7.3.1]
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253) ~[spark-core_2.11-2.4.3.jar!/:2.4.3]
...
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418) ~[na:1.8.0_121]
	at org.elasticsearch.hadoop.util.IOUtils.toCanonicalFilePath(IOUtils.java:242) ~[elasticsearch-hadoop-7.3.1.jar!/:7.3.1]
	at org.elasticsearch.hadoop.util.Version.<clinit>(Version.java:66) ~[elasticsearch-hadoop-7.3.1.jar!/:7.3.1]
	... 27 common frames omitted
``` 

### Version Info

OS:         :  MacOS lastest
JVM         :  1.8
Hadoop/Spark:  null/2.4.3
ES-Hadoop   :  7.3.1
ES          :  7.3.0

**Comment by jbaiera** [comment]
How are you constructing your jar file for your operation? Are you adding ES-Hadoop as a jar to your classpath? Are you repackaging it in with your client code in a new jar? The error indicates that the path to the Version.class file is not hierarchical which means that it may not be packaged correctly or accessable in a way that ES-Hadoop expects it to be.

**Comment by maxmin93** [comment]
Thanks a lot of your reply.

Spring boot executable jar is made by spring-boot-maven-plugin in pom.xml as normally. And I exactly declared dependency about "es-hadoop" or "es-spark". And I made sure confirm the existence of dependency libraries on my target jar file.

I tried another way like as using CLASSPATH env variable or run jar with -Dload.path or -cp, so on..
But all did not work. And I tried using local maven repository although maven can access es-hadoop libraries through Central repository.

I have been holding this problem for over a few week. OTL
----------------
java -jar target/agensspark-0.0.1-SNAPSHOT.jar -Dloader.path=/Users/bgmin/Servers/es-hadoop/dist/

jar -tf agensspark-0.0.1-SNAPSHOT.jar (<-- my target jar file)
==>
BOOT-INF/lib/elasticsearch-hadoop-7.3.2.jar
...
BOOT-INF/lib/hadoop-annotations-2.6.5.jar
BOOT-INF/lib/hadoop-auth-2.6.5.jar
BOOT-INF/lib/hadoop-client-2.6.5.jar
BOOT-INF/lib/hadoop-common-2.6.5.jar
BOOT-INF/lib/hadoop-hdfs-2.6.5.jar
BOOT-INF/lib/hadoop-mapreduce-client-app-2.6.5.jar
BOOT-INF/lib/hadoop-mapreduce-client-common-2.6.5.jar
BOOT-INF/lib/hadoop-mapreduce-client-core-2.6.5.jar
BOOT-INF/lib/hadoop-mapreduce-client-jobclient-2.6.5.jar
BOOT-INF/lib/hadoop-mapreduce-client-shuffle-2.6.5.jar
BOOT-INF/lib/hadoop-yarn-api-2.6.5.jar
BOOT-INF/lib/hadoop-yarn-client-2.6.5.jar
BOOT-INF/lib/hadoop-yarn-common-2.6.5.jar
BOOT-INF/lib/hadoop-yarn-server-common-2.6.5.jar
..
BOOT-INF/lib/spark-catalyst_2.11-2.4.3.jar
BOOT-INF/lib/spark-core_2.11-2.4.3.jar
BOOT-INF/lib/spark-graphx_2.11-2.4.3.jar
BOOT-INF/lib/spark-kvstore_2.11-2.4.3.jar
BOOT-INF/lib/spark-launcher_2.11-2.4.3.jar
BOOT-INF/lib/spark-mllib-local_2.11-2.4.3.jar
BOOT-INF/lib/spark-network-common_2.11-2.4.3.jar
BOOT-INF/lib/spark-network-shuffle_2.11-2.4.3.jar
BOOT-INF/lib/spark-sketch_2.11-2.4.3.jar
BOOT-INF/lib/spark-sql_2.11-2.4.3.jar
BOOT-INF/lib/spark-tags_2.11-2.4.3.jar
BOOT-INF/lib/spark-unsafe_2.11-2.4.3.jar

**Comment by jbaiera** [comment]
> I have been holding this problem for over a few week. OTL

I'm sorry to hear that! It certainly sounds like a frustrating situation. We get these issues for this kind of error message occasionally, but most times they are closed without any action due to lack of user feedback. I want to thank you for getting this info back to us! Your jar contents definitely highlight the issue here. It seems that the Spring Boot plugin includes the dependencies of the jars in your project nested inside the final jar. This is what is causing the hierarchical URI error.

When ES-Hadoop is first loaded, it runs some checks within the `Version` class that ensure that only one copy/version of ES-Hadoop is available on the classloader. This is to ensure no Jar-Hell issues while running (which was more common than one would think without the check). 

To verify that condition, the ES-Hadoop asks the current classloader for all copies of the `Version` class that it knows about. The classloader returns a set of URL's (either jars or .class files) that are then validated by ES-Hadoop to ensure no duplicates. We canonicalize each URL to eliminate false duplicates, like if a jar appears twice because of symlinks in the classpath. Finally, if only one unique URL remains, we can be sure that there's only one ES-Hadoop library available and the check passes.

The issue here is that the location of the jar file that ES-Hadoop finds is _within_ another jar file, which cannot be resolved as a canonical filepath because it is inside an archive file. In this case, the ES-Hadoop jar is located at:
```
file:///path/to/agensspark-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/elasticsearch-hadoop-7.3.2.jar
```
... which is not a hierarchical URI.

I'll classify this as a bug for now. Since Spring Boot is so widely used, we should probably add some logic to handle this nested jar case in the Jar-Hell check. As a temporary fix, you may need to remove ES-Hadoop from your Spring Boot jar and specify it as a library on the `-cp` option.

**Comment by maxmin93** [comment]
Thank you very much for your kind reply.
Your explanation made me understand enough, and I'll keep an eye on that Debug issue.

**Comment by maxmin93** [comment]
I try as your advice.

jar -tf target/agensspark-0.0.1-SNAPSHOT.jar | grep elastic
==> Nothing

java -jar target/agensspark-0.0.1-SNAPSHOT.jar -cp ~/Servers/es-hadoop/dist/elasticsearch-hadoop-7.3.1.jar
==> 
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.spark.rdd.api.java.JavaEsSpark

Uhm.. like some kind of difficult

```xml
<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch-hadoop</artifactId>
    <version>${es-hadoop.version}</version>
    <scope>provided</scope>
</dependency>
...
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <excludes>
            <exclude>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch-hadoop</artifactId>
            </exclude>
        </excludes>
    </configuration>
</plugin>
```

**Comment by hw2814** [comment]
FWIW If anyone else is having this issue and uses the [spring boot gradle plugin](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-configuring-unpacking) adding the line `requiresUnpack '**/elasticsearch-hadoop*.jar'` to the bootJar fixed it for me. It looks like the [maven plugin has something similar](https://docs.spring.io/spring-boot/docs/current/maven-plugin/repackage-mojo.html#requiresUnpack).

**Comment by maxmin93** [comment]
@hw2814 Thanks, but still has same error. 

I made build.gradle and add "requiresUnpack" as you said.
** esHadoopVersion="7.3.2"

```
bootJar {
    requiresUnpack '**/elasticsearch-hadoop*.jar'
}
```

But, With "gradle bootRun" it works fine.

**Comment by carlose2108** [comment]
Hi there!

Any help with this?

**Error message:**
" java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:577)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:65)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:108)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:108)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)"

**My code is:**

```
val ss: SparkSession = SparkSession
                .builder()
                .appName("WriteToES")
                .getOrCreate()

val esConf = Map("es.nodes" -> "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.es.amazonaws.com", 
                         "es.port" -> "443",
                         "es.net.http.auth.user" -> "xxxxxxxxx",
                         "es.net.http.auth.pass" -> "xxxxxx",
                         "es.nodes.discovery" -> "true",
                         "es.index.auto.create" -> "true",
                         "es.nodes.wan.only" -> "true",
                         "es.net.ssl" -> "true"
                         )

        Kinesis.buildStream(ssc, stream, credentials)
            .map(Gzip.decompress)
            .flatMap(Strings.bytesToStringLines)
            .transform(Json.jsonToZabbixTypes[ZabbixItemInteger](_))
            .transform(rdd => {
               EsSpark.saveToEs(rdd, "spark/docs", esConf)
                rdd                
            })

```
**Spark-submit:**
```
spark-submit \
       	--name KinesisGzipElastic \
       	--class Main \
       	--master local[*] \
        --deploy-mode client \
        --packages org.apache.spark:spark-streaming-kinesis-asl_2.12:3.0.0,org.elasticsearch.client:elasticsearch-rest-high-level-client:7.7.0 \
        trkinesisgzipelastic_2.12-0.1.0-SNAPSHOT.jar
```

This situation is very frustrated.

Hope you can help!

**Comment by zxdposter** [comment]
@jbaiera I have same iusse too, `URI is not hierarchical`

the reason is cause by `org/springframework/boot/loader/jar/Handler.class` when package boot jar, it will be included in 
 and redefine url `openConnection` behavior.

I'm glad to see that the latest version has already fixed the problem, but I used `org.elasticsearch:elasticsearch-spark-20_2.11:7.10.1` no repair.

So I covered `IOUtils` and fixed it.

**Comment by zxdposter** [comment]
@jbaiera I have a question, if I use spring boot jar, what value should I put on `spark.jars`?

some thins like `file:/xxx-spring-boot-272428e08c.jar!/BOOT-INF/lib/elasticsearch-spark-20_2.11-7.10.1.jar` not woking.

**Comment by jbaiera** [comment]
@zxdposter I would suggest updating to 8.2.0+ to pick up the official change. If you are stuck on an older version you will need to remove the es hadoop dependencies from your boot jar and add them on java's normal classpath.

**Comment by cloudhuang** [comment]
> @hw2814 Thanks, but still has same error.
> 
> I made build.gradle and add "requiresUnpack" as you said. ** esHadoopVersion="7.3.2"
> 
> ```
> bootJar {
>     requiresUnpack '**/elasticsearch-hadoop*.jar'
> }
> ```
> 
> But, With "gradle bootRun" it works fine.
> 
> ==================================
> 
> Thanks a lot!! In maven, it works!!
> 
> pom.xml
> 
> ```
> <plugin>
> 	<groupId>org.springframework.boot</groupId>
> 	<artifactId>spring-boot-maven-plugin</artifactId>
>     <executions>
>         <execution>
>             <goals>
>                 <goal>repackage</goal>
>             </goals>
>         </execution>
>     </executions>
>     <configuration>
>         <requiresUnpack>
>             <dependency>
> 		<groupId>org.elasticsearch</groupId>
> 		<artifactId>elasticsearch-spark-20_${scala.base}</artifactId>
>             </dependency>
>         </requiresUnpack>
>     </configuration>
> </plugin>
> ```
> 
> oh yeah~~~

Thanks a lot!! In maven, it works!! You really did me a big favor, thanks.
