### ISSUE TITLE
Re-enable QA Kerberos Tests

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#1366]
The QA Kerberos tests were disabled immediately after they were added earlier in the year due to some issues with their compatibility with our CI environment. First and foremost, there are a set of jobs that fail due to path resolution errors: Hadoop incorrectly treats + signs in paths as spaces, and thus, file paths under the project in CI are broken. See #1251 .

Additionally, even getting the jobs to respect path names correctly in CI still encounters failures. The YARN environment needs to be tuned for the lower amount of memory available in the CI environment. Right now, the default settings are far too greedy and need to be reigned in.

Finally, after retrying to run them in a local test environment, it seems that auth issues are starting to occur due to local host name resolution on Kerberos. Further investigation is required into these failures.

Relates #1251

**Comment by masseyke** [comment]
I think that this is the relevant commit right? https://github.com/elastic/elasticsearch-hadoop/commit/b3547fc42785ca071583178d1e4317262772435e
