### ISSUE TITLE
es.input.max.docs.per.partition invalid for spark2.2 es6.1.3

### ISSUE THREAD

**Issue by pokerWu** [elastic/elasticsearch-hadoop#1407]
In 5 shards cluster, the Index has more than two hundred million records.

spark: 2.2.0 
elasticsearch: 6.1.3
elasticsearch-hadoop: 6.1.3

set `es.input.max.docs.per.partition=2000000` or not set the partition always equals shards.
each partition has more than 20gb data.

Track code about partitions been created in debug mode, `findSlicePartitions` method was called and get the right paritions. But, in spark web ui and console log, the task numbers still equals shards.

**Comment by jbaiera** [comment]
Can you share your job configuration here? Can you also make sure that the setting is getting picked up by the job in the spark web ui? Depending on where you add the configuration you may need to prefix it (`spark.es.input.max.docs.per.partition`)

**Comment by pokerWu** [comment]
@jbaiera hi,
I found out the problem, cause by apache spark partition  strategy.
Because there only only one stage load and then write. If force repartition, the read  stage satisfies the configuration
