### ISSUE TITLE
[CI] Master branch - AbstractScalaEsScalaSpark testNewIndexWithTemplate fails

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch-hadoop#1417]
## Example build failure

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+master+periodic/234/

## Reproduction line
This does reproduce locally. There's no steps to reproduce in the build output but the following worked for me:
```
./gradlew :elasticsearch-spark-13:integrationTest -Pdistro=hadoopYarn --tests="SparkScalaSuite"
```

## Example relevant log:
```
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: org.elasticsearch.hadoop.rest.EsHadoopRemoteException: parse_exception: unknown key [template] in the template 

{
"template" : "spark-template-*",
"settings" : {
    "number_of_shards" : 1,
    "number_of_replicas" : 0
},
"mappings" : {
    "properties" : {
      "name" : { "type" : "keyword" },
      "number" : { "type" : "long" },
      "@ImportDate" : { "type" : "date" }
     }
   }},
"aliases" : { "spark-temp-index" : {} }
}
```

## Frequency

This test has been failing once a day since January 11th. The exceedingly strange thing is that there don't seem to have been any code changes on the master branch that would have caused this, so it's a bit mysterious to me. Perhaps something changed in an upstream repo?

**Comment by polyfractal** [comment]
Another instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+master+periodic/238/console
