### ISSUE TITLE
es bulk sizes and entries

### ISSUE THREAD

**Issue by ik8** [elastic/elasticsearch-hadoop#1419]
Hey, I'm trying to understand the bulk api here,
I use two es-spark config on context init:
`es.batch.size.bytes: 15mb`
`es.batch.size.entries: 1000`
once i write to a single shard index it works perfectly, 1000 docs in a bulk(the average document size is about 1.1kb), but when I write to another index with more than one shard, the bulk becomes smaller, for index with 4 shards, the average bulk size is about 250.
I use the same configuration for every write so I guess it's the number of shards because I don't see any other difference.
Is that it? how can I make the bulk size back to 1000? It really overloads my cluster.

And another quite general question,
Is there a convention for limiting the amount of docs the jar writes to elastic? maybe a configuration I missed. 
For now I use a low number of partitions because it's the only solution that works for me.

**Comment by jbaiera** [comment]
Thanks for your interest in the project, but in the future, please post questions like these on our project [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop). We try to keep Github cleared of user questions and only track verified bugs and feature requests here. If you drop a post on forum I'd be happy to respond and engage there. Thanks!
