### ISSUE TITLE
If possible add an example of usage with https://spark.incubator.apache.org

### ISSUE THREAD

**Issue by rbraley** [elastic/elasticsearch-hadoop#142]
It should be possible since it can use any hadoop input formats.

Bonus points if we can figure out how to use shark with it.

**Comment by emwalker** [comment]
@costin, any thoughts on getting the native ES integration to work in PySpark?  I see that there is a https://github.com/TargetHolding/pyspark-elastic project, but it looks like a one-off, and don't know enough yet about the relevant code to have an opinion on whether it's taking the right approach.

**Comment by costin** [comment]
@emwalker outside the scope of the project for the near future. ES-Hadoop/Spark is based on the JVM (Java/Scala), a PySpark integration would have to be in Python. 

P.S. For questions/discussions the [forum](discuss.elastic.co) is much better suited than the issue tracker.

**Comment by MLnick** [comment]
@emwalker you should be able to use PySpark's InputFormat methods to read from ES using the ES-Hadoop InputFormats:

I provided an example using ES under http://spark.apache.org/docs/latest/programming-guide.html#external-datasets under the Python section

e.g. this works with Spark 1.4.1 - at least for simple fields. If you have some really complex data schema, it may fall down, but you can write your own custom SerDe using the `Converter` trait (it must be done in Scala/Java though) - the doc link above has some details and links to examples.

``` python
$ ./bin/pyspark --driver-class-path /path/to/elasticsearch-hadoop.jar
>>> conf = {"es.resource" : "index/type"}   # assume Elasticsearch is running on localhost defaults
>>> rdd = sc.newAPIHadoopRDD("org.elasticsearch.hadoop.mr.EsInputFormat",\
    "org.apache.hadoop.io.NullWritable", "org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=conf)
>>> rdd.first()         # the result is a MapWritable that is converted to a Python dict
(u'Elasticsearch ID',
 {u'field1': True,
  u'field2': u'Some Text',
  u'field3': 12345})
```

You can also use the SQL loader:
``` python
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)
df = sqlContext.read.format("org.elasticsearch.spark.sql").load("index/type")
df.printSchema()
```
