### ISSUE TITLE
unable to read flattened type field using pyspark connector.

### ISSUE THREAD

**Issue by amendhe** [elastic/elasticsearch-hadoop#1421]
After reading index from elasticsearch using pyspark in databricks - All fields appeared but only one field which is a type of 'flattened' type not appeared in dataframe schema. Is there any option that i need to include during read. Following is my snippet to read from index.
```
spark.read.format("org.elasticsearch.spark.sql")\
      .option("es.nodes", ",".join(db['nodes']))\
      .option("es.mapping.date.rich", "false")\
      .option("es.net.http.auth.user", 'abc')\
      .option("es.net.http.auth.pass", '123abc')\
      .load('indexname')
```
elasticsearch: 7.5.1
spark: 2.4.3

**Comment by jbaiera** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
