### ISSUE TITLE
TOMCAT crashes due to PDF font . ERROR ((CTRL-CHAR, code9)):

### ISSUE THREAD

**Issue by Alexx2020767** [elastic/elasticsearch-hadoop#1428]
Hi all,
I have this type of issue:
When users print a PDF document with **special characters** **tomcat crashes** with the error below.
![01 error](https://user-images.githubusercontent.com/61049351/74531298-8f53a380-4f2c-11ea-9276-b50651cf97f0.png)

I understand that the users should not have these characters, but unfortunately if operating systems allows it, I will continue to face this type of issue. The HP DAS application works as per normal (spools and delivers the print job meta data to the server).
![02 error](https://user-images.githubusercontent.com/61049351/74531336-a98d8180-4f2c-11ea-98ab-014feaa57acc.png)

Do you have any suggestion about the error above?
Thanks and regards!
Alex

**Comment by jbaiera** [comment]
This does not look like an ES-Hadoop issue. Closing.
