### ISSUE TITLE
Build failure Could not find org.elasticsearch.gradle:build-tools:7.6.3-SNAPSHOT

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch-hadoop#1459]
Could not resolve all files for configuration ':buildSrc:compileClasspath'.
13:57:50    > Could not find org.elasticsearch.gradle:build-tools:7.6.3-SNAPSHOT.

Lo:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+7.6+periodic/80/console

Should this point to 7.7 instead?

**Comment by jakelandis** [comment]
Thanks @mayya-sharipova for the report.  That is the correct dependency, but (for other reasons being addressed) the 7.6.3-SNAPSHOT has not been built yet. (there is a bit of a chicken/egg problem with some of the snapshot builds).  

I will leave this issue open until things work themselves out.
