### ISSUE TITLE
org/elasticsearch/hadoop/EsHadoopIllegalStateException : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by kevinzpw** [elastic/elasticsearch-hadoop#1462]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description
java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider org.elasticsearch.spark.sql.DefaultSource15 could not be instantiated: java.lang.UnsupportedClassVersionError: org/elasticsearch/hadoop/EsHadoopIllegalStateException : Unsupported major.minor version 52.0
org/elasticsearch/hadoop/EsHadoopIllegalStateException : Unsupported major.minor version 52.0
if i use jdk1.8 normal
### Steps to reproduce

Code:
 DataFrame df = sqlContext.read().format("org.elasticsearch.spark.sql").options(esOptions).load("index");
        DataFrame dfr = sqlContext.read().format("org.elasticsearch.spark.sql").load("index/_doc");

```
### Version Info

OS:         :  linux
jdk         :  1.7.0_51
Hadoop/Spark:  1.6.0
ES-Hadoop   :          <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-spark-13_2.10</artifactId>
            <version>7.3.0</version>
        </dependency>
ES          :   7.3.0

<!--
If you are filing a feature request, please remove the above bug
report block and provide responses for all of the below items.
-->

### Feature description

**Comment by jbaiera** [comment]
Java 7 is no longer supported by the connector as of version 7.0.0. Please upgrade to Java 8.

This deprecation and removal is detailed in https://github.com/elastic/elasticsearch-hadoop/issues/1200
