### ISSUE TITLE
How search es using spark-sql with 'function match' or others

### ISSUE THREAD

**Issue by ZBHdd** [elastic/elasticsearch-hadoop#1469]
### Issue description
now,I want select es using '**spark-sql**',but '**predicate pushdown**' does not take effect
Description

### Steps to reproduce

Code:
first I create a index
```
curl -H "Content-Type: application/json" -XPOST  'http://localhost:9200/myindex/_mapping?pretty=true' -d '
{
  "properties": {
        "author" : {
          "type" : "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_max_word",
          "fields": {
            "raw": { 
              "type":  "keyword"
            }
        }

        },
        "name" : {
          "type" : "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_max_word",
          "fields": {
            "raw": { 
              "type":  "keyword"
            }
        }
        },
         "uuid" : {
          "type" : "keyword"
        } 
    }                   
}' 
```
and create a global_temp table in spark
```
val conf = new SparkConf().setMaster("local").setAppName("sss").set("es.nodes", "countly-new002").set("es.port", "9200").set("pushdown", "true")
val spark = SparkSession.builder().master("local[*]").appName("spark_es").config(conf).enableHiveSupport().getOrCreate()
var df = spark.read.format("org.elasticsearch.spark.sql").options(Map("es.nodes" -> "countly-new002", "es.port" -> "9200", "es.resource" -> "myindex", "es.index.auto.create" -> "false", "pushdown" -> "true", "strict" -> "false")).load();
df.createOrReplaceGlobalTempView("myindex")
HiveThriftServer2.startWithContext(spark.sqlContext)
```

when I search data from ES using spark-sql:
```
select * from global_temp.myindex where  name = '慕容公子' limit 10;
+---------+-------+-------+--+
| author  | name  | uuid  |
+---------+-------+-------+--+
+---------+-------+-------+--+
```
```
explain select * from global_temp.myindex where  name = '慕容公子' limit 10;
| == Physical Plan ==
CollectLimit 10
+- *(1) Filter (isnotnull(name#1) && (name#1 = 慕容公子))
   +- *(1) Scan ElasticsearchRelation(Map(es.internal.spark.sql.pushdown -> true, es.index.auto.create -> false, es.port -> 9200, es.resource -> myindex, es.nodes -> countly-new002, es.internal.spark.sql.pushdown.strict -> false),org.apache.spark.sql.SQLContext@2fc0ad21,None) [author#0,name#1,uuid#2] PushedFilters: [IsNotNull(name), EqualTo(name,慕容公子)], ReadSchema: struct<author:string,name:string,uuid:string>  
```

the PushedFilters are '[IsNotNull(name), EqualTo(name,慕容公子)]'
and 'es.internal.spark.sql.pushdown.strict' is false.

SQL syntax | ES 1.x/2.x syntax | ES 5.x syntax
-- | -- | --
= null , is_null | missing | must_not.exists
= (strict) | term | term
= (not strict) | match | match
\> , < , >= , ⇐ | range | range
is_not_null | exists | exists
in (strict) | terms | terms
in (not strict) | or.filters | bool.should
and | and.filters | bool.filter
or | or.filters | bool.should [bool.filter]
not | not.filter | bool.must_not
StringStartsWith | wildcard(arg*) | wildcard(arg*)
StringEndsWith | wildcard(*arg) | wildcard(*arg)
StringContains | wildcard(*arg*) | wildcard(*arg*)
EqualNullSafe (strict) | term | term
EqualNullSafe (not strict) | match | match

that should execute 'match' in es , but not.
when I execute 'match' with eql is
```
select * from myindex where  match(name,'慕容公子') limit 10;
author|name|uuid                
----|----|----
金庸| 纷纷猜测是慕容公子与小姐外出踏青了。|1c5249c4-91a1-11ea-ac36-00163e014c29
```
using spark-sql
```
select * from global_temp.myindex where  match(name,'慕容公子') limit 10;
Error: org.apache.spark.sql.AnalysisException: Undefined function: 'match'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 41 (state=,code=0)
```
### Version Info

OS:         :  centos7
JVM         :  jdk1.8
Hadoop/Spark:   spark 2.3.2
ES-Hadoop   :  elasticsearch-hadoop-7.6.2
ES          :  elasticsearch 7.6.2

How search es using spark-sql with 'function match' or can I execute 'match' using spark-sql with other ways？thk.

**Comment by jbaiera** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
