### ISSUE TITLE
BUILD FAILED in Task :elasticsearch-hadoop-mr:generateGitHash FAILED （elasticsearch-hadoop-7.8）

### ISSUE THREAD

**Issue by ZBHdd** [elastic/elasticsearch-hadoop#1475]
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8>gradlew distZip

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.0/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
===================================
ES-Hadoop Build Hamster says Hello!
===================================
Building version [7.8.0-SNAPSHOT]
Testing against Elasticsearch [7.8.0-SNAPSHOT] with Lucene [8.5.1]
Using Gradle [6.0]
Using Apache Hadoop [2.2.0]

> Configure project :elasticsearch-spark-13
Compiled using Scala 2.11 [2.11.12]

> Configure project :elasticsearch-spark-20
Compiled using Scala 2.11 [2.11.12]

> Task :elasticsearch-hadoop-mr:compileJava
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\rest\RestClient.java:373: 警告: [unchecked] 未经检查的转换
        Map<String, Object> fieldInfo = (Map<String, Object>) foundFields.get("_source");
                                                                             ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\rest\RestClient.java:661: 警告: [unchecked] 未经检查的转换
        Map<String, Object> aliases = (Map<String, Object>) get(query, null);
                                                               ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\NodeInfo.java:49: 警告: [unchecked] 未经检查的转换
            Map<String, Object> attributes = (Map<String, Object>) map.get("attributes");
                                                                          ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\NodeInfo.java:60: 警告: [unchecked] 未经检查的转换
            List<String> roles = (List<String>) map.get("roles");
                                                       ^
  需要: List<String>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\NodeInfo.java:65: 警告: [unchecked] 未经检查的转换
        Map<String, Object> httpMap = (Map<String, Object>) map.get("http");
                                                                   ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\IndicesAliases.java:76: 警告: [unchecked] 未经检查的转换
            final Map<String, Object> metadata = (Map<String, Object>) index.getValue();
                                                                                     ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\IndicesAliases.java:77: 警告: [unchecked] 未经检查的转换
            final Map<String, Map<String, Object> > aliases = (Map<String, Map<String, Object> >) metadata.get("aliases");
                                                                                                              ^
  需要: Map<String,Map<String,Object>>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\IndicesAliases.java:95: 警告: [unchecked] 未经检查的转换
                    filter = (Map<String, Object>) aliasMetadata.get("filter");
                                                                    ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\rest\request\GetAliasesRequestBuilder.java:68: 警告: [unchecked] 未经检查的转换
        return new Response((Map<String, Object>) client.get(path.toString(), null));
                                                            ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\mr\MultiOutputFormat.java:52: 警告: [unchecked] 对作为原始类型RecordWriter的成员的write(K,V)的调用未经过检查
                writer.write(key, value);
                            ^
  其中, K,V是类型变量:
    K扩展已在类 RecordWriter中声明的Object
    V扩展已在类 RecordWriter中声明的Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\mr\MultiOutputFormat.java:83: 警告: [unchecked] 对作为原始类型RecordWriter的成员的write(K,V)的调用未经过检查
                writer.write(key, value);
                            ^
  其中, K,V是类型变量:
    K扩展已在接口 RecordWriter中声明的Object
    V扩展已在接口 RecordWriter中声明的Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\mr\MultiOutputFormat.java:257: 警告: [unchecked] 参数化 vararg 类型Class<? extends OutputFormat>的堆可能已受污染
    public static void addOutputFormat(Configuration cfg, Class<? extends OutputFormat>... formats) {
                                                     ^
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\rest\query\RawQueryBuilder.java:58: 警告: [unchecked] 未经检查的转换
        this((Map<String, Object>) MAPPER.readValue(value, HashMap.class), isQuery);
                                                   ^
  需要: Map<String,Object>
  找到:    HashMap
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\bulk\AbstractBulkFactory.java:156: 警告: [unchecked] 对作为原始类型ValueWriter的成员的write(T,Generator)的调用未经过检查
                valueWriter.write(value, generator);
                                 ^
  其中, T是类型变量:
    T扩展已在接口 ValueWriter中声明的Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\mapping\FieldParser.java:54: 警告: [unchecked] 未经检查的转换
        Map<String, Object> mappingsObject = (Map<String, Object>) indexToMappings.getValue();
                                                                                           ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\mapping\FieldParser.java:60: 警告: [unchecked] 未经检查的转换
        Map<String, Object> mappingEntries = (Map<String, Object>) mappingsObject.get("mappings");
                                                                                     ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\mapping\FieldParser.java:102: 警告: [unchecked] 未经检查的转换
            Map<String, Object> content = (Map<String, Object>) value;
                                                                ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\mapping\FieldParser.java:151: 警告: [unchecked] 未经检查的转换
            Map<String,Object> fieldValueAsMap = ((Map<String, Object>)fieldValue);
                                                                       ^
  需要: Map<String,Object>
  找到:    Object
D:\profiles\ChromDownload\elasticsearch-hadoop-7.6.2\dist\elasticsearch-hadoop-7.8\mr\src\main\java\org\elasticsearch\hadoop\serialization\dto\mapping\MappingUtils.java:198: 警告: [unchecked] 未经检查的转换
            Map<String, Object> geoShape = (Map<String, Object>) parsedContent;
                                                                 ^
  需要: Map<String,Object>
  找到:    Object
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
19 个警告

> Task :elasticsearch-hadoop-mr:generateGitHash FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':elasticsearch-hadoop-mr:generateGitHash' (type 'DefaultTask').
> No value has been specified for property '$1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s
2 actionable tasks: 2 executed

**Comment by jbaiera** [comment]
Are you executing the repository build from underneath a git worktree or submodule?

**Comment by ZBHdd** [comment]
I download from  “https://github.com/elastic/elasticsearch-hadoop/archive/7.8.zip”

**Comment by jbaiera** [comment]
Hmm, I suppose that if you're building and do not have the git directory information it could fail. I would suggest cloning the repository instead of pulling down the project zip until this can be addressed.

**Comment by jakelandis** [comment]
closing since the approve way to build from source is to clone the repository.
