### ISSUE TITLE
how to set cluster.name property in SSL connection

### ISSUE THREAD

**Issue by parvanehabi** [elastic/elasticsearch-hadoop#1494]
### Issue description

i need to set cluster.name property but i don't know how to do it  in elasticsearch-hadoop.

**Comment by jbaiera** [comment]
Thanks very much for your interest.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
