### ISSUE TITLE
array type default is array and has one null value

### ISSUE THREAD

**Issue by ZhendongBai** [elastic/elasticsearch-hadoop#1527]
### What kind an issue is this?

- when insert null value, array type default is array and has one null value, and how to handle the unset value

### Issue description

- **why the unset value(i.e. the first row of result) status_code has the array(null) as its default value ?**
- **how to handle the default unset value ?**

### Steps to reproduce

Code:

```
PUT my-index-000001/_doc/1
{
  "status_code": null,
  "ts": 12345678910,
  "name": "john"
}

PUT my-index-000001/_doc/2
{
  "status_code": ['123'],
  "ts": null,
  "name": "johnny"
}

PUT my-index-000001/_doc/3
{
  "status_code": [],
  "ts": 12345678910,
  "name": null
}
```
the result show as following:
![image](https://user-images.githubusercontent.com/18043146/93551135-b92be780-f99f-11ea-9322-f6cbb1813d84.png)

query the collection result with spark sql:
```
queryStatement =
      """SELECT status_code,
        | size(status_code),
        | case when size(status_code) = 1 then status_code[0] else null end as first_status_code,
        | ts,
        | name
        | FROM artists""".stripMargin
    df = spark.sql(queryStatement)
    df.show(200, truncate = false)
``` 
the result shows as below:
```
+-----------+-----------------+-----------------+-----------+------+
|status_code|size(status_code)|first_status_code|ts         |name  |
+-----------+-----------------+-----------------+-----------+------+
|[]         |1                |null             |12345678910|john  |
|[123]      |1                |123              |null       |johnny|
|[]         |0                |null             |12345678910|null  |
+-----------+-----------------+-----------------+-----------+------+
```
### Version Info

OS:         :  mac pro
JVM         :  1.8
Hadoop/Spark:  2.4.3
ES-Hadoop   :  7.9.1
ES          :  7.5.2(docker container single-node)

**Comment by jbaiera** [comment]
The existence of a null field value can be interpreted in both ways equally validly, but the absence of the field is evidence enough to indicate that the array itself should be null. Classifying as a bug.

**Comment by johnnyprimary** [comment]
@jbaiera  actually, I have signed the CLA, but the CLA service tells me I am not sign the CLA....

**Comment by masseyke** [comment]
I get different results following your steps. @ZhendongBai can you tell me what I'm doing differently? I indexed 3 documents into the my-index-000001 table (which did not previously exist) as you show. Then I did the following in spark shell:
```
import org.elasticsearch.spark.sql._
import org.apache.spark.sql._
val sqlContext = new SQLContext(sc)
sqlContext.sql("create temporary table artists USING org.elasticsearch.spark.sql OPTIONS (resource 'artists', 'es.read.field.as.array.include' 'status_code')")
val queryStatement =
      """SELECT status_code,
        | size(status_code),
        | case when size(status_code) = 1 then status_code[0] else null end as first_status_code,
        | ts,
        | name
        | FROM artists""".stripMargin
val df = sqlContext.sql(queryStatement)
df.show(200, truncate = false)
```
But it outputs:
```
+-----------+-----------------+-----------------+-----------+------+            
|status_code|size(status_code)|first_status_code|ts         |name  |
+-----------+-----------------+-----------------+-----------+------+
|[null]     |1                |null             |12345678910|john  |
|[123]      |1                |123              |null       |johnny|
|[]         |0                |null             |12345678910|null  |
+-----------+-----------------+-----------------+-----------+------+
```
Which is more what I would expect. This was with elasticsearch-spark-30_2.12-7.15.2.jar. I'll try 7.9.1 to see if I can reproduce what you saw.

**Comment by masseyke** [comment]
OK I was able to reproduce this using the exact steps I posted above, except with spark 2.4.4 and elasticsearch-spark-20_2.11-7.15.2.jar. Trying to track down where this got fixed.

**Comment by masseyke** [comment]
Interestingly on spark 2 while show gives an empty array:
```
scala> spark.read.format("org.elasticsearch.spark.sql").option("es.read.field.as.array.include","status_code").load("my-index-000001").select("name", "status_code").where("name = 'john'").show
+----+-----------+
|name|status_code|
+----+-----------+
|john|         []|
+----+-----------+
```
The null is actually there if you get the list:
```
scala> spark.read.format("org.elasticsearch.spark.sql").option("es.read.field.as.array.include","status_code").load("my-index-000001").select("name", "status_code").where("name = 'john'").first.getList(1)
res38: java.util.List[Nothing] = [null]

scala> spark.read.format("org.elasticsearch.spark.sql").option("es.read.field.as.array.include","status_code").load("my-index-000001").select("name", "status_code").where("name = 'john'").first.getList(1).isEmpty
res39: Boolean = false

scala> spark.read.format("org.elasticsearch.spark.sql").option("es.read.field.as.array.include","status_code").load("my-index-000001").select("name", "status_code").where("name = 'john'").first.getList(1).get(0) == null
res41: Boolean = true
```
Now that I think about it though, it really seems like it's wrong in both spark 2 ([]) and spark 3 ([null]) because it ought to just be null. I think that's what @jbaiera was saying as well.

**Comment by masseyke** [comment]
Here is what I get in both spark 2 and spark 3 with the code in the PR:
scala> val df = sqlContext.sql(queryStatement)
df: org.apache.spark.sql.DataFrame = [status_code: array<string>, size(status_code): int ... 3 more fields]
```
scala> df.show(200, truncate = false)
+-----------+-----------------+-----------------+-----------+------+
|status_code|size(status_code)|first_status_code|ts         |name  |
+-----------+-----------------+-----------------+-----------+------+
|null       |-1               |null             |12345678910|john  |
|[123]      |1                |123              |null       |johnny|
|[]         |0                |null             |12345678910|null  |
+-----------+-----------------+-----------------+-----------+------+
```
@jbaiera and @ZhendongBai I'd appreciate your thoughts about whether this is the behavior you'd expect.
