### ISSUE TITLE
Upgrade to Gradle 6.7

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch-hadoop#1550]
https://github.com/elastic/elasticsearch-hadoop/commit/a56d9a771db4ffbc73c419cb90d598e8683c94f4 upgraded to Gradle 6.7 (https://github.com/elastic/elasticsearch-hadoop/pull/1544), but caused the following error for the given command

```
./gradlew :elasticsearch-spark-20:compileScala
```
to fail with the following error:

```
> Task :elasticsearch-spark-20:compileScala
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[Error] /home/jakelandis/workspace/elasticsearch-hadoop/spark/sql-20/src/main/scala/org/elasticsearch/spark/deploy/yarn/security/EsServiceCredentialProvider.scala:103: Class com.google.protobuf.InvalidProtocolBufferException not found - continuing with a stub.
one error found

> Task :elasticsearch-spark-20:compileScala FAILED

FAILURE: Build failed with an exception.
```
What's weird is that there is not a reference to that class on that line.  I wonder if this is a bug in Gradle ?

The commit was reverted on https://github.com/elastic/elasticsearch-hadoop/commit/f491a429f22d56f77a036bd037346b9dce258a8b

This issue is to remember to figure out what caused the issue and re-upgrade to 6.7

**Comment by breskeby** [comment]
This issue that was fixed in Gradle 6.7 looks suspicious and likely causes this problem: https://github.com/gradle/gradle/issues/14168 I'll dig a bit deeper but likely we're missing a dependency here

**Comment by breskeby** [comment]
I looked into this issue. I think what's going on here is that protobuf is required at compile time for some reason, transitively required by spark: https://gradle-enterprise.elastic.co/s/7pnv55fidrsim/dependencies?dependencies=protobuf&expandAll&focusedConfiguration=WzQsMCxbMCwwXV0&toggled=W1swLDBdLFswLDBdXQ Before Gradle 6.7 the protobuf dependency leaked into the compile class path by zinc covered this issue. 

IMO the best fix would be to add 

```
    compileOnly("com.google.protobuf:protobuf-java:2.5.0")
```
to the `sql-20` project. 

@jakelandis wdyt?

**Comment by jakelandis** [comment]
It would seem so...nice find!

A quick test, revert the revert and add [1] seems to fix the issue. However, I haven't looked too deeply. I can submit a PR later today unless you beat me to it. 
[1]
```
elasticsearch-hadoop[master] $ git diff
diff --git a/spark/sql-20/build.gradle b/spark/sql-20/build.gradle
index 1776b004..adf8a964 100644
--- a/spark/sql-20/build.gradle
+++ b/spark/sql-20/build.gradle
@@ -146,6 +146,7 @@ dependencies {
     compileOnly("com.fasterxml.jackson.core:jackson-annotations:2.6.7")
     compileOnly("org.json4s:json4s-jackson_${project.ext.scalaMajorVersion}:3.2.11")
     compileOnly("org.apache.spark:spark-tags_${project.ext.scalaMajorVersion}:$sparkVersion")
+    compileOnly("com.google.protobuf:protobuf-java:2.5.0")
 
     if ('2.10' == scalaMajorVersion) {
         implementation("org.apache.spark:spark-unsafe_${project.ext.scalaMajorVersion}:$sparkVersion")

```

**Comment by jakelandis** [comment]
The main project was downgraded to 6.6.1 via https://github.com/elastic/elasticsearch/pull/64300 (for unrelated reasons). We should wait to upgrade this project to 6.7 until the main project is upgraded again.

**Comment by masseyke** [comment]
Closing this as out of date since we're now on gradle 7.3: #1809
