### ISSUE TITLE
Does elasticsearch-hadoop support HIVE 3.1.0?

### ISSUE THREAD

**Issue by rickw1028** [elastic/elasticsearch-hadoop#1567]
Hi Guys,  Does anyone did the test that elasticsearch-hadoop work for Hive 3.1.0?
We using HDP 3.1.0 which include Hadoop 3.1.1 and Hive 3.1.0

**Comment by devendrasr** [comment]
+1

**Comment by jbaiera** [comment]
this is already being tracked in https://github.com/elastic/elasticsearch-hadoop/issues/744 - unfortunately there is no timeline on when this will be available, though we are evaluating efforts to upgrade some of the older integration versions like Hive.
