### ISSUE TITLE
no support for elasticsearch dencevector

### ISSUE THREAD

**Issue by mide123** [elastic/elasticsearch-hadoop#1590]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [x] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by mide123** [comment]
hi, i wan't read dencevector from elasticsearch by spark, but i can't do it now, thank you!

**Comment by jbaiera** [comment]
Please help us keep the issue tracker in good order by filling out the issue template when opening feature requests and bug reports, as well as a detailed explanation of the feature requested or the bug encountered.
