### ISSUE TITLE
Reading from specific index under alias

### ISSUE THREAD

**Issue by AnaMariaIlie** [elastic/elasticsearch-hadoop#1598]
Hello! I have an alias containing different indices and I want to read all documents from a specific index under that alias.

Ex:
```
curl -X GET http://es_host:port/_alias/my_alias?pretty
{
  "my-first-index" : {
    "aliases" : {
      "my_alias" : { }
    }
  },
  "my-second-index" : {
    "aliases" : {
      "my_alias" : { }
    }
  }
```

What I do now is a filter, like this:
```
 http://es_host:port/my_alias/_search?q=_index:my-first-index

```
I think there should be a way to ready directly from that index(under the alias), without filtering. Thank you!

**Comment by jbaiera** [comment]
Thanks very much for your interest in Elasticsearch.

You could directly target the index from the alias as the read target, would that work? 

```
http://es_host:port/my-first-index/_search
```

This also appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
