### ISSUE TITLE
Skip non-valid data in mr

### ISSUE THREAD

**Issue by jarda-manana** [elastic/elasticsearch-hadoop#160]
How can a mr job skip non-valid json document in input data?
An exception is thrown:

```
Java.lang.IllegalStateException: Found unrecoverable error [Bad Request(400) - MapperParsingException[failed to parse [failField]]; nested: JsonParseException[Numeric value (18446744073594037153) out of range of long (-9223372036854775808 - 9223372036854775807)
```

It is catched in mapper and logged.

I'm using:

```
es.input.json=true
es.batch.write.retry.policy=none
```

But this exception is appearing over an over again and map task gets really slow (duration increases from minutes to hours).

Thanks for any advise..

**Comment by jbaiera** [comment]
Visit from the Backlog Fairy: With the introduction of bulk write failure handlers in 6.2.0 we are very much looking to target adding serialization failure handlers for both reading data and writing data.

**Comment by jbaiera** [comment]
Closing this in favor of #1128
