### ISSUE TITLE
Missing elasticsearch-spark-20_2.12-7.12.0.jar files

### ISSUE THREAD

**Issue by dlubomski** [elastic/elasticsearch-hadoop#1649]
Under https://www.elastic.co/guide/en/elasticsearch/hadoop/7.12/eshadoop-7.12.0.html

we see that "Add support for Spark integration on Scala 2.12" but after downloading we see only elasticsearch-spark-20_2.11-7.12.0.jar file so as I understand it support only Scala 2.11.

elasticsearch-spark-20_2.12-7.12.0.jar is missing.

**Comment by jbaiera** [comment]
We only ship the 2.11 version in the project zip archive, but 2.12 is available on maven as a separate artifact. Please see [minimalistic libraries](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/install.html#_minimalistic_binaries) in the documentation.
