### ISSUE TITLE
Spark ES documentation options

### ISSUE THREAD

**Issue by priamai** [elastic/elasticsearch-hadoop#1703]
Hi there,
I am using:

- elasticsearch-spark-30_2.12:7.13.0
- ELK 7.13.0
- PySpark: spark_version=3.1.2 hadoop_version=3.2

I wasn't able to find the following from the documentation:

- for scroll queries how can I set the parameters such as scroll size and timeout?
- for batch queries how can I set the batch size?
- is there a way to display the generated ES underlying query?
- does the library take full advantage of multiple threads (I have a standalone cluster mode with lots of threads) for performing multiple queries?

Best Regards.

**Comment by jbaiera** [comment]
Thanks very much for your interest in ES-Hadoop.

This appears to be a user question, and we'd like to generally direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

All of our configurations and explanations for them are available on the docs site. Some sections that might be helpful for the first few questions: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_network, https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#configuration-serialization.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer any other of your questions. As such, I hope you don't mind that I close this.

**Comment by priamai** [comment]
Perfect thanks!
