### ISSUE TITLE
Whether predicate push down is supported

### ISSUE THREAD

**Issue by shenshengli** [elastic/elasticsearch-hadoop#1714]
Hive on ElasticSearch does not seem to be able to use predicate pushdown, only the 'es.query' configuration provides simple filtering and does not support indexing on '_source=fasle'.

**Comment by jbaiera** [comment]
This is a long listed todo item on the project (#4). There was a PR open for this at one point but I do not think the author has returned to it at all. Closing as duplicate for now.
