### ISSUE TITLE
unable to query elastic search repository from hive

### ISSUE THREAD

**Issue by ashishrathi1** [elastic/elasticsearch-hadoop#172]
I'm using ES and hadoop integration jar and using hadoop version 2.2.0 . Querying the data from ES repository using Hive table. I consistently getting following error 

Error: java.io.IOException: Cannot create an instance of InputSplit class = org.elasticsearch.hadoop.hive.EsHiveInputFormat$ESHiveSplit:Class org.elasticsearch.hadoop.hive.EsHiveInputFormat$ESHiveSplit not found at org.apache.hadoop.hive.ql.io.HiveInputFormat$HiveInputSplit.readFields(HiveInputFormat.java:147) at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:71) at org.apache.hadoop.io.serializer.WritableSerialization$WritableDeserializer.deserialize(WritableSerialization.java:42) at org.apache.hadoop.mapred.MapTask.getSplitDetails(MapTask.java:370) at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:402) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:415) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157) Caused by: java.lang.ClassNotFoundException: Class org.elasticsearch.hadoop.hive.EsHiveInputFormat$ESHiveSplit not found at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:1626) at org.apache.hadoop.hive.ql.io.HiveInputFormat$HiveInputSplit.readFields(HiveInputFormat.java:144) ... 10 more

I copied all the elasticsearch-hadoop jars(elasticsearch-hadoop-1.3.0.M2.jar,elasticsearch-hadoop-1.3.0.M2-yarn.jar in hadoop and aux_lib folder but does not resolve the problem. Any clue ?

**Comment by gubinjie** [comment]
@ashishrathi1 
![企业微信截图_16170023267350](https://user-images.githubusercontent.com/37869445/112800320-110b7f80-90a2-11eb-835a-d691651a6b5f.png)
How to solve it?
