### ISSUE TITLE
read search_as_you_type columns

### ISSUE THREAD

**Issue by personalety** [elastic/elasticsearch-hadoop#1739]
Is there a way to read the **search_as_type** of columns by spark?

**Comment by jbaiera** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
