### ISSUE TITLE
Provide Scala 2.13 builds

### ISSUE THREAD

**Issue by bpiper** [elastic/elasticsearch-hadoop#1815]
Now that the update to Spark 3.2 (which is cross-built for Scala 2.13) is in, it would be great to see 2.13 builds of elasticsearch-spark. I have been using a custom 7.12.0 build with Spark 3.2 and Scala 2.13.5 for a while now, which didn't require too many changes (https://github.com/Biomatters/elasticsearch-hadoop/commit/3b765befeb8abdacbfa06728a795f80e44445b9a), but it was quick and dirty and minimal in scope, so I imagine there might be more to doing it properly and with due diligence.

**Comment by masseyke** [comment]
Thanks for the interest! It's definitely on our radar -- I've also made the changes in an experimental branch but haven't had time to fully vet them either. Hopefully we'll get there soon. I'll compare my changes to yours to see if you've hit anything I didn't.

**Comment by masseyke** [comment]
@bpiper I've got a PR up for this that is very similar to your changes. Aside from some additional changes to make sure older versions keep working, I've left out one of your changes that I didn't understand (and left a comment on your code). I'd appreciate any feedback on the PR if you have time. Thanks.

**Comment by bpiper** [comment]
@masseyke do you know when 2.13 builds will be published to Maven central? I thought they might arrive with the 8.1.0 release. Thanks.

**Comment by masseyke** [comment]
@bpiper it looks like I missed a step with our release team to get the new artifact uploaded. Thanks for catching that. I'm working with them to try to see if we can manually put it in maven central.

**Comment by masseyke** [comment]
The artifact has been published and ought to show up in maven central in an hour or so.

**Comment by bpiper** [comment]
Awesome, many thanks @masseyke.
