### ISSUE TITLE
Add option to use Node or Transport Client

### ISSUE THREAD

**Issue by xstevens** [elastic/elasticsearch-hadoop#183]
It would be a really nice feature to be able to use Node or Transport clients. In our case this library isn't usable currently because we disable HTTP on our data nodes.

**Comment by AlexeyRaga** [comment]
Yes, being able to use Transport Clients would be very helpful from the performance point of view.
We are using `elasticsearch-hadoop` now and are thinking of moving away from it (try `https://github.com/SHSE/spark-es` or write something own) because HTTP client is just much slower.

**Comment by ckarmann** [comment]
Another data point, for what it worth: for us HTTP is like 30 times slower when sending to a cluster across the ocean, due to caracteristics of our network. Too bad we can't use this project then, but doing a custom OutputFormat is simple enough.

**Comment by jbaiera** [comment]
Transport and Node clients have been deprecated in the Elasticsearch project as of 5.0. We will most likely not be implementing the usage of Transport or Node clients because of this.
