### ISSUE TITLE
[CI] compilation error `:elasticsearch-spark:compileTestScala`

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch-hadoop#1835]
### Issue description

Description
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+8.0+periodic/55/console 

```
Task :elasticsearch-spark:compileTestScala FAILED
... elastic-elasticsearch-hadoop-8.0-periodic/spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueReaderTest.scala:26:90: not found: value DATE_NANOS
... elastic-elasticsearch-hadoop-8.0-periodic/spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueReaderTest.scala:31:62: not found: value DATE_NANOS
...
```

### Steps to reproduce
``` 
./gradlew :elasticsearch-spark:compileTestScala
```

**Comment by masseyke** [comment]
This one ought to be good now. I had forgotten when I cherry-picked the date_nanos fix that it had been done in two parts. We're going to get builds on pull requests soon so this will stop being a problem.
