### ISSUE TITLE
NoClassDefFoundError: org/apache/spark/Partition

### ISSUE THREAD

**Issue by imgoby** [elastic/elasticsearch-hadoop#1879]
version: 8.0.0-rc1

error:

22/01/25 16:21:37 INFO Version: Elasticsearch Hadoop v8.0.0-rc1 [b9198f5a51]
22/01/25 16:21:38 WARN RestClient: Could not verify server is Elasticsearch! ES-Hadoop will require server validation when connecting to an Elasticsearch cluster if that Elasticsearch cluster is v7.14 and up.
22/01/25 16:21:38 INFO ScalaEsRDD: Reading from [xxxxx]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/Partition$class

**Comment by masseyke** [comment]
Hi @imgoby. That class (org.apache.spark.Partition) comes from your spark installation. We would need reproducible steps to fix an issue though. Can you provide steps? Or if you need help getting set up, https://discuss.elastic.co/ is a good place to get help (create an "Elastic Stack / Elasticsearch" topic and tag it with "es-hadoop".

**Comment by masseyke** [comment]
Closing this for now. Feel free to reopen it if you can provide steps to reproduce it.
