### ISSUE TITLE
Elasticsearch spark connector: byte and short written as long from Spark to Elasticsearch

### ISSUE THREAD

**Issue by mqiu1750** [elastic/elasticsearch-hadoop#1958]
### What kind an issue is this?

- [ ] Bug report.

### Issue description
I need to write byte and short data from spark SQL dataframe to Elasticsearch. However, the short and byte data both was written as long data type in Elasticsearch.

Below two documents has a conflict opinion about writing short/byte data to elasicsearch:

On [Elasticsearch Hadoop](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#_numbers_mapped_only_as_longdouble), it mentioned elasticsearch will allocate the largest type for it since it does not know the exact number type of the field (Allocating a small type like byte and short to long). But on the other document [Elasticsearch Spark ](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-sql-type-conversion), it mentions elastic spark connector will convert short to short and byte to byte. 

Could I know short/byte data type will be written to elasticserch as long or byte/short ? If they should be written as byte/short, I believe this is a bug in elasticsearch spark connector.

### Steps to reproduce

Below is my code which read and write data from/to elasticsearch through elasticsearch spark connector.

Code:

```
     val sparkSession = SparkSession
        .builder()
        .master("local")
        .getOrCreate();

     val options = Map(
        "es.nodes.wan.only" -> "true",
        "es.nodes" -> "host", 
        "es.port" -> "9200", 
        )
      
     //Read data from elasticsearch
     var df = sparkSession
        .read
        .format("org.elasticsearch.spark.sql")
        .options(options)
        .load("sample")   
      
    //Write data to elasticsearch
    df.write
      .format("org.elasticsearch.spark.sql")
      .option("es.nodes.wan.only","true")
      .option("es.port","9200")
      .option("es.nodes", "host")
      .mode("Overwrite")
      .save("sample_tgt2")

    df.printSchema()
    df
```

Below is the sample data in elasticsearch source index
```
{
  "sample" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "blob" : {
          "type" : "binary"
        },
        "bytetype" : {
          "type" : "byte"
        },
        "datetype" : {
          "type" : "date"
        },
        "longtype" : {
          "type" : "long"
        },
        "name" : {
          "type" : "text"
        },
        "shorttype" : {
          "type" : "short"
        },
        "time_in_seconds" : {
          "type" : "float"
        }
      }
    },
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "sample",
        "creation_date" : "1651611506530",
        "number_of_replicas" : "1",
        "uuid" : "dP9SHvi6TmC9JlMSkusKOQ",
        "version" : {
          "created" : "7170099"
        }
      }
    }
  }
}
```
Below is the sample data in elasticsearch target index

```
{
  "sample_tgt2" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "blob" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "bytetype" : {
          "type" : "long"
        },
        "datetype" : {
          "type" : "long"
        },
        "longtype" : {
          "type" : "long"
        },
        "name" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "shorttype" : {
          "type" : "long"
        },
        "time_in_seconds" : {
          "type" : "float"
        }
      }
    },
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "sample_tgt2",
        "creation_date" : "1651709703750",
        "number_of_replicas" : "1",
        "uuid" : "b20RS-5DSFSrEuOzR2Ja4g",
        "version" : {
          "created" : "7170099"
        }
      }
    }
  }
}
```
Schema from target index

```
root
 |-- blob: binary (nullable = true)
 |-- bytetype: byte (nullable = true)
 |-- datetype: timestamp (nullable = true)
 |-- longtype: long (nullable = true)
 |-- name: string (nullable = true)
 |-- shorttype: short (nullable = true)
 |-- time_in_seconds: float (nullable = true)
``` 
### Version Info

OS:         :  Windows 10 Enterprise, 64-bit operating system
JVM         :  Java 8
Hadoop/Spark:  spark-sql_2.12
ES-Spark   :  elasticsearch-spark-30_2.12
ES          :  7.17.0

**Comment by jbaiera** [comment]
The connector does not create mappings on Elasticsearch before writing data. If an index/mapping does not already exist, the connector relies on Elasticsearch's automated mapping logic to assign field types for new fields. There is no way to indicate in JSON that a number value should be stored in a byte or a short, and so Elasticsearch defaults to using the largest size possible to store it for safety purposes.

If you want to set mappings on indices before they are written, you should configure Elasticsearch with an index template matching the index name being written to that provides the correct mappings for the fields being written.

**Comment by mqiu1750** [comment]
Hi @jbaiera thank you for your reply! 
 In [Elasticsearch spark connector conversion table](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-sql-type-conversion) mentioned that spark SQL short will map to elasticsearch short. Could I know if it is for the Elasticsearch with an index template situation?

**Comment by jbaiera** [comment]
If you have an existing index in Elasticsearch with a `short` field, then attaching SQL to read from it without a schema will generate a schema with the correct `short` field in it. If there is no corresponding mapping in Elasticsearch when a dataset is written from SQL, the SQL schema is not used to generate any mappings on Elasticsearch. The mappings are either generated using dynamic mapping or provided by a matching index template.

JSON does not distinguish between "short", "int", "long" - It just has numbers, which Elasticsearch treats as "long" types unless it is told beforehand to treat differently.
