### ISSUE TITLE
elasticsearch-hadoop-8.4.2.zip misses the Jar for Spark 3.X

### ISSUE THREAD

**Issue by saryeHaddadi** [elastic/elasticsearch-hadoop#2029]
### What kind an issue is this?

- [X] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description
elasticsearch-hadoop-8.4.2.zip contains only the jar for spark 2.X, jar for Spark 3.X is missing.
- elasticsearch-spark-30_2.12-8.4.2.jar is missing

### Steps to reproduce

Go to: https://www.elastic.co/fr/downloads/hadoop
Download the Zip
Extract the Zip
- it contains only jar for spark 2.X (elasticsearch-spark-**20**_*)
- as per the [documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/install.html#CO4-1), jar for Spark 3.X is named (elasticsearch-spark-**30**_*)

### Version Info

Hadoop/Spark:  3.X
ES-Hadoop   :  8.4.2

**Comment by masseyke** [comment]
That's by design. We only ship one "default" elasticsearch-spark jar in the elasticsearch-hadoop zip. In most cases users need to pull the es-spark version that is appropriate for their spark and scala versions. We really ought to remove the default spark jar because it only causes confusion.
