### ISSUE TITLE
How to custom rest client?

### ISSUE THREAD

**Issue by cutiechi** [elastic/elasticsearch-hadoop#2052]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [x] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

How to custom rest client

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by masseyke** [comment]
I'm not sure if there's a question here, but https://discuss.elastic.co/ is probably the better place for this.

**Comment by cutiechi** [comment]
> I'm not sure if there's a question here, but https://discuss.elastic.co/ is probably the better place for this.

I didn't see how to customize the rest client in any document, I want to use our own authentication method

**Comment by jbaiera** [comment]
The rest client is not configurable on a per document basis. Client connections are expensive and creating a bespoke rest client per document is not something we will be supporting. For other configurations pertaining to the client, you can find the settings in the [documentation][1]. For examples of supported authentication, we have a [basic guide][2] and [kerberos guide][3] available as well.

[1]: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html
[2]: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/security.html
[3]: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/kerberos.html
