### ISSUE TITLE
Elastic search hadoop connector dropping document silently while calling rdd.SaveJsonToES call

### ISSUE THREAD

**Issue by bhuvesh321** [elastic/elasticsearch-hadoop#2061]
Hi, we are using Elasticsearch Hadoop library to index the documents from Spark job. We are facing one weird issue where the documents are not getting indexed without throwing any error or exception.
Method used: rdd.SaveJSonToES.
We have set the batch size as 5000 and let's say if we try to index 15K documents then around 1500-2000 documents doesn't get indexed. Checked the logs in Spark executor and driver and didn't find any exception. We are using ES version 6.2.3. installed in Linux VMs'. I already logged the similar issue in Elastic search forum. Can you please help to get to the root cause of this problem so that we can fix this permanently.

**Comment by bhuvesh321** [comment]
> Hi, we are using Elasticsearch Hadoop library to index the documents from Spark job. We are facing one weird issue where the documents are not getting indexed without throwing any error or exception. Method used: rdd.SaveJSonToES. We have set the batch size as 5000 and let's say if we try to index 15K documents then around 1500-2000 documents doesn't get indexed. Checked the logs in Spark executor and driver and didn't find any exception. We are using ES version 6.2.3. installed in Linux VMs'. I already logged the similar issue in Elastic search forum. Can you please help to get to the root cause of this problem so that we can fix this permanently.

Configuration used:

ES   Version | 6.2.3
Data   node count | 4
Data   node type | Standard_D13_v2   (8 CPU, 56 GB RAM)
Data   Disks per node | 2   (Managed disks)
Data   Disk Size | 2TB
Cluster   Size | 16TB

      "es.index.auto.create" -> "yes",
      "es.nodes" -> ClusterIP,
      "es.port" -> ClusterPort,
      "es.mapping.id" -> MappingId,
      "es.write.operation" -> "upsert",
      "es.batch.size.entries" -> 5000,
      "es.nodes.wan.only" -> "false",
      "es.batch.write.retry.count"-> "5",
      "es.batch.write.retry.wait"-> "20",
      "es.batch.write.retry.policy"-> "simple",
      "es.resource.write" -> s"{${Constants.IndexNameField}}/_doc",
      "es.write.rest.error.handlers" -> "logError",
      "es.write.rest.error.handler.logError" -> "classname",
      "es.write.rest.error.handler.logError.clusterIp" -> ClusterIP,
      "es.write.rest.error.handler.logError.indexName" -> index name,
      "es.write.rest.error.handler.logError.environment" -> stamp,
      "es.write.rest.error.handler.logError.stamp" -> stamp

**Comment by masseyke** [comment]
6.2.3 is well beyond end of life. https://discuss.elastic.co/t/elastic-search-savejsontoes-hadoop-libra-dropping-documents-without-throwing-error-or-warning/323384 is probably a better place for this until we have a confirmed bug in a supported version.
