### ISSUE TITLE
WritableBytesConverter always falls back to JdkBytesConverter

### ISSUE THREAD

**Issue by jasperiq** [elastic/elasticsearch-hadoop#2072]
### What kind an issue is this?

- [X] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

WritableBytesConverter always falls back to JdkBytesConverter. I would expect a return after invoking the safeWritableConverter, or a else statement. Previously, this was working correctly, but below commit introduced the behavior of always using the fallback.

https://github.com/elastic/elasticsearch-hadoop/commit/08b2986f5f2759aa9d01a4701cb53b7b6d87a85b

### Steps to reproduce

Code:

Below code is where the unexpected behavior is:
```
@Override
public void convert(Object from, BytesArray to) {

    if (safeWritableConverter != null)
        safeWritableConverter.invoke(from, to);

    super.convert(from, to);
}
```

Strack trace:

N/A

### Version Info

ES-Hadoop   :  7.17.9

**Comment by masseyke** [comment]
Thanks for the report, and that looks to me like a bug in the commit you linked, too.

**Comment by masseyke** [comment]
@jasperiq what are you doing to hit this (I want to test it as much like your use as possible)? Thanks.

**Comment by jasperiq** [comment]
I think this sums it up:

```
MultipleOutputs<NullWritable, Text> outputs = new Multiple ;
String namedOutput = "some named output";
String documentJson = "any kind of json";
outputs.write(namedOutput, NullWritable.get(), new Text(documentJson));
```

It goes wrong when wrapping the documentJson in a Text writable. Also when I wrap byte[] in Text it goes wrong. 

This actual issue I have is that because of it does the toString() in the JdkBytesConverter it becomes inefficient. I start with String, in Text this is translated into a new byte[], JdkBytesConverter creates another String, and because of this String, BytesArray needs to make sure it's in UTF-8 and creates a byte[] again. This all makes me run into heap when writing larger documents.  

I worked around this by directly write byte[] to the MultipleOutputs for now. However, looking at the code, I think the intention was to support Text writables in an efficient way as well. 

I hope this explains my issue enough. Let me know if you have more questions.

**Comment by masseyke** [comment]
OK thanks. I think my change in #2075 will fix that.

**Comment by jasperiq** [comment]
Indeed!
