### ISSUE TITLE
Invalid jackson fallback on MapR distro

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#215]
Pre 1.7 jackson versions are not properly detected resulting in an invalid code path being executed. This typically occurs on MapR distros.

**Comment by sibbsnb** [comment]
Is this issue taken care in latest release?

**Comment by costin** [comment]
@sibbsnb This issue has been closed since Jul 2014. There are also two labels associated with it on the right. This means it has been addressed starting with these versions. If experience problems, considering raising a different issue.
