### ISSUE TITLE
hello, is async http support?

### ISSUE THREAD

**Issue by KilJaeeun** [elastic/elasticsearch-hadoop#2156]
hello. I am a first-time user of this library. My question may be immature, but I created an issue because I couldn't find the relevant code. When sending a request from hdfs to es, is the code that sends it asynchronously implemented?

https://github.com/elastic/elasticsearch-hadoop/issues/602

**Comment by masseyke** [comment]
Hi. @KilJaeeun. The call is not asynchronous. The blocking call is made here: https://github.com/elastic/elasticsearch-hadoop/blob/main/mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java#L717. That is called from NetworkClient::execute, which is called from RestClient::execute.
If you would like to discuss more about this, https://discuss.elastic.co/ is a better place for these kinds of conversations.
