### ISSUE TITLE
Upgrade to Spark 3.4.x

### ISSUE THREAD

**Issue by codefromthecrypt** [elastic/elasticsearch-hadoop#2187]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [x] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Please update the Spark version to 3.4.x

### Steps to reproduce

N/A

### Version Info

N/A

### Feature description

The current codebase is on Spark 3.3.x and causes conflicts moving to Scala 2.13 where other projects are at Spark 3.4.x. Please update the dependency or keep this open with a note about timeframe or external event which would result in the same.

**Comment by codefromthecrypt** [comment]
Spark 3.5 is out, so updating to this also works

**Comment by masseyke** [comment]
#2215 updates to spark 3.4.2, so I'm closing this one. Supporting spark 3.5 is going to be a good bit more involved because of some breaking API changes, so I'll leave #2210 for that.

**Comment by codefromthecrypt** [comment]
I tested this, and it works fine. Thanks @masseyke!
