### ISSUE TITLE
What's the status on Elasticsearch 8.13 support?

### ISSUE THREAD

**Issue by landlord-matt** [elastic/elasticsearch-hadoop#2228]
Hi!

According the [official compatibility matrix](https://www.elastic.co/support/matrix#matrix_compatibility), there is support for 8.12.x, but no support (blank) for Elasticsearch 8.13.x. At the same time both [Releases](https://github.com/elastic/elasticsearch-hadoop/releases) and [Maven](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-spark-30) states that there is a 8.13.4 version available. What is meant by it being blank in the official compatibility matrix?

Best regards,
Matt

**Comment by masseyke** [comment]
I think that's just a mistake in the compatibility matrix.

**Comment by landlord-matt** [comment]
Thanks for confirming! On closer inspection the matrix was update on the same date ("Last updated: 2024-03-26") as the [8.13 support was released](https://github.com/elastic/elasticsearch-hadoop/releases/tag/v8.13.0). Maybe it just didn't make the cut off and they forgot about Hadoop after that.

**Comment by landlord-matt** [comment]
I verified myself now and it works!
