### ISSUE TITLE
External HIVE table - all values NULL!

### ISSUE THREAD

**Issue by Kappers** [elastic/elasticsearch-hadoop#229]
Using elasticsearch-hadoop-2.0.0, I can create external tables pointing to a specific ES index, however the data appearing on query is nothing but NULL. I am simply indicated 'es.resource' in TBLPROPERTIES, without an 'es.query', and it is correctly retrieving the right number of rows and not giving any parse errors etc.... The data is correctly stored in ES, too.

I'm not experienced with Hive/Hadoop/ES, so was wondering where you thought the issue may lie?

Thank you very much!

I followed this tutorial using more recent releases. 
http://ryrobes.com/systems/connecting-tableau-to-elasticsearch-read-how-to-query-elasticsearch-with-hive-sql-and-hadoop/

**Comment by jasonliaoxiaoge** [comment]
how to resolve this problem? i met the same issue.

**Comment by amine-92** [comment]
if some one meet the same problem,
For me, Adding the 'es.mapping.names'  propertie in TBLPROPERTIES of the external hive table had solved the issue,
in other words, i enforce the mapping beetwen External table's fields and index's fields.
Exemple : 
'es.mapping.names' = 'id_doc:_metadata._id,MCM_date_reference:MCM_date_reference,MCM_nb:MCM_nb,MCM_nom_indicateur:MCM_nom_indicateur,MCM_type:MCM_type'

**Comment by smiecj** [comment]
Maybe case sensitive cause this problem, can check field name between hive and es
