### ISSUE TITLE
Allow the source document to be returned as is

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#232]
That is, provide the equivalent of `es.input.json` - don't filter or map out the documents but rather return the source as is.

**Comment by b0c1** [comment]
Hi dude, what is the status of this functionality? I waiting for this a lot!
Thanks

**Comment by costin** [comment]
It's been in master from quite some time now: http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/configuration.html#_operation

**Comment by costin** [comment]
See also #251

**Comment by costin** [comment]
Closing the issue.
