### ISSUE TITLE
Feature - Setting ids in spark w/o using a Map

### ISSUE THREAD

**Issue by chrislovecnm** [elastic/elasticsearch-hadoop#255]
Hi all

I believe that the only way that one can set their own id is to use a Map Object.  This is a request for a feature to send in the id in the rdd with spark.  In Scala an idea would be to have:

<pre><code>
val data: RDD[((String,Object))] = ...
data.saveToEs("foo/bar")
</code>
</pre> 

In essence have the capability to define my own id and use either an object or json. If this capability does exist, please improve the documentation so that I have examples of it.

**Comment by costin** [comment]
@chrislovecnm @bobrik I've added support for this in master. The feature is also [documented](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/spark.html#spark-write-meta). In short, there are now a handful of methods named `saveToEsWithMeta` that work on _pair_ `RDD`s, where the key is the metadata, the value the actual document:

```
val airportsRDD = sc.makeRDD(Seq((1, otp), (2, muc), (3, sfo)))  
pairRDD.saveToEsWithMeta(airportsRDD, "airports/2015")
```

Of course, both the Scala and the Java API are covered.

Feedback is welcome!

**Comment by bobrik** [comment]
This is awesome, I'm going to try this next week :+1:

**Comment by chrislovecnm** [comment]
:+1: @costin - like your comment 'is also documented'

**Comment by costin** [comment]
Closing the issue. Beta4 is about to be released.
