### ISSUE TITLE
Incorrect metrics reported

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#268]
It seems in case of rejections, the accepted documents counter is missing some documents:

```
Documents Accepted 10028225
Documents Received 0
Documents Retried 27847
Documents Sent 10056354
```

Sent - Retried > Accepted...

**Comment by jbaiera** [comment]
While incorrect metrics are a big deal, this is an old issue and enough has changed in how the metrics are reported at job completion.
