### ISSUE TITLE
Multiple indexes setting for 'es.resource'

### ISSUE THREAD

**Issue by mungeol** [elastic/elasticsearch-hadoop#289]
'es.resource' = 'apache-2014.09./apache-access' or
'es.resource' = 'apache-2014.09.29,apache-2014.09.30/apache-access' 
are not working well for 'select count(\*) from test' which is HiveQL.
The count result is not right.
'es.resource' configuration should support multiple indexes setting.
Or, at least give an error message.

**Comment by costin** [comment]
Folks, can you try the latest Beta (4) and see whether it addressed your issue? There have been several updates on this front.

Thanks,

**Comment by mungeol** [comment]
It is working now.
Thanks,

**Comment by costin** [comment]
Closing the issue...
