### ISSUE TITLE
EsBolt for reading

### ISSUE THREAD

**Issue by itaifrenkel** [elastic/elasticsearch-hadoop#296]
Reading from ElasticSearch is not for spouts only. One could use ES bolt to enrich input tuple with data stored in ES. For example given an id emit the document that matches that id. In its most generic form the input tuple would be a valid ES json query, and the output would be the ES json result.

**Comment by itaifrenkel** [comment]
See also the new proposed JdbcLookupBolt https://github.com/apache/storm/pull/374/files

**Comment by jbaiera** [comment]
With the addition of the high and low level java rest clients, I am not seeing the benefit to building out a potentially complicated enrichment bolt for Storm/other integrations. These sorts of solutions are never quite generic enough, and often are used by a limited set of users. I am closing this for now, but would be fine with reopening it if there is enough community support. +1's on initial issue post please.
