### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/spark/package$

### ISSUE THREAD

**Issue by lairdnote** [elastic/elasticsearch-hadoop#297]
use lib  "org.elasticsearch" % "elasticsearch-hadoop" % "2.1.0.BUILD-SNAPSHOT" % "provided",

or 
"org.elasticsearch" % "elasticsearch-hadoop" % "2.1.0.Beta3" % "provided",

```
  val lines = KafkaUtils.createStream(ssc, zkQuorum, group, topicpMap).map(_._2).cache()
  val esregex = s"""(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}) (\\S+) (\\S+) \\[(.*)\\] "(.*?)" (\\d{3}) (\\S+) "(.*?)" "(.*?)" (.*?) (\\d+?)""".r


  val esRdd = lines.flatMap(_.split("\\n"))
              .map{
                case esregex(ip, client, user, dataTime, request, status, bytes, referer, agent, hit , origintime) => Map("ip" -> ip,"client"->client, "user" -> user, "dateTime" -> dataTime, "request" -> request, "status" -> status, "bytes" -> bytes, "referer"->referer, "agent" -> agent, "hit"-> hit, "origintime"-> origintime)
                case line => Map("message"-> line)
              }
```

esRdd.saveToEs("spark/docs")

```
or
```

sc.makeRDD(Seq(esRdd)).saveToEs("spark/docs")

```
or 

```

EsSpark.saveToEs(esRdd, "spark/docs")

```
all has error ..
```

***Eerror:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/spark/package$
    at spark.c4hcdn.KafkaNetWork$.main(KafkaNetWork.scala:54)
    at spark.c4hcdn.KafkaNetWork.main(KafkaNetWork.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:303)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:55)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.spark.package$
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 9 more
```

**Comment by charlesa101** [comment]
Was this issue really resolved ?

**Comment by costin** [comment]
@charlesa101 It wasn't an issue to begin with - the reporter opened and close it right away suggesting it was a configuration issue. The CNFE typically occurs when the classpath is not set properly - in this case, if the es-hadoop/spark jar is not in the classpath.
If you encounter this/any issue, please open a new ticket with information about your [environment](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help).

**Comment by charlesa101** [comment]
You right @costin, i was trying to run a spark submit job

I specified the --jar path param after the --class and it was throwing exception due to that, works for me now! Thank you

[wrong]
~/spark-1.3.0-bin-hadoop2.4/bin/spark-submit  --class <className> --deploy-mode client <jar>  "hdfs://<node>" --jars $(echo /path/to/jar/*.jar | tr ' ' ',')

[correct]
~/spark-1.3.0-bin-hadoop2.4/bin/spark-submit --jars $(echo /path/to/jar/*.jar | tr ' ' ',') --class <className> --deploy-mode client <jar>  "hdfs://<node>"

**Comment by costin** [comment]
Glad to hear it got sorted out. Anything we can do to prevent this type of
failure in the future?
Thanks,

On Wed, Apr 15, 2015 at 3:49 AM, charles adetiloye <notifications@github.com

**Comment by charlesa101** [comment]
Thanks @costin, I will try to update the documentation on this

**Comment by gaurav6351** [comment]
can someone let me know how to solve above error cause ,i am facing same issue

**Comment by costin** [comment]
@gaurav6351 As I've mentioned in #665, for questions and assistance please use the dedicated forum and not the issue tracker.
Ignoring this advice and commenting on issues closed 10 months ago is unlikely to result in any assistance, quite the opposite.
Further more, speaking about the issue at hand, the [comment above](https://github.com/elastic/elasticsearch-hadoop/issues/297#issuecomment-93125975) indicates what was the problem and how it was solved.

Again, please pay a bit more attention to those trying to help you and consider following their advice. Thanks!

**Comment by prabhushrikant** [comment]
Another way is to use sbt assembly instead of sbt package to create your jar so that it includes all the required jars in the jar that is created.

**Comment by karthikeyanpa90** [comment]
I got it solved by using sbt assembly which includes all the required jars as @prabhushrikant mentioned
