### ISSUE TITLE
Ignore existing documents

### ISSUE THREAD

**Issue by SHSE** [elastic/elasticsearch-hadoop#307]
It would be great if you could tell es-hadoop to ignore existing documents when `es.write.operation` is set to `create` (e.g. `es.write.ignore.conflicts` config property).
For now it throws `EsHadoopInvalidRequest: Found unrecoverable error [Conflict(409)...`.

`update` operation requires `_source` to be enabled which is an additional and in my case unnecessary overhead.

**Comment by dmarkhas** [comment]
Can this please be picked up? There are two different pull requests addressing this issue, please accept either one of them since this is breaking Elastic functionality - Elastic allows to bulk insert documents, and the operation is successful even if some already exist - the plugin should mimic this functionality, instead of throwing an exception in a perfectly valid condition (from Elastic's perspective).

**Comment by jbaiera** [comment]
@dmarkhas you mention that the bulk insert operation is successful even if some documents already exist. While that is true, the response returns with a successful HTTP status, the body contains a breakdown of all errors that were encountered.

I think it would be incredibly unwise to add a blanket option to ignore conflicting writes when the entire purpose of the "create" operation in Elasticsearch is to avoid conflicting writes. Perhaps if your write patterns require ignoring existing documents and only inserting data that does not exist then instead we should talk about ways to extend the framework's handling of update/upsert operations to support that specifically.

**Comment by dmarkhas** [comment]
@jbaeira, your point is valid but there is a specific use case that the current implementation breaks (which I should've mentioned earlier) - external versioning.

When using external versioning in ElasticSearch, it is perfectly acceptable to ignore conflicting writes; in fact, that is exactly what external versioning does - it provides a safeguard against overwriting documents with older versions.

We use a timestamp as the document's version to make sure that if events arrive out of order the data will still be consistent. If we already have a document that has a newer version (i.e. newer timestamp) than the one we are trying to index - we expect ES to return 409 for this document, and index the rest of the bulk successfully.

If the connector aborts the entire operation if a single document in the bulk conflicts with an existing document, that breaks our ability to use external versioning completely, and makes it impossible for us to safeguard against out of order events.

**Comment by jbaiera** [comment]
Closing this in favor of #1064. Please post any conversations or feedback on the new issue.
