### ISSUE TITLE
Scan-Scroll support for Spark RDDs?

### ISSUE THREAD

**Issue by arnaudsj** [elastic/elasticsearch-hadoop#316]
I can't find anywhere references to whether or not esRDD supports properly scan-scroll when attempting to load a very large amount of results from ES to Spark: [http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-scroll.html#scroll-scan]

If it does, would somebody be kind enough to provide an example?

Thank you!

**Comment by seufagner** [comment]
Nowadays it just support scroll api using Spark ?
