### ISSUE TITLE
Hive Column Comments causing Hive Query to fail

### ISSUE THREAD

**Issue by sagarnarla** [elastic/elasticsearch-hadoop#322]
I am using Hive 0.13.0.2.1.6.0-2103 and I am creating a simple 2 columns table and inserting one record into it.
Query:
`CREATE TABLE IF NOT EXISTS testinsertion (`
`id STRING,`
`name STRING`
`) STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'`
`TBLPROPERTIES (`
`'es.resource' = 'data/shouldwork',`
`'es.nodes' = '172.16.0.14,172.16.0.15,172.16.0.16',`
`'es.hive.disable.columns.comments.fix' = '0'`
`);`

`INSERT INTO TABLE testinsertion`
`SELECT "id1","myname" from hivesampletable limit 1;`

 Unfortunately the Job.XML that gets generated for the Hive Query has this line in it, which contains an illegal XML character sequence:
`<property><name>columns.comments</name><value>&#0;</value><source>programatically</source></property>`

This is leading to an invalid XML which in turn causes the Hive query to fail.

I noticed there is what I assume a fix for this issue in the `fixHive13InvalidComments` method. This method should clear out or remove the `columns.comments` property altogether. Unfortunately this is not seem to being applied. Using `es.hive.disable.columns.comments.fix` does not seem to have any effect.

**Comment by jbaptisteGH** [comment]
Hello,
This issue is back with HDP2.2 / Hive 0.14 on Linux, either with the "es.hive.disable.columns.comments.fix" option.

**Comment by costin** [comment]
@jbaptisteGH I'm afraid there's not much we can do about it. This is a bug in Hive and es-hadoop tries to work around it - apparently it doesn't succeed all the time. I've noticed the bug occurs if the client or the server is on Windows - if that's not the case then it might be that Hive 0.14/HDP 2.2 made this worse.
I'd like to help but again, Hive configuration shouldn't use an illegal XML character in the first place; es-hadoop tries to remove it but if the configuration is read/parsed before es-hadoop kicks in, the error will appear. And that's out side es-hadoop control which is a library as oppose to Hive which is a runtime.

**Comment by sagarnarla** [comment]
I am trying to make the changes you made in the master brach to `fixHive13InvalidComments` to the 2.0 branch (https://github.com/elasticsearch/elasticsearch-hadoop/commit/56928e6ef344944c9b8651b4201e24641b2c5bfb#diff-f7e8fbf5f42badb596e0cdbbfbfdca08).

However the issue does not seem to go away. Is there any other change that I need to make?
