### ISSUE TITLE
EsSpout : option to re-run a query when we get to the end of the results

### ISSUE THREAD

**Issue by jnioche** [elastic/elasticsearch-hadoop#326]
My understanding of [https://github.com/elasticsearch/elasticsearch-hadoop/blob/master/storm/src/main/java/org/elasticsearch/storm/EsSpout.java] is that it will stop generating tuples when all the results for a query have been exhausted.
What about having an option to re-run the query? Here is an example: the ES index is used to store the status of URLs to be fetched by a storm topology. The topology discovers new URLs from the original ones and adds them to ES and in turn the spout should push them into the pipeline. This currently does not work without rerunning the query.

**Comment by jbaiera** [comment]
Since we have removed support for Storm in the latest versions of ES-Hadoop, I will go ahead and close this issue.
