### ISSUE TITLE
Move away from a single-key to improve data partitioning (on the reducer side)

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#341]
Currently the MapReduce `OuputFormat` relies on `NullWritable` for the key used to index documents - which works fine if there are no reducers. Otherwise Hadoop will shuffle all the values into the same key and send everything to only one reducer which is suboptimal. A different strategy needs to be used - an obvious option is to have one key per shard but potentially we could use the fields of the values passed in to group them based on a user defined critieria.

**Comment by costin** [comment]
@ agarwalsuchin I've been looking at this issue (based on your comment in #243) and I'd like to understand the problem better. First, you mention `EsInputFormat` as the problem but I don't think that's the case since there for each document its id and content are being returned, not `NullWritable`.
As for `OutputFormat`, the format itself does not depend on `NullWritable` rather that's what the user can pass in as a key (which we ignore anyway). To spread the load one could use a different strategy - for example pick a random number between 0 and `s` where `s = <number of shards>` or use some type of counter, etc...
I agree that the example in the documentation is not appropriate and should be changed but again, that's not related to es-hadoop itself but rather something completely under the user control.

Any comments?

**Comment by costin** [comment]
@agarwalsuchin ^^ (not sure whether the initial post sent the appropriate notification, hence this extra comment)

**Comment by agarwalsuchin** [comment]
Yes, I agree. This is completely under user control. And the issue should be related to EsOutputFormat, and not EsInputFormat. 

I thought, instead of the user taking care of the issue, this would have been handle internally by EsOutputFormat. I would like to understand this better. I could spawn N reducers. But what should be the optimal number and what kind of heuristics should I use to arrive at the optimal number. 

To throw some numbers out, I am using the batch API with a size of 1000 and indexing 12MM documents. Each document of the size ~1 KB.

**Comment by costin** [comment]
`EsOutputFormat` is at the end of the M/R chain and it doesn't have any control over the runtime. If `OutputFormat` is part of a reducer and you N reducers, than use as keys a multiple of N (either by using a counter or by simply applying a `random(n)` as mentioned before).
Not sure what you mean by `using the batch API` - that's what es-hadoop uses internally and it's not something configurable. You can simply instruct es-hadoop to use a batch size of 1k but note that is for each task - so if you want N tasks, it's best to start with a low number (say 1k/n) and keep raising it up until you see diminishing returns or the rejection rate is getting high.

Depending on your hardware and settings, you could go much higher or lower. Start with a random of N for your keys and see how it affects your job and if you're reducers are all used.

P.S. Can you also take a look at the updates at #243 and see if it improves things on your end? Thanks!

**Comment by jbaiera** [comment]
Closing this as the shuffling key (and consequently, the parallelism) is entirely up to the user or framework to control.
