### ISSUE TITLE
hive integration, autocreate index, shouldn't es.mapping.ttl enable timestamp field

### ISSUE THREAD

**Issue by wenzong** [elastic/elasticsearch-hadoop#345]
Hi,

I'm trying hive integration, and there are two key settings

```
'es.index.auto.create' = 'true',
'es.mapping.ttl' = '<10m>'
```

I don't set `es.mapping.timestamp` because I have no date field in hive table

-----------------

What I expected is that the index autocreated by hive should auto enable the timestamp field, which now seems not.

So I have to disable auto.create and create index outside the hive script(and enable timestamp and ttl by hand).

-----------------

I know that timestamp is disabled by default, but with es.mapping.ttl setting, shouldn't timestamp be auto enabled?

Thanks in advance~

**Comment by costin** [comment]
The connector does not populate indices settings. The ttl setting is per document - on this job it might apply to all your data, on another it might not.
Hence why the recommendation is to define any index setting outside the connector just as you have.
