### ISSUE TITLE
document usage in secured Hadoop environments

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#352]
This applies not only to es-hadoop but also repository hdfs as well.

**Comment by jbaiera** [comment]
With the HDFS Repository moved to the main Elasticsearch project, and it's new official support for Kerberos deployments, I don't see the need for further documentation on this topic here. As for the main ES-Hadoop library, I also don't see much room for further documentation in a secured hadoop environment, as it feels out of scope.
