### ISSUE TITLE
elasticsearch hive integration with wildcard index name not working as expected.

### ISSUE THREAD

**Issue by ybensimhon** [elastic/elasticsearch-hadoop#356]
I am using ES 1.2.1 and elasticsearch-hadoop 2.0.2 and trying to read data from multiple indexes via hive. the index names look like: metric_<customer-name> and the type is "metric". 
The external table definition I am using is:
CREATE EXTERNAL TABLE IF NOT EXISTS ext_es_metric (
    user  STRING,
    name  STRING,
    combined STRING)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'metric_*/metric', 'es.mapping.names' = 'user:userId, name:name, combined:combined', 'es.nodes' = 'ela');

Running select "count (_) from ext_es_metric" returns 24381173 records
while running in ES the following query:  POST metric__/metric/_search returns only 1913196 records.

Note: When I pass a single index the results are consistent.

Any help will be appreciated.

**Comment by costin** [comment]
Interesting. Can you try a smaller set and see whether you get some inconsistencies?
Can you look into the es-hadoop Hadoop counters and see what it reports? I'm wondering if this is not an issue due to how Hive handles item equality - can you try defining an id column as well?

**Comment by ybensimhon** [comment]
Hi Costin, thanks for your reply.
I am new to es-hadoop can you please point out where do I see the es-hadoop counters and what do you mean by id column, I am not familiar with any built-in Id generation in hive.

**Comment by costin** [comment]
On each hadoop job, es-hadoop send the information to Hadoop which can inform the user. You can read more about it [here](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/2.1.Beta/metrics.html). As for Hive, take a look at their documentation which goes into detail. It all boils down to defining a column (as string) which is mapped to the document id.

**Comment by ybensimhon** [comment]
I did a test with a subset of the indexes that hold 547826 documents and the stats show that ~7.6M docs are retrieved (see below).
I also tried defining an Id column by adding 'es.mapping.id' = 'id' into my TBLPROPERTIES and it did no change.
An interesting thing is that when I run:  
select distinct user, name from ext_es_metric...
into a fresh table I get the exact number of documents as appear in ES so I guess it might be related to how hive does identification.  

{
            "name": "org.elasticsearch.hadoop.mr.Counter",
            "displayName": "Elasticsearch Hadoop Counters",
            "counts": [
              {
                "name": "BULK_RETRIES",
                "displayName": "Bulk Retries",
                "value": 0
              },
              {
                "name": "BULK_RETRIES_TOTAL_TIME_MS",
                "displayName": "Bulk Retries Total Time(ms)",
                "value": 0
              },
              {
                "name": "BULK_TOTAL",
                "displayName": "Bulk Total",
                "value": 0
              },
              {
                "name": "BULK_TOTAL_TIME_MS",
                "displayName": "Bulk Total Time(ms)",
                "value": 0
              },
              {
                "name": "BYTES_ACCEPTED",
                "displayName": "Bytes Accepted",
                "value": 0
              },
              {
                "name": "BYTES_RECEIVED",
                "displayName": "Bytes Received",
                "value": 2177734045
              },
              {
                "name": "BYTES_RETRIED",
                "displayName": "Bytes Retried",
                "value": 0
              },
              {
                "name": "BYTES_SENT",
                "displayName": "Bytes Sent",
                "value": 42055944
              },
              {
                "name": "DOCS_ACCEPTED",
                "displayName": "Documents Accepted",
                "value": 0
              },
              {
                "name": "DOCS_RECEIVED",
                "displayName": "Documents Received",
                "value": 7669564
              },
              {
                "name": "DOCS_RETRIED",
                "displayName": "Documents Retried",
                "value": 0
              },
              {
                "name": "DOCS_SENT",
                "displayName": "Documents Sent",
                "value": 0
              },
              {
                "name": "NET_RETRIES",
                "displayName": "Network Retries",
                "value": 0
              },
              {
                "name": "NET_TOTAL_TIME_MS",
                "displayName": "Network Total Time(ms)",
                "value": 434468
              },
              {
                "name": "NODE_RETRIES",
                "displayName": "Node Retries",
                "value": 0
              },
              {
                "name": "SCROLL_TOTAL",
                "displayName": "Scroll Total",
                "value": 70560
              },
              {
                "name": "SCROLL_TOTAL_TIME_MS",
                "displayName": "Scroll Total Time(ms)",
                "value": 433874
              }
            ]
          }

**Comment by ybensimhon** [comment]
Just to make sure regarding the Id column, here is how my table definition looks like:
CREATE EXTERNAL TABLE IF NOT EXISTS ext_es_metric (
    id    STRING,
    user  STRING,
    name  STRING,
    combined STRING)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.mapping.id' = 'id', 'es.resource' = 'metric_*/metric', 'es.mapping.names' = 'user:userId, name:name, combined:combined', 'es.nodes' = 'ela4');

**Comment by ybensimhon** [comment]
Turns out the the inconsistency was a result of \t characters (and maybe some other white space characters) that magically made there way into our elasticsearch documents. I think that Hive uses \t as a delimiter and this caused the problem. After removing the problematic docs seems like things work as expected. 
Are you aware of any limitations regarding special characters when accessing ES from hive?

**Comment by costin** [comment]
@ybensimhon Can't say that I am. The `\t` sounds like a potential problem though you can work around it by configuring Hive to use a different char. The only char that can be problematic is `\n` which needs to be escaped in JSON (which we do) however can be an issue if you pass in raw JSON.
I recommend taking a look at the JSON spec and check out the special characters - typically again if you pass in raw JSON, otherwise it shouldn't be needed.

**Comment by jbaiera** [comment]
Cleaning up older issues. Closing this as the original issue seems to be resolved.
