### ISSUE TITLE
allow per-doc metadata to be specified at runtime

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#358]
Libraries with API-driven support (like Spark) could support passing the metadata as a pair beside the document. This facilitates computational environments where things like id or the timestamp are created on the fly and are not part of the doc itself.

**Comment by costin** [comment]
Related to #255

**Comment by mgreene** [comment]
@costin Will this include the `_version` metadata as well?

**Comment by costin** [comment]
Fixed in master. Closing the issue.

**Comment by mgreene** [comment]
@costin I don't know if you saw my comment from above but I was wondering how to fetch the metadata while reading documents?

**Comment by costin** [comment]
@mgreene For questions, please use the forum. The issue is about writing (not reading) documents (see the reference commits).
Thanks,
