### ISSUE TITLE
Dynamic es.resource.write fails to find nested field

### ISSUE THREAD

**Issue by aewhite** [elastic/elasticsearch-hadoop#362]
Given the dynamic configuration...

```Java   
hadoopConfiguration.set("es.resource.write", "{nested.field}/type");
```

And a document like...

```JSON
{"nested" : { "field" : "value" } }
```

The load will fail with "Cannot find match for "{nested.field}". The work around is to either insert a dummy field before the target field or, if possible, re-order the nested sub fields. 

I did manage to debug the issue down to `org.elasticsearch.hadoop.serialization.ParsingUtils#doFind`. In particular this section...

```Java
            if (token == Token.START_OBJECT) {
                token = parser.nextToken();  // <--- this eats the first FIELD_NAME token of the nested object
                if (matchingCurrentLevel == null) {
                    parser.skipChildren();
                }
                else {
                    doFind(parser, matchingCurrentLevel, active, inactive);
                }
            }
```

I expect moving the `parser.nextToken()` to inside the null check block would solve my particular problem since that is what's eating the FIELD_NAME token, but I don't know if it would break something else. 

__Edit__: To clarify, if "field" is the first property inside the nested object, then the error is triggered. If "field" is the second or later field, it works as expected.

**Comment by costin** [comment]
To confirm, you are using a JSON input, correct?

**Comment by aewhite** [comment]
Correct.

**Comment by costin** [comment]
@aewhite Looks like the problem occurs on 2.0.x branch and it has been fixed in master. Can you please try the latest dev builds published for both 2.1 and 2.0 branch and report back?

Thanks!

**Comment by costin** [comment]
@aewhite ping...

**Comment by aewhite** [comment]
This appears resolved in the latest branch.

**Comment by costin** [comment]
Great. Closing the issue.
