### ISSUE TITLE
Read operations do not take routing into account 

### ISSUE THREAD

**Issue by aewhite** [elastic/elasticsearch-hadoop#364]
When doing a read, ES-Hadoop gets shard information for the entire index/alias. The _search_shards endpoint allows for this out-of-the box so it would be nice if ES-Hadoop used it. For example, http://localhost:9200/twitter/tweet/_search_shards?routing=march

After reviewing org.elasticsearch.hadoop.rest.RestClient#targetShards it appears that the _search_shards endpoint is always called with no parameters. This results in more InputSplits than are needed to be created.

**Comment by costin** [comment]
es-hadoop is designed to performed multi/parallel read/writes. Routing is the opposite of that as it tells es to put all documents under one shard. 
While I suppose we could support this (as an optimization to save the communication to the rest of the shards that fit outside the routing) is this really what you want? It means calling only one shard (aka one node) from a Hadoop cluster; all the advantages that come with multi/parallel node-to-node reads/writes go out the window...

**Comment by aewhite** [comment]
I have a few points that I believe make this a valid request. 

First, you can certainly select from multiple routes in a single query. After only one route, something like ES-Hadoop is nice to manage the scans and locality for you. 

Second, it is convenient when some batch processing needs to happen, even on a single node. I'd personally much rather use the existing ES-Hadoop bulk scanning read/write than have to re-implement that logic.  

Also, it might be nice to perform "rolling" queries against a large index.

So, I would argue that ES-Hadoop should perform best in the multi-shard case but still do the "right" thing for routes. Either way, it's rather low priority since the workaround is simple, create an alias that does the routing on the ES side.

**Comment by jbaiera** [comment]
This is not a bad idea, but it is a very niche one that I suspect only a small percentage of users will get much use out of. Since you mention that there is a way to do this currently using aliases, I'm inclined to say that in order to keep things simpler on the ES-Hadoop side we will not pursue this feature at this time. If there's buy in for it or more evidence that it would be a more widely used feature, then we can look into it. Until then, I am closing this.
