### ISSUE TITLE
ElasticSearch on YARN Documentation is severely lacking

### ISSUE THREAD

**Issue by baank** [elastic/elasticsearch-hadoop#366]
The ElasticSearch on YARN does not show how to USE this functionality once it has been installed.

Obvious questions:
1) Can you connect to the cluster using REST/Kibana/CLI/anything ?
2) What happens to Hadoop M/R jobs which require a host/port ?

**Comment by jbaiera** [comment]
Closing this as the ES-on-YARN Beta is now deprecated and will be removed in 6.0
