### ISSUE TITLE
case sensitive columns in Pig

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#380]
The docs wrongly indicate that Elasticsearch doesn't support case sensitive fields and thus that all columns/fields are lower-cased. This is not the case and needs to be corrected.

**Comment by uris77** [comment]
Uggggh, I just ran into this issue. Hive kept returning NULL for all camelCase fields. Eventually we changed everything to lowercase. Now it works.

**Comment by costin** [comment]
Fixed in 2.1
