### ISSUE TITLE
Excluding fields when writing JSON documents from Spark to Elasticsearch doesn't work

### ISSUE THREAD

**Issue by itaiy** [elastic/elasticsearch-hadoop#381]
When working with Spark and using RDD.saveJsonToEs(), setting es.mapping.exclude doesn't actually exclude the field from the final document.
I've used the latest elasticsearch-spark_2.10 artifact (version 2.1.0.BUILD-SNAPSHOT taken from http://oss.sonatype.org/content/repositories/snapshots).
I've placed a small test application to reproduce this issue in https://gist.github.com/itaiy/1067deddae09c16077f0

**Comment by costin** [comment]
This has been fixed in master a while back - it will be part of the upcoming Beta4. Please try it out - if the problem persists, please raise a new issue.

Thanks!
