### ISSUE TITLE
How can be sure of data colocation on my Spark/ES cluster ?

### ISSUE THREAD

**Issue by NicolasYDDER** [elastic/elasticsearch-hadoop#383]
Hi folks,

I have 4 ES nodes and 4 colocated Spark nodes on my Cluster. When i execute query via ODBC driver my jobs is well distributed around my Spark cluster but each nodes request data from any other nodes... I have a huge network usage (confirmed with network tcpdump trace).

See attached screenshot
![data-colocation-es-hadoop](https://cloud.githubusercontent.com/assets/9348251/6374768/5761fcca-bd13-11e4-96fa-2bc0555f7701.png)

How can control the data-colocation request on each node ?

Environment:

Spark 1.2.0
Hive 0.13.1
elasticsearch-hadoop-2.1.0-BUILD-SNAPSHOT ( vers 2015-02-23 )
elasticsearch 1.4.4

BR

Nicolas.

**Comment by costin** [comment]
@NicolasYDDER It all depends on whether there's true data co-location or not. First the data in ES needs to be locally (aka on the same machine) as the Spark task/job; if that's not the case, then you'll see network traffic.
Second, if the ES cluster is sitting on the same nodes, check whether the index you are using is on the same nodes and if the tasks are running on the same machines; typically this shouldn't be a problem but it can occur if some nodes of ES sit outside the Spark cluster machines.

Third, co-location cannot be controlled - it's a _hint_ (hence why it's called `preferredLocation`).  In other words, es-spark/hadoop will tell Spark where the data is so Spark _might_ chose to run the task there but that's not a forced requirement.
You can see the shard location for each task if you enable [logging](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/logging.html) on the es-hadoop/spark package (make sure to include `org.elasticsearch.spark` in there).

**Comment by NicolasYDDER** [comment]
Hi @costin ,

Thanks for your clear feedback. I confirm that each Spark nodes and ES nodes are physically colocated on same machine.

With the debug logging I got more interesting information but without infer why my spark job isn't running task with only data from its node...

Basically I can see exchange like that:
    - DEBUG header: >> "GET / HTTP/1.1[\r][\n]"



Unfortunately, I can display Elasticsearch-Hadoop debug from the master but I'm not able to display the same result for each worker. So I lost the stack trace when tasks are distributed on each workers.

**Comment by costin** [comment]
Most likely each worker node needs to have the logging configuration in place and you'll probably have to aggregate the logs. However at that point, the decision on where to run the workers has already been made - the relevant part should be before that where you can see the number of tasks created and their relevant shards (ip + location). That is, you can see what data topology es-hadoop returns - whether Spark takes that into account all the way or not becames a separate issue.
I'm not aware at this point of any mechanism that can enforce the data location to be enforced and reduce the network shuffling...

**Comment by NicolasYDDER** [comment]
I add some important information and i start to understand some es-hadoop workflow (correct me if i'm wrong)
Spec : My index has 600M of documents, 10 shards on 4 nodes ( 1 replication )
I want to get only 10000 of them (spark SQL query with limit 10000). It seems that es-hadoop is not looking for data on each node but only on the first shard [0] located on node 3. ( because my shard has more than 10000 docs)

So my processing is not distributed around each node but only one nodes is working...
Is it strange or a normal behaviors of Es-hadoop/spark workflow ?

**Comment by azuisleet** [comment]
Posting my notes on this, in case others run into this same issue:

I was seeing this issue as well, all of my ES tasks were showing up as "ANY" instead of "NODE_LOCAL" when I ran ES and Spark on the same machine. It turns out that the elasticsearch-hadoop driver will prefer the ip of the node as the definitive host. You can confirm this in the code as well as the output of RDD.preferredLocations(...). 

I happen to be running on EC2, but I believe the experience is the same regardless: the spark nodes get the host name of the machine itself, so a worker might be called "worker-somedate-123-ec2-internal-pid. That second to last part of the name is what the scheduler uses for the host name. I did a band-aid over this by specifying SPARK_LOCAL_HOSTNAME=123 for my worker nodes and the tasks are correctly scheduled to the ES nodes.

**Comment by costin** [comment]
@azuisleet If I understand correctly, the issue seems to be that Spark would use the machine/node DNS name while ES and ES-Hadoop relies on the IP address and to avoid any confusion, one should create an alias between the host name and IP through `SPARK_LOCAL_HOSTNAME`, correct?

**Comment by azuisleet** [comment]
In this case, SPARK_LOCAL_HOSTNAME is simply a way to bypass Spark's host name lookup and apply the IP as the name directly on the worker. I'd have to play more with the hostname settings, but I believe it tries its best to resolve a DNS name.

**Comment by NicolasYDDER** [comment]
@azuisleet thanks for your feedback, seems to be very useful. I will investigate on this way.

**Comment by costin** [comment]
Folks, I'm closing the issue; if the problem persists (seems to be more of a discussion rather) please create a new one. 
Cheers,
