### ISSUE TITLE
Invalid position given exception

### ISSUE THREAD

**Issue by ssemichev** [elastic/elasticsearch-hadoop#386]
I tried to export the whole ES index in JSON format several times without any success.

My current configuration:
ES version: 1.4.2
Hadoop Yarn version: 2.6.0.2.2.0.0-2041 (Hortonworks distribution)
ES Hadoop version: 2.1.0.BUILD-SNAPSHOT

ES cluster includes 8 datanodes
Hadoop cluster includes 6 datanodes

The ES index has 12 shards and about 1.2 billion documents.

When I run a Mapreduce Job ten of twelve tasks are completed successfully.

Two task are failed with the same errors:

Error: java.lang.IllegalArgumentException: Invalid position given=374535 -1 at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234)

Error: java.lang.IllegalArgumentException: Invalid position given=367085 -1 at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234) 

Another attempts are failed with same position numbers 
https://gist.github.com/ssemichev/b78898b4c82566f60985

It happens with different version of ES (0.9, 1.1, 1.4) and Hadoop (Hadoop and Hadoop YARN). I get the same errors for indexes with four and twelve shards (they store the same data), but it works for index with another mapping.

Originally data were inserted in ES index using ES Hadoop from raw JSON files without any error. 

Thanks

**Comment by costin** [comment]
It looks like there's a parsing error when reading the data back from Elasticsearch probably triggered by certain documents (hence why it happens at that particular position). Can you try and isolate the data that triggers it? Potentially enabling logging on the `rest` package and checking the documents that cause the issue?

Thanks,

**Comment by ssemichev** [comment]
I agree, it seems it's data relative issue.

Do you mean add logging to source code? 
Or you are saying about enabling logging on the rest package at log4j configuration?
I can not see any logging record in the code.

Thanks

**Comment by costin** [comment]
I mean the log4j logging - see http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/master/logging.html in particular the `org.elasticsearch.hadoop.rest`

**Comment by ezli** [comment]
Hi Costin, I am ssemichev's colleague. I tried your suggestion to turn on  DEBUG logging for elasticsearch-hadoop by adding the following two lines in log4j.properties:
`log4j.category.org.elasticsearch.hadoop.rest=DEBUG
log4j.category.org.elasticsearch.hadoop.serialization=DEBUG`

And I do see some DEBUG logs for elasticsearch-hadoop:
`15/03/12 16:29:09 DEBUG rest.RestRepository: Closing repository and connection to Elasticsearch ...
15/03/12 16:29:09 DEBUG rest.RestRepository: Sending batch of [0] bytes/[0] entries
`

Then I re-run the export job. However, I do not see any useful logs for the java.lang.IllegalArgumentException. Here is the log I got:
`Error: java.lang.IllegalArgumentException: Invalid position given=347458 -1
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:165)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:403)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
        at org.elasticsearch.hadoop.mr.EsInputFormat$ShardRecordReader.next(EsInputFormat.java:298)
        at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.moveToNext(MapTask.java:199)
        at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.next(MapTask.java:185)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:52)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
`

#### So my questions are:
1. Looks like I need to add more logging information in the code to show the ElasticSearch documents that have problems. Is that true? 
2. Give 1 is true, where is a good place to put these additional logs? What about in [ScrollReader] (https://github.com/elastic/elasticsearch-hadoop/blob/3586c636acb8f2813b66b51e529152fd4bf08a5c/mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java#L234)?
3. We are using the `2.1.0.BUILD-SNAPSHOT` in our code. Which branch was this built from? 

Thanks!

**Comment by ezli** [comment]
Do you think it is a good idea to continue the scroll reader even if there is some bad data? We have 2TB of data in ElasticSearch, and we use elasticsearch-hadoop to export data. It is a problem if the export stopped only because there is one bad data. I tried catch the exception and continue the scroll reader here: https://github.com/targetedvictory/elasticsearch-hadoop/blob/9e221ebf2b2af1f0d9dc5366f733c3392bc518ef/mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java#L166. Could you please take a look at this?

**Comment by costin** [comment]
@ssemichev @ezli This has been fixed in master (see also #385). Can you please try out the latest dev build?

**Comment by ezli** [comment]
@costin Thanks for fixing this. I will test and let you know soon.

**Comment by costin** [comment]
Closing the issue; if the problem persists please create a new one.
