### ISSUE TITLE
Does it make sense to see similiar performance with/without 'es.nodes.client.only' set to 'true'  in spark? this related to #373

### ISSUE THREAD

**Issue by wingchen** [elastic/elasticsearch-hadoop#387]
Hi @costin,

Thank you again for #373. The fix works great.

We have been trying to benchmark the performance with and without `es.nodes.client.only` set to `true`. Here comes the ES cluster settings:

![mycom com](https://cloud.githubusercontent.com/assets/798321/6495685/2b7d8930-c281-11e4-936f-ff1b89bdfd72.png)

There is around 27GB and 2,685,643 documents in this cluster. All of them have http enabled. We then started to use 1 spark worker node to dump entire data out with the following code:

https://gist.github.com/wingchen/24345b5dabf212a19ee6

We set/unset `conf.set("es.nodes.client.only", "true")` at line 11 to see the difference.

It turns out that the performance is not much different from each other.

With `es.nodes.client.only` set to `true`:

```
Elapsed time: 575937176018ns
Elapsed time: 472600809446ns
Elapsed time: 551257582522ns
Elapsed time: 537133446720ns
Elapsed time: 586939805228ns
Elapsed time: 648629441787ns
Elapsed time: 529784087027ns
Elapsed time: 526775918447ns
```

Without `es.nodes.client.only` set to `true`:

```
Elapsed time: 538304918249ns
Elapsed time: 629962009599ns
Elapsed time: 525998454515ns
Elapsed time: 639182008909ns
Elapsed time: 663308006015ns
Elapsed time: 680316998433ns
Elapsed time: 582389258596ns
Elapsed time: 506762219830ns
```

We tried this for couple more times with different ways to loop through all the docs and got similar result.

Does this make sense to you? Did we do anything wrong?

**Comment by costin** [comment]
On such a small cluster and with this data size I would not expect the difference too be too large. ES can work just fine through one or multiple nodes; however as your cluster grows and the number of data nodes >> client nodes, especially for large indices you are likely to see the difference.

Note that in your case you are using only 1 thread so it's unlikely to reap the benefits of using data nodes - with 1 worker you basically serialize all access to ES; if you were to use 2 or more than the data node access could be paralelized and thus differentiate from the client one.

**Comment by wingchen** [comment]
@costin Thank you for the response.
I am adding 2 more ES data nodes into the cluster. I will put the findings in this thread too.

Although we are only using 1 spark worker, it has 4 concurrent threads querying data from ES. This part should be fine though.

**Comment by wingchen** [comment]
updating..

When the data nodes goes to 4:

Queries directly to nodes:
Elapsed time: 470630507777ns
Elapsed time: 406645812219ns
Elapsed time: 408881927157ns
Elapsed time: 414242318143ns
Elapsed time: 452786718960ns
Elapsed time: 372493486682ns
Elapsed time: 474240296835ns
Elapsed time: 397531725737ns
Queries to client:
Elapsed time: 474592889865ns
Elapsed time: 418418365928ns
Elapsed time: 446898938478ns
Elapsed time: 410490175018ns
Elapsed time: 469610069992ns
Elapsed time: 534890328547ns
Elapsed time: 434523328629ns
Elapsed time: 437825524403ns

When data nodes goes to 6:
Queries directly to nodes:
Elapsed time: 377629492849ns
Elapsed time: 341215123920ns
Elapsed time: 317493424817ns
Elapsed time: 391410875052ns
Elapsed time: 321606160207ns
Elapsed time: 324965128633ns
Elapsed time: 358170022240ns
Elapsed time: 343984614895ns
Queries to client:
Elapsed time: 382361635010ns
Elapsed time: 361805287626ns
Elapsed time: 334565486212ns
Elapsed time: 378959307134ns
Elapsed time: 392082768221ns
Elapsed time: 494627115729ns
Elapsed time: 394183382681ns
Elapsed time: 399458519944ns

@costin Like you said, the performance difference will gradually unfold as the number of data nodes grows. Also, I am increasing spark worker count to see what will happen there too.

**Comment by wingchen** [comment]
@costin 
I increased spark workers number to 4 (12 cores) and still see similar results (it's way faster now):

Queries directly to nodes:
Elapsed time: 169175076846ns
Elapsed time: 227021836078ns
Elapsed time: 247021145438ns
Elapsed time: 259099202476ns
Elapsed time: 196787504525ns
Elapsed time: 232730755253ns
Elapsed time: 163212245504ns
Elapsed time: 226552320074ns

Queries to client:
Elapsed time: 277207796177ns
Elapsed time: 209881209785ns
Elapsed time: 272959493646ns
Elapsed time: 200681801838ns
Elapsed time: 232259698945ns
Elapsed time: 164348253066ns
Elapsed time: 254794330333ns
Elapsed time: 238033701832ns

The numbers are too odd, so I went into newrelic to monitor the traffic of two different configurations: client only and otherwise.

It turns out that there is no significant amount of traffic going through client at all during the whole time:
![client](https://cloud.githubusercontent.com/assets/798321/6565547/0feacb2e-c66e-11e4-9381-1d48359d4c6a.png)

However, the data nodes are transmitting data without any problem:
![nodes](https://cloud.githubusercontent.com/assets/798321/6565586/6314df60-c66e-11e4-8fb1-6aa297bcc7d2.png)
(Please note that I ran client-only and otherwise interchangeably during the 6 times of execution.)

In this case, it seems that no matter I set `es.nodes.client.only` or not, data is passing out through data nodes, not client. Can you confirm it?

The ES cluster configuration is here: https://gist.github.com/wingchen/fb332414d0e1e5a3b844 Please let me know if any of the configuration is preventing client nodes configuration from working.

Thanks

**Comment by costin** [comment]
@wingchen Repicking up this thread.
By using the client nodes, the connector is simply re-routed; the client nodes forwards the request internally to the data node. So the traffic will occur on that node - and in case of queries, the results is simply returned.
Now if all the data is being returned and the connection doesn't happen through the client nodes than this indicates an issue.

The easiest ways to double check this is:

1. disable HTTP on data nodes and only leave it on client nodes. The connector won't be able to connect to the data nodes, even if it wants to.

2 turn on logging on the rest package and monitor the connections made. Additionally, log the traffic and what the IPs used.

Do note that if you a running client nodes on the same machines as the data nodes, the same network card and potentially IP will be used (but on a different port). And that's to be expected however it might be interpreted incorrectly when monitoring.

**Comment by jbaiera** [comment]
Closing this out as inactive
