### ISSUE TITLE
[Documentation][ newHadoopRDD not a member of SparkContext

### ISSUE THREAD

**Issue by eliasah** [elastic/elasticsearch-hadoop#390]
Following the documentation section about the [Apache Spark support](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html)

I have noticed the following when defining the context to read data from Elasticsearch :

    val esRDD = sc.newHadoopRDD(conf, classOf[EsInputFormat[Text, MapWritable]],     
                                  classOf[Text], classOf[MapWritable]))

Beside the extra parenthesis by the end, newHadoopRDD is not a member of SparkContext. So how do we define the RDD using the new Hadoop API.

Thanks! :)

**Comment by MLnick** [comment]
It is `sc.newAPIHadoopRDD(...)` - I have submitted a PR for updating the doc

**Comment by eliasah** [comment]
Ok thanks! Then we should close the issue once the PR has been accepted

**Comment by MLnick** [comment]
@eliasah can close this now I think :)
