### ISSUE TITLE
[spark] saveToEs [PUT] on [ _bulk] failed; server[null] returned [504|null]

### ISSUE THREAD

**Issue by 506764932** [elastic/elasticsearch-hadoop#396]
i am using elasticsearch-hadoop dump my 1,600,000 data from mongoDB.
when running. the data always lost ,the log print saveToEs [PUT] on [ _bulk] failed; server[null] returned [504|null] . says the task failed . what should i do?

**Comment by jbaiera** [comment]
This is a really old issue with no follow ups. I'd like to close this for inactivity. If the problem persists, please open a new ticket.
