### ISSUE TITLE
es.nodes and es.nodes.discovery question

### ISSUE THREAD

**Issue by bitsofinfo** [elastic/elasticsearch-hadoop#399]
For our ES cluster, we force all connections, for meta-data, reads/writes to go through a few limited "client" nodes. Our data-nodes are not directly accessible.

When reading the docs, I see that you can specify one or more nodes in `es.nodes` and these will be used to discover the nodes where the shards actually exist. I guess this is in combination with `es.nodes.discovery` (nodes for meta-data only?)

So what is the behavior if our network ACLs only permit ES reads/writes to go through our ES client nodes, and we don't permit direct access to the data nodes? Will elasticsearch-hadoop still try to connect  and just fail? or will it revert to just using the nodes we have specified via `es.nodes`

**Comment by costin** [comment]
This has been fixed through the introduction of client nodes support in 2.1.x (and all subsequent releases).

Cheers,
