### ISSUE TITLE
newAPIHadoopRDD does not wok properly with DSL QUERIES

### ISSUE THREAD

**Issue by 2dmitrypavlov** [elastic/elasticsearch-hadoop#407]
Hello,
I would run following code for a while now and i am not able to get proper results set (even not properly sorted), every time I run dsl query it return all results as in match_all case. The only case that works for me is running simple queries such as ?q=hello or ?q=:my_field:hello. If i put more then two terms it fails.
thanks a lot 
val cnf = new JobConf()
    cnf.set("es.resource", EsUtils.ESINDEX)
    cnf.set("es.nodes", EsUtils.ESIP)
    val b = """{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"""
    val a = """}}],"must_not":[],"should":[]}},"from":0,"size":1,"sort":[],"facets":{}}"""
    val q = b + "\"" + query + "\"" + a

```
val q5 = """{
"query": {
    "match": {
        "_all": " 35559 v script type text javascript language JavaScript 1 2 CDATA window calcPriceData priceTo productX 35 000 productY 18 price 593 70 productInBox product avail 119 div id browse form name orderform method post action cart php mode add 36561 span h2 li dl class each dt pr TaxedPrice1 Sale Price dd TaxedPrice priceto Market alt 771 81 You Save"
    }
}
```

}"""
    cnf.set("es.query", q5)  
    val res = sc.newAPIHadoopRDD(cnf, classOf[EsInputFormat[Text, MapWritable]], classOf[Text], classOf[MapWritable])
    val res_map = res.map { l => (l._1.toString(), l._2.map { case (k, v) => (k.toString, v.toString) }.toMap) }
    val prices = res_map.take(10).map { p => p._2.get("price").get.toString }

**Comment by jbaiera** [comment]
Closing this since this is a fairly old ticket. The query parsing logic was re-written in 5.0. If the 5.x line is still not working with DSL queries, then we can open a new ticket to address.
