### ISSUE TITLE
QUESTION: Hadoop as Long-Term Archive for Elasticsearch, but will it work using hadoop compression like gzip?

### ISSUE THREAD

**Issue by rodrigo-merino** [elastic/elasticsearch-hadoop#420]
Hi all,

we are going to receive a huge amount of logs and we are going to process them with the typical ELK stack. But because of volume we plan to keep, in ElasticSeach a week or at most a month of logs. After that time we plan to use the Elasticsearch - hadoop integration, mainly for Long-Term Archive, so older logs are moved to Hadoop. Disk space is a very important issue here and we plan to use hadoop compression codecs like gzip, for those logs older than a month.

If we use compression in hadoop, can we still index + graph data stored in logs older than a month? Or for this goal, logs must be stored in a raw format?

As far as I have read, if logs (in raw) are stored in hadoop, thanks to the elasticsearch-hadoop integration, elasticsearch can index on them, and kibana can report seamlessly both logs, current logs (stored locally in elasticsearch servers) or older logs (in hadoop). Please correct me if I am wrong. The question is if we lose this feature if we compress the logs in hadoop.

Any help is appreciated.

Thanks and best regards,
Rodrigo.

P.S.: Do not hesitate to challenge the architecture/data-flow as well, if you think there are better ways to do it.Thanks.

**Comment by costin** [comment]
@rodrigo-merino with all due respect, this is the issue tracker which is for bug reports not architectural questions. Please post your question on the mailing list and I'll be more than happy to respond there.

Cheers,

**Comment by costin** [comment]
@rodrigo-merino I see you already [posted](https://groups.google.com/d/msgid/elasticsearch/5810a405-8fd8-41f6-b949-9c36cb856b9d%40googlegroups.com?utm_medium=email&utm_source=footer) on the mailing list. I realize you are inpatient but in the future, please don't cross post - it's not going to speed things up but rather annoy the people reading the list since you are basically spamming.
Which is not cool at all.

**Comment by rodrigo-merino** [comment]
Thanks a lot. Sorry for the inconveniences. And thanks a lot for your answer.
Best regards,
Rodrigo.

----- Reply message -----
De: "Costin Leau" <notifications@github.com>
Para: "elastic/elasticsearch-hadoop" <elasticsearch-hadoop@noreply.github.com>
CC: "rodrigo-merino" <rodrigo.merino@gmail.com>
Asunto: [elasticsearch-hadoop] QUESTION: Hadoop as Long-Term Archive for Elasticsearch, but will it work using hadoop compression like gzip? (#420)
Fecha: vie., abr. 10, 2015 13:29

@rodrigo-merino I see you already posted on the mailing list. I realize you are inpatient but in the future, please don't cross post - it's not going to speed things up but rather annoy the people reading the list since you are basically spamming.

Which is not cool at all.

&mdash;
