### ISSUE TITLE
Mistakes in documentation

### ISSUE THREAD

**Issue by andrejsab** [elastic/elasticsearch-hadoop#421]
In Apache Spark Scala reading example there is  `sc.esRDD("radio/artists", "?me*") `, it should be `sc.esRDD("radio/artists", "?q=me*") `
and similare mistakes in onther parts like 
`'val sql = new SQLContext(sc)
val people = sqlContext.esDF("spark/people") ` where it should be `val people = sql.esDF("spark/people")`

**Comment by costin** [comment]
Fixed in master. By the way, both `"?me*"` and `?q=me&` work but I opted for the first one for consistency.

**Comment by andrejsab** [comment]
for me `"?me*"` produces following error "org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot token [me*] in uri query [me*]"
 I use spark 1.3.0, ES 2.1.0.Beta3 in local mode and I'm runing  elasticsearch-1.5.1 server
