### ISSUE TITLE
Introduce configuration for returning `Date` object as primitives

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#422]
Sometimes, returning a Date as a `long` or `String` might be preferred to that of a rich object where available. While the user can do so by implementing their own deserializer, it would be nice/convenient to have this provided out of the box.

**Comment by mgreene** [comment]
I'm not entirely sure if this is being considered or not, but it does seem that this is less of a static configuration if I'm understanding it correctly.

ES seems to allow you to write a `Date` value in a variety of formats. What I'm hoping for is that the interfaces between ES and processing frameworks like Hadoop and Spark will dynamically deserialize into the correct data type given the format it is stored in.

So if I have a mapping like:

```json
"created_at": {
    "type": "date"
},
"updated_at": {
    "type": "date",
    "format": "yyyy-MM-dd"
}
```

and I index a `long` UTC millis value to `created_at` and a human readable date string to `updated_at` I would expect to get the same formats back during the deserialization process.

**Comment by costin** [comment]
The issue has been addressed in master, the docs updated and the nightly builds published.
In short, by default, `date` objects are returned as _rich_ objects (they vary depending on the library used). To get the fields as primitives (`long` or `String` depending on how they are stored), one should use `es.mapping.date.rich` field and configure it to `false`.

**Comment by costin** [comment]
Closing the issue; if the problem persists please create a new one.
