### ISSUE TITLE
IDEA support

### ISSUE THREAD

**Issue by b0c1** [elastic/elasticsearch-hadoop#423]
Hi,

I tried to import the project in intellij idea but I got: "Could not find property 'scala' on source set 'main'". How can I solve this (sry, I'm familiar with mvn and sbt, but not with gradle)

Thanks

b0c1

**Comment by costin** [comment]
I'm afraid I'm not using IDEA so I don't know what is wrong. If the latest IDEA doesn't import the gradle file correctly, try generating the project files from gradle: `gradlew idea: idea`

Note that the Eclipse support has some issue hence why the build file contains some workarounds these so one doesn't have to do them by hand. It _might_ be needed that the some workarounds are required for IDEA as well though again, you can fix them manually.

http://gradle.org/docs/current/userguide/idea_plugin.html

**Comment by b0c1** [comment]
I got same error with eclipse (scala ide + gradle):

Could not find property 'scala' on source set 'main'.
Could not fetch model of type 'HierarchicalEclipseProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-1.12-bin.zip'

**Comment by costin** [comment]
Make sure you are using ScalaIDE since plain Eclipse doesn't support Scala. Or make sure to add install the Scala plugin.

On 4/14/15 10:34 PM, Janos Haber wrote:
> I got same error with eclipse (scala ide + gradle):
>
> Could not find property 'scala' on source set 'main'.
> Could not fetch model of type 'HierarchicalEclipseProject' using Gradle distribution
> 'https://services.gradle.org/distributions/gradle-1.12-bin.zip'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-hadoop/issues/423#issuecomment-93032109>.
>

-- 
Costin

**Comment by b0c1** [comment]
I downloaded fresh new install from http://scala-ide.org/, and after that I installed the gradle plugin... need any other plugin or something? (I got same error when I run gradle from command line)

**Comment by b0c1** [comment]
I added: ```    apply plugin: 'scala'``` to the build.gradle, now it's compiling...

**Comment by b0c1** [comment]
I checked the gradle file and I see the problem is my jdk is java 8. otherwise it's added scala plugin already...

**Comment by costin** [comment]
Did you get a message that building the scala project under JDK 8 is not
supported (Scala doesn't support yet JDK 8 in 2.10 and 2.11)?
Sorry for your trouble - is there anything we can do to make things
easier/clearer?

**Comment by b0c1** [comment]
Yeah I got the message, but I think I can import and after that I can change the JDK. Maybe if java8 detected need to stop the build instantly (not a simple message but throw an exception), but this is just an Idea :)

**Comment by costin** [comment]
No exception is thrown since:

1. it is assumed the user actually reads build messages - they aren't that
many. The fallacy of the logs :)
2. if one wants to build and run the projects on JDK 8, it's significantly
easier to do so then specifying all the projects by hand.

These being said, I can see your predicament and try to find a solution to
the above while stopping the build.

Cheers,

**Comment by b0c1** [comment]
I tried to pull up the application, but if I activate scala nature and run the gradle eclipse refresh, most project dir are disappeared from the project (and the project will be invalid)... can you send me your eclipse dir? maybe I missed some plugin or I do something wrong... (I want to debug the #385 problem)

**Comment by costin** [comment]
I'm using Scala IDE 4.0.0. You need to check out the entire package and from the root of it, do `gradlew cleanEclipse eclipse`.
Both spark projects (1.3 and 1.2) will refer to the core project as you can see from the `.project` and `.classpath` files which you can find [here](https://gist.github.com/costin/2a1588cec8013c7d0b0b).

**Comment by b0c1** [comment]
you installed gradle plugin?

**Comment by sidorykp** [comment]
I had exactly the same problem in IntelliJ IDEA ("Could not find property 'scala' on source set 'main'"). The solution was simple: use JDK 1.7 to run Gradle.
