### ISSUE TITLE
Jackson error in elasticsearch hadoop while loading data to elasticsearch

### ISSUE THREAD

**Issue by sibbsnb** [elastic/elasticsearch-hadoop#425]
I am trying to load data from hdfs to elasticsearch using elasticsearch-hadoop version elasticsearch-hadoop-2.1.0.Beta3.jar.

There was a bug on Mapr https://github.com/elastic/elasticsearch-hadoop/issues/215 which was supposed to fix the jackson issue. But it is still taking the jackson jars from the hadoop directory which has jackson version 1.5.

I did register commands to the 1.8 jars: REGISTER /opt/mapr/hive/hive/lib/jackson-core-asl-1.8.8.jar; REGISTER /opt/mapr/hive/hive/lib/jackson-jaxrs-1.8.8.jar; REGISTER /opt/mapr/hive/hive/lib/jackson-mapper-asl-1.8.8.jar; REGISTER /opt/mapr/hive/hive/lib/jackson-xc-1.8.8.jar;

But i am still getting the error i am getting: 
2015-04-17 05:49:03,760 [main] ERROR org.apache.pig.tools.pigstats.SimplePigStats - ERROR 2997: Unable to recreate exception from backed error: Error: org.codehaus.jackson.map.ObjectMapper.reader(Ljava/lang/Class;)Lorg/codehaus/jackson/map/ObjectReader;

i tried the same with Hive and getting the same error as well.

**Comment by costin** [comment]
What version of MapR are you using? Jackson 1.5 is quite old (from 2010). Registering the jackson jars does not help since they can't override the ones in Hadoop - these are already loaded.
You need to replace the jackson jars in MapR with the recent ones.

Can you please post (as a gist not in the post) information about the mapR version as well as Hive and Pig and your classpath?

Thanks,

**Comment by sibbsnb** [comment]
It will take time to upgrade the Jackson jar as it is a big cluster. Is there any workaround?

Below are the verisons:

mapr 3.0.1 verison
maprfs-core-1.0.3-mapr-3.0.2.jar

hive-beeline-0.12-mapr-1401-140130.jar

Apache Pig version 0.12.1-mapr-1401

Hadoop 1.0.3

**Comment by costin** [comment]
@sibbsnb The latest version of es-hadoop should work with MapR 3.0.1. Can you confirm the version used (by logging at the logs and checking the version displayed)?
Also can you post the full stacktrace behind the Pig version (please format the code through markdown or post it as a gist).

Thanks,

**Comment by costin** [comment]
@sibbsnb Since there hasn't been any update on this issue I'm closing it. If that's not the case, please open a new one and link this issue to it.
Thanks!
