### ISSUE TITLE
Incorrect parameter names es.update.params and es.update.params.json in config examples

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-hadoop#430]
http://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_update_settings

>es.update.script.params (default none)
Script parameters (if any). The document (currently read) field/property who’s value is used. To specify a constant, use the <CONSTANT> format. Multiple values can be specified through commas (,)
For example:

>specifying 2 parameters, one extracting the value from field 'number', the other containing the value '123':
es.update.params = param1:number,param2:<123>

>es.update.script.params.json
Script parameters specified in raw, JSON format. The specified value is passed as is, without any further processing or filtering. Typically used for migrating existing update scripts.
>For example:
es.update.params.json = {"param1":1, "param2":2}

The doc specifies `es.update.script.params ` and `es.update.script.params.json` as configuration options.  But in their respective examples, it references `es.update.params` and `es.update.params.json` instead of the correct parameter names ( `es.update.script.params ` and `es.update.script.params.json`)

**Comment by costin** [comment]
Thanks, fixed the docs in master and 2.x
