### ISSUE TITLE
/elasticsearch-hadoop/mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java:333: illegal start of expression

### ISSUE THREAD

**Issue by AntBean** [elastic/elasticsearch-hadoop#431]
when I try to build the project from git clone, use the command:./gradlew  --info

in Ubuntu , the system java version is : 
java version "1.6.0_20"
OpenJDK Runtime Environment (IcedTea6 1.9.7) (6b20-1.9.7-0ubuntu1~10.04.1)
OpenJDK Client VM (build 19.0-b09, mixed mode, sharing)

I get the error like below:

/elasticsearch-hadoop/mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java:333: illegal start of expression

All input files are considered out-of-date for incremental task ':elasticsearch-hadoop-mr:compileJava'.
Compiling with JDK Java compiler API.
/root/elasticsearch-hadoop/mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java:333: illegal start of expression
            return (currentTask >= esPartitions ? Collections.<PartitionDefinition> emptyList() : 
                                                                                        ^
Collections.singletonList(partitions.get(currentTask)));
                                                              
1 error
:elasticsearch-hadoop-mr:compileJava FAILED
:elasticsearch-hadoop-mr:compileJava (Thread[main,5,main]) completed. Took 1.183 secs.

**Comment by costin** [comment]
Can you try using the Sun JDK or even better JDK 1.7. The binaries are 1.6
compatible but 1.7 is required to compile all the modules.

**Comment by AntBean** [comment]
when i use sun jdk 1.7, I can build. This issue will be closed
