### ISSUE TITLE
failed unit test dateindexformattertest

### ISSUE THREAD

**Issue by AntBean** [elastic/elasticsearch-hadoop#433]
I build it under java 1.7.0_51,windows7, es-hadoop version is the newest master version. and failed the unit test
org.elasticsearch.hadoop.serialization.field.DateIndexFormatterTest > testTimeYM
DFormat                                                                        FAILED
    java.lang.AssertionError at DateIndexFormatterTest.java:34

289 tests completed, 1 failed, 19 skipped
:elasticsearch-hadoop-mr:test FAILED

FAILURE: Build failed with an exception.

the detail information is:

testTimeYMDFormat

java.lang.AssertionError: 
Expected: is "2014.10.06"
     but: was "2014.10.07"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.hadoop.serialization.field.DateIndexFormatterTest.testTimeYMDFormat(DateIndexFormatterTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by costin** [comment]
Hi,

You might have stumbled onto a subtle bug. I have updated the master - can you please retry the build again please?

By the way, what's your timezone/locale?

**Comment by AntBean** [comment]
My TimeZone is Asia/Shanghai. I will retry the build later

**Comment by costin** [comment]
Closing the issue. If the problem persists, please create a new one.
