### ISSUE TITLE
Cannot set es-resource properties from the command-line

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#434]
Spark doesn't allow properties not starting with `spark.` to be set from the command-line, removing them. This means it is not possible to set any of the es-hadoop properties from the command-line and thus complicates externalization.

**Comment by pickypg** [comment]
If you submit an ES property, such as `es.nodes=192.168.50.2:9200`, then it will be ignored:

> Warning: Ignoring non-spark config property: es.nodes=192.168.50.2:9200

[Spark apparently ignores all properties not prefixed with `spark.`](https://github.com/apache/spark/blob/336f7f5373e5f6960ecd9967d3703c8507e329ec/core/src/main/scala/org/apache/spark/deploy/SparkSubmitArguments.scala#L121)

**Comment by costin** [comment]
Fixed in master.
