### ISSUE TITLE
Cannot Find Node

### ISSUE THREAD

**Issue by webtoed** [elastic/elasticsearch-hadoop#436]
Version: 2.1.0.Beta3 
Elastic.version: 1.4.4

Set to :  'es.nodes.client.only' = 'true',

java.io.IOException: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find node with id [KRPdnBpJRc2FkyTJ_oRQpQ] (is HTTP enabled?) from shard [Shard[state=STARTED, primary=true, node=KRPdnBpJRc2FkyTJ_oRQpQ, name=0, index=metrics-2015.04.18]] in nodes [[{state=STARTED, primary=true, node=KRPdnBpJRc2FkyTJ_oRQpQ, relocating_node=null, shard=0, index=metrics-2015.04.18}, {state=STARTED, primary=false, node=sPeEIWyBRZWlnHAHevG7Ng, relocating_node=null, shard=0, index=metrics-2015.04.18}]]; layout [[[{state=STARTED, primary=true, node=KRPdnBpJRc2FkyTJ_oRQpQ, relocating_node=null, shard=0, index=metrics-2015.04.18}, {state=STARTED, primary=false, node=sPeEIWyBRZWlnHAHevG7Ng, relocating_node=null, shard=0, index=metrics-2015.04.18}], [{state=STARTED, primary=false, node=MB83hrQtR-CgPEfKfUFYWA, relocating_node=null, shard=1, index=metrics-2015.04.18}, {state=STARTED, primary=true, node=KRPdnBpJRc2FkyTJ_oRQpQ, relocating_node=null, shard=1, index=metrics-2015.04.18}]]]

**Comment by costin** [comment]
`es.nodes.client.only` is supported only in master not in Beta3. The exception that you are getting shows (in a bad way) that the node you specified cannot be found because it is not a data node - upgrade to the dev snapshot.

**Comment by webtoed** [comment]
this ->
https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-hadoop/2.1.0.BUILD-SNAPSHOT/elasticsearch-hadoop-2.1.0.BUILD-20150428.023724-383.zip

**Comment by webtoed** [comment]
Here are my node types: Master, Search, Index, Data.
The Data nodes do not have HTTP enabled. 
The LB URL for Search would be https://enviro.qa.comp.org/ES.
I can hit the Search nodes via IP which are behind the LB URL - 10.2.20.139:9200, 10.2.20.140:9200

Here is a sample query:
CREATE EXTERNAL TABLE qa_metrics (
  date timestamp,
  category string,
  subcategory string,
  application string,
  version string,
  company_id string,
  hostname string,
  entity_code string,
  datacenter_location string)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource'= 'metrics-2015.04.18/metrics',
        'es.nodes' = '10.2.20.139,10.2.20.140',
        'es.nodes.client.only' = 'true',
        'es.field.read.empty.as.null' = 'true',
        'es.mapping.id' = '_id',
        'es.mapping.names' = 'date:metrics.@timestamp,
                              category:metrics.Category, 
                              subcategory:metrics.Subcategory, 
                              application:metrics.Application, 
                              version:metrics.Version,
                              company_id:metrics.extra_data.company_id,
                              hostname:metrics.Hostname,
                              datacenter_location:metrics.datacenter_location,
                              entity_code:metrics.entity_code');

**Comment by costin** [comment]
That's the one and soon Beta4 will be available in the maven repo. For data nodes, you need to enable the HTTP port; this is a requirement of the connector. If that's not an option, you can enable client nodes with HTTP enabled and configure the connector to use only those.
Without http, I'm afraid the connector won't work.

**Comment by webtoed** [comment]
The search nodes are: 10.2.20.139,10.2.20.140 ---
http.enabled: true
node.data: false
node.master: false

**Comment by webtoed** [comment]
@costin Should this work with nodes i listed above and the use of es.nodes.client.only?

**Comment by costin** [comment]
the params you specify in `es.nodes` only need to have HTTP access. In a client only scenario, it is recommended to specify some of client nodes here - you don't need all of them since they'll be discovered automatically.

Can you double check you are using Beta4 (and that no other jar is available in the classpath) and follow the instructions [here](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help). In particular, turn on logging on the REST package and please upload as a gist the logs somewhere.

Cheers,

**Comment by webtoed** [comment]
Yes - I removed all files except - elasticsearch-hadoop-2.1.0.Beta4.jar

Here is the hive output:
http://pastebin.com/4fnkwkYR
and
http://pastebin.com/rNPPiHm5

I did notice another error, this time... I'm not sure this is related...

Error!
java.io.IOException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.ClassCastException: org.apache.hadoop.io.LongWritable cannot be cast to org.apache.hadoop.io.Text

**Comment by webtoed** [comment]
@costin Any ideas

**Comment by webtoed** [comment]
@costin Any thoughts to this issue?

**Comment by costin** [comment]
Not at the moment, no. When I do, I'll post them - the error does seem conspicuous and likely is caused by an incorrect mapping as explained [here](http://www.elastic.co/guide/en/elasticsearch/hadoop/2.1.Beta/mapping.html#_automatic_mapping). What's your ES mapping?

**Comment by webtoed** [comment]
My Mapping is huge, but the hive statement I used works in a lower environment. This lower environment has http enabled on all data nodes. Both environments use the same mapping. 
I also confirmed my mapping against the one failing...

**Comment by costin** [comment]
What's the mapping relevant to the fields used by the Hive table? The
connector will use those and ignore the rest.

**Comment by webtoed** [comment]
I was able to get this working after I opened up http on the data nodes. 
I can retest the above HIVE Statement. But I need to be able to get es.nodes.client.only working in the next environment. 

Understood about the mapping - 

1) Does es.resources require the Type or can it just be an index? 
2) When using es.query, does this change the path for es.mapping.names?

**Comment by costin** [comment]
1. es.resource requires an index and type - you can use wild cards but in
the end, it will be resolved to an index and a type; see the documentation
2. not sure what you mean - es.query is the query to elasticsearch,
es.mapping.names handles the mapping between Hive and Elasticsearch. If in
your es.query you want to refer to fields in elasticsearch that are mapped
to the Hive table, then use the Elasticsearch names.
There is no translation of the es.query done by the connector.

**Comment by webtoed** [comment]
-What does the es.query provide? How does it help in most cases?
I was trying to use this to isolate the data further, by only returning specific data from Elastic. 

To explain my previous question - mapping of fields is direct when looking at data in Elastic. You use a path/field name to perform a search.  However performing a search (Post) the return data has changed the field path. 

Example:  to search you can use the metric.application on the index. The reference to this field in the returned JSON , data.hits.hits.appliciation. 

I was wondering it using es.query transforms the path or mappings in any way. 

My other issue - 444 seems to be more relevant now. I have moved my client.nodes only testing into another environment that has http disabled on all DATA nodes. This has the latest HIVE and Issue. It a different error from "cannot find node" 

If you deem them not related we can keep each open. My bottom line is , I need to get client only working. 

Thanks so much for your time thus far...

**Comment by costin** [comment]
@webtoed Does this mean you have found the solution to your problem? Does client routing works for you or not? And if so, what was the problem in the first place?
