### ISSUE TITLE
Version compatibility detection wrong in 2.1.0.BUILD-SNAPSHOT (Tue Apr 28 00:37:19 EEST 2015)

### ISSUE THREAD

**Issue by ejsarge-gr** [elastic/elasticsearch-hadoop#440]
I'm getting the following warning in my log.

`15/04/29 10:04:38 WARN rdd.EsSpark: Incorrect classpath detected; Elasticsearch Spark compiled for Spark 1.0-1.2 but used with Spark 1.3.1`

I checked the code and it's using the absence of `org.elasticsearch.spark.sql.EsSchemaRDDWriter` to detect that this library was compiled for Spark 1.3.1.

In the snapshot I have that library does, indeed, exist.

**Comment by costin** [comment]
What is your environment? The behaviour you are describing is correct - `EsSchemaRDDWriter` is available only in the jar for Spark 1.0-1.2.
It's not clear from this report what is the issue...

**Comment by ejsarge-gr** [comment]
This specific Jar, https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/elasticsearch-hadoop/2.1.0.BUILD-SNAPSHOT/elasticsearch-hadoop-2.1.0.BUILD-20150427.213847-382.jar, is what I'm using at the moment (because we need the conf change to use spark.es.nodes, etc.).

Are the snapshots not built for 1.3.1?

**Comment by costin** [comment]
It is however that is an old snapshot which by mistake, incorporated both Spark 1.2 and 1.3 code into one jar. Try the latest one (typically sbt, maven,gradle will automatically download the latest snapshots) or Beta4.

**Comment by ejsarge-gr** [comment]
Great, you're correct. The latest snapshot makes that message go away. I'll close this.

I'll note, in parsing, that I've currently seeing errors with the Spark SQL auto schema discovery but I'll figure out a minimal repro for that.

**Comment by costin** [comment]
Cheers!

**Comment by fpopic** [comment]
`WARN EsSpark: Incorrect classpath detected; Elasticsearch Spark compiled for Spark 1.3 (or higher) but used with Spark 2.0.0`

`lazy val root = (project in file(".")).settings(
  organization := "com.fp",
  name := "MySbtScalaProject",
  version := "1.0",
  sbtVersion := "0.13.12",
  scalaVersion := "2.11.8", // for %% operator
  parallelExecution in Test := true
)

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % "2.0.0",
  "org.apache.spark" %% "spark-sql" % "2.0.0",
  "org.apache.spark" %% "spark-streaming" % "2.0.0",
  "org.apache.spark" %% "spark-streaming-kafka" % "1.6.2",

  "com.typesafe" % "config" % "1.3.0",

  "org.scalactic" %% "scalactic" % "3.0.0",
  "org.scalatest" %% "scalatest" % "3.0.0" % "test",
  "org.scalamock" %% "scalamock-scalatest-support" % "3.2.2" % "test",

  "com.microsoft.sqlserver" % "sqljdbc4" % "4.0",
  "org.elasticsearch" %% "elasticsearch-spark-20" % "5.0.0-alpha5",
  "com.databricks" %% "spark-csv" % "1.4.0"
)`

**Comment by jbaiera** [comment]
@fpopic - Good find! The compatibility check code assumes Spark 1.3 compatibility in the case that `EsSchemaRDDWriter` is absent. This class was only present in the old es-spark `1.0-1.2 compatibility` packages. Since the `1.0-1.2` packages have been removed with the advent of Spark 2.0, the check now erroneously assumes that every version run is es-spark `1.3` compatibility. This is not a blocker, as it simply prints a warning log, but it is indeed confusing.

Could you kindly open a new Github issue for this so that we may track it separately from this currently closed one? Thanks.

**Comment by fpopic** [comment]
Thanks, I did it: https://github.com/elastic/elasticsearch-hadoop/issues/824 (it my first ever :) )
