### ISSUE TITLE
Adding Nodes in ES-Yarn

### ISSUE THREAD

**Issue by WalterDalton** [elastic/elasticsearch-hadoop#443]
Is there is a simple way to scale up more nodes in ES Yarn?

**Comment by costin** [comment]
es-yarn allows you to specify the number of nodes at startup. Changing the
number of required resources cannot be done dynamically in YARN (currently)
so one would have to either restart the process (that is, stop the current
setup and create a new one with the new settings) or potentially start a
different es-yarn configuration with the delta resources; if the same setup
is used, the new nodes should be able to pick the old ones up.

However, as I've mentioned this goes beyond the official features in YARN
and thus, it is quite brittle and might not work at all.

Cheers,


P.S. This is an issue tracker, not a forum - please use the mailing list
next time for asking questions. Thanks!
