### ISSUE TITLE
Hive cannot read @timestamp from ES which format is unix time 

### ISSUE THREAD

**Issue by stongline** [elastic/elasticsearch-hadoop#452]
hive require timestamp format must be yyyy-mm-dd hh:mm:ss,how to read unix time ,please help me ,thanks

**Comment by duke8249** [comment]
ES @timestamp format is yyyy-mm-dd hh=mm:ss which matches hive perfectly. I have tried to read from ES and it works fine.

**Comment by costin** [comment]
@stongline @duke8249 Can you please provide more information. Potentially opening up a thread on the [forum](discuss.elastic.co)?

Thanks,
