### ISSUE TITLE
Hadoop Configuration setMapOutputValueClass method doesn't exists

### ISSUE THREAD

**Issue by gquintana** [elastic/elasticsearch-hadoop#454]
In http://www.elastic.co/guide/en/elasticsearch/hadoop/2.0/mapreduce.html#writing-json-new-api code exemple
```
Configuration conf = new Configuration();
conf.set("es.input.json", "yes");                 
conf.setMapOutputValueClass(BytesWritable.class); 
```
The `setMapOutputValueClass` method doesn't exist on class`Configuration`

**Comment by costin** [comment]
Fixed in master.
