### ISSUE TITLE
Json value extraction fails with mixed nested objects

### ISSUE THREAD

**Issue by shawnsmith** [elastic/elasticsearch-hadoop#455]
The json extraction code in `ParsingUtils.values()` doesn't always extract the right values when the dot paths are at a mix of levels within the Json object.  For example, given the following source JSON and matching on "a.b" and "c", the extractor can't find the value of "c" because the parser gets stuck in the nested object "a":

json:
```
{
   "a" : { "b": "nested" },
   "c" : "top-level"
}
```

test case:
```
@Test
public void testMixed() throws Exception {
    List<Object> vals = ParsingUtils.values(parser, "a.b", "c");
    assertEquals(2, vals.size());
    assertEquals("nested", vals.get(0));
    assertEquals("top-level", vals.get(1));
}
```

test case output:
```
org.junit.ComparisonFailure: 
Expected :top-level
Actual   :(not found)
```

Note that this test succeeds if the order of "a" and "c" happen to be reversed in the source JSON.

Here's a test case that will reproduce the problem within the existing unit tests:
```
public class JsonValuePathTest {
    ...

    @Test
    public void testMixedLevels() throws Exception {
        List<Object> vals = ParsingUtils.values(parser, "firstName", "address.state", "state");
        assertEquals(3, vals.size());
        assertEquals("John", vals.get(0));
        assertEquals("NY", vals.get(1));
        assertEquals("CA", vals.get(2));
    }
```

**Comment by costin** [comment]
Fixed through the PR in master and 2.x
