### ISSUE TITLE
is JOIN operation possible in ElasticSearch using a Presto Connector ?

### ISSUE THREAD

**Issue by sumanth232** [elastic/elasticsearch-hadoop#459]
As we know that JOIN operation is not possible in ElasticSearch among indices, Can it be achieved, i.e. can we do a JOIN operation using Presto Connector for Elastic Search ?

**Comment by costin** [comment]
There is no presto connector for elasticsearch. Any JOINs that might be attempted, would have to be made in memory or anyway, outside Elastic itself.

Last but not least, this is an issue tracker - for questions and general discussions, please use the dedicated forum [here](https://discuss.elastic.co/c/elasticsearch-and-hadoop).
