### ISSUE TITLE
Behavior of elasticsearch-hadoop/spark when es nodes are restarted

### ISSUE THREAD

**Issue by hsunami** [elastic/elasticsearch-hadoop#462]
Is there a recommended protocol for restarting elasticsearch machines when data is being streamed in live from Spark into Elasticsearch? How does elasticsearch-hadoop/spark deal with node failure?

Thanks in advance.

**Comment by costin** [comment]
No sure what you mean by protocol - if you need to restart the nodes then any data that is being streamed to the cluster will fall back to any available nodes.  Restarting nodes means the cluster state needs to be shuffled around so do expect performance to slow down.
I'm not sure why you would want to restart the nodes however in cases like this having some type of buffer or queue in front tends to provide the 'space' needed to for differences in system lifecycle.

Last but not least, for questions please use the [forums](https://discuss.elastic.co) - an issue tracker is not the appropriate place for asking questions.

Thank,

**Comment by hsunami** [comment]
Sorry about that @costin. thanks for the quick reply! will use forums next time.
