### ISSUE TITLE
Reading BulkResponse of BulkRequestBuilder in spark?

### ISSUE THREAD

**Issue by piyushGoyal2** [elastic/elasticsearch-hadoop#463]
Hi Costin,
If I see the elasticsearch API, for bulk add, update and delete functionality, the response obtained from execute.actionGet always contains the information such as hasFailure, failureMessages, numberOfActions and other parameters. 
However, with spark, saveToES(with or without Meta) returns Unit. Is there a way wherein I can collect the response and see at least certain items such as hasFailure and failureMessage?

**Comment by costin** [comment]
No, one would get an exception in case of failure and the exception message would contain any relevant information.

There are various reasons why that is, the main one being that the connector does not control the runtime (it's YARN, Hadoop, Spark, Akka, etc..) and only an exception can prevent those from assuming everything went okay.
Additionally, in terms of sync/async, distributed vs local things tend to be different and a fail fast stop works consistently across all.

Last but not least, please ask questions on the [forums](https://discuss.elastic.co) not on the issue tracker.

Thanks.
