### ISSUE TITLE
full body search from Spark

### ISSUE THREAD

**Issue by kyunam** [elastic/elasticsearch-hadoop#466]
I want to do the following in Spark and create a RDD.
How do I do that?

GET bulk_points/point/_search
{
  "size" : 0,
  "fields" : "orig_hex100",
  "aggregations" : {
    "orig_hex100" : {
      "terms" : {
        "field" : "orig_hex100",
        "size" : 200
      },
      "aggregations" : {
        "myvalue" : {
          "value_count" : {
            "field" : "orig_hex100"
          }
        }
      }
    }
  }
}

**Comment by costin** [comment]
You can't currently in an easy way. Aggregations are not yet supported - the plan was to include them in 2.1 but with the update in Elasticsearch 2.0 and the amount of functionality in, it is decided to postpone them for 2.2/2.5 - next release.

For questions, please use the [forums][http://discuss.elastic.co] not the issue tracker.

**Comment by kyunam** [comment]
Thank you!
