### ISSUE TITLE
Aggregation with newAPIHadoopRDD

### ISSUE THREAD

**Issue by nguyenhoan1988** [elastic/elasticsearch-hadoop#483]
Using Spark, I cannot use the aggregation function using `newAPIHadoopRDD`.
The error log I received is:

```
15/06/24 12:55:17 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 192.168.1.101): org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: SearchPhaseExecutionException[Failed to execute phase [init_sca
n], all shards failed; shardFailures {[eoaHJS_7T42_eE7WXXubWw][ranking_tweets][0]: ElasticsearchIllegalArgumentException[aggregations are not supported with search_type=scan]}]
```

Inside the file (https://github.com/elastic/elasticsearch-hadoop/blob/0654cd6db26843739673d3394ff653645a35c569/mr/src/main/java/org/elasticsearch/hadoop/rest/QueryBuilder.java) in line **115** of the function `assemble`, it has been set manually the **search_type** to **scan**, therefore, ElasticSearch cannot do any aggregations:

``` java
private String assemble() {
        StringBuilder sb = new StringBuilder();
        sb.append(StringUtils.encodePath(resource.index()));
        sb.append("/");
        sb.append(StringUtils.encodePath(resource.type()));
        sb.append("/_search?");

        // override infrastructure params
        uriParams.put("search_type", "scan");
        ...
```

**Comment by costin** [comment]
@nguyenhoan1988 That is correct. Aggregations will be fully supported in the upcoming version.

**Comment by nguyenhoan1988** [comment]
@costin thank you for your answer, do you happen to know when will it be released?

**Comment by jaysonminard** [comment]
+1

**Comment by costin** [comment]
Not too long in the future. I'm hesitant in providing an actual date however that will become clear as the milestones appear.

**Comment by larghir** [comment]
+1

**Comment by JihanZhuang** [comment]
I also want to know that when will it be released?

**Comment by jbaiera** [comment]
Duplicate of #276
