### ISSUE TITLE
CLOSE_WAIT with hdfs repository plugin

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-hadoop#492]
_From @JasonBian on July 1, 2015 10:44_

when I use hdfs-repository plugin to create snapshot,there is a issue: Cannot assign requested address, there are too many CLOSE_WAIT

_Copied from original issue: elastic/elasticsearch#11971_

**Comment by costin** [comment]
@JasonBian Unfortunately there's no much we can do. The latest repository-hdfs (2.1.0) is more aggressive in closing the underlying HDFS `FileSystem` which in turn leaks the TCP connections that you see in the first place.

See #220 for more background info.

**Comment by costin** [comment]
Closing the issue...

**Comment by JasonBian** [comment]
thanks，I have changed the source code of the plugin and compiled it to fix the issue 发自网易邮箱大师
            在2015年10月29日 20:04，Costin Leau 写道:Closed #492.

**Comment by costin** [comment]
@JasonBian Is there a specific fix that you have applied? If it's part of the project you can simply download it as it is being deployed in maven with each release.
