### ISSUE TITLE
sc.esRDD(...) how to specific ElasticSearch IP address?

### ISSUE THREAD

**Issue by ningjun** [elastic/elasticsearch-hadoop#496]
I need to create an RDD from an ElasticSearch index as follow
sc: SparkContext
sc.esRDD("myindex/mytype")

This only talk to ElasticSearch instance at localhost:9300. How can I change it to talk to a different ElasticSearch instance with IP 10.121.68.102 and port 9400?

By the way, is there a discussion forum for asking questions regarding Spark/ElasticSearch integration?

**Comment by gracen** [comment]
https://discuss.elastic.co

and this is how you do it in java

sc.set("es.nodes", "<Host>");
sc.set("es.port", "<PORT>");

**Comment by costin** [comment]
@ningjun It is mentioned in the reference [documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-native-cfg). 
As for discuss.elastic.co it was already mentioned.

Out of curiosity, how did you find out about Elasticsearch Spark ? Both these resources are mentioned in Github and the homepage and I'd like to understand how to better advertise them.

Thanks,

**Comment by ningjun** [comment]
Our architect heard about Soark/ElasticSearch integration in the Spark Summit conference and then decide to try it out.

Ningjun
