### ISSUE TITLE
Does ES Hadoop support the Hadoop MultipleOutput feature?

### ISSUE THREAD

**Issue by johnsonlarryl** [elastic/elasticsearch-hadoop#498]
I am trying to use ES Hadoop in my Reduce function where I want to post the Map/Reduce results to Elastic Search.  I thought the way to accomplish this was using the MultipleOutputs feature of Hadoop where I can have multiple destinations to write my desired output.  However, when I add an ESOutputFormat to the "multiple output" setting it seems like ES Hadoop totally ignores this setting.  Is this feature available in ES Hadoop or is there another way to accomplish the aforementioned task?  

Below is a snippet of the configuration in my driver class of my Map/Reduce program.

MultipleOutputs.addNameOutput(job, "eshadoop", EsOutputFormat.class, Text.class, MapWritable.class);

**Comment by costin** [comment]
I've never tried it so I can't comment on what is going on; not sure whether it's `MultipleOutputs` or ES-Hadoop that does the ignoring.
Do note that ES-Hadoop does provide its own simpler, compatible across Hadoop 1 and 2 `MultipleOutput` class (part of `org.elasticsearch.hadoop.mr` package):

```
    MultiOutputFormat.addOutputFormat(conf, EsOutputFormat.class);
    MultiOutputFormat.addOutputFormat(conf, PrintStreamOutputFormat.class);
    // using the new MR API
    conf.setClass("mapreduce.outputformat.class", MultiOutputFormat.class, OutputFormat.class);
    // using the old MR API
   conf.setClass("mapred.output.format.class", MultiOutputFormat.class, OutputFormat.class);
```

Hope this helps,

**Comment by jbaiera** [comment]
Closing this as there doesn't seem to be anything actionable here.
