### ISSUE TITLE
Apply refresh after indexing only once per job

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#502]
Currently each task can issue a refresh after it has completed its bulk. This has the downside of causing too many (non-useful) refreshes _per task_ which becomes counter productive. 
This process should be improved to be one per job not per task so that only one occurs at the end of the job.

**Comment by jbaiera** [comment]
Some added information here: Refreshing an index requires administrative permissions on the index when security is enabled, which is not always something that users have configured for their jobs. On top of that, the support for doing this in technologies like MR and Hive where we don't fully wrap the execution of the job (like in the case of Spark) seems to be a big blocker for implementing this. Adding the stalled label.

**Comment by jbaiera** [comment]
Closing this as sufficient API hooks to execute a finalizing step for a whole job are lacking for the current Hadoop system. We can revisit this on a per-integration basis if the opportunity presents itself.
