### ISSUE TITLE
Allow a higher number of partitions with an RDD

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#528]
When dealing with large number of documents, Spark tasks can be overwelmed by the number of documents within a shard. 
While one can re-partition the shards, it would be convenient to allow this have this built-in resulting in "fake" partitions that basically slice the shards into smaller bits that should be easier for Spark to digest.

**Comment by mavencode01** [comment]
:+1:

**Comment by larghir** [comment]
+1

**Comment by jeremysanecki** [comment]
+1

**Comment by zhuge19881117** [comment]
+1

**Comment by costin** [comment]
This requires some support from ES which is tracked through #778

**Comment by jbaiera** [comment]
Now with the delivery of sliced scrolls in ES 5.0 and ES-Hadoop 5.0 (#812), I will be closing this.
