### ISSUE TITLE
build issue with Gradle 2.5

### ISSUE THREAD

**Issue by NihalBhagchandani** [elastic/elasticsearch-hadoop#531]
I tried following to try elastic-hadoop in my eclipse project
1. git clone https://github.com/elastic/elasticsearch-hadoop.git
2. install gradle
3. run command gradle build also tried gradle eclipse

**encountered the following error:**
````
Using Apache Hadoop Stable [1.2.1]
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-hadoop-cascading:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-hadoop-hive:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-hadoop-mr:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-hadoop-pig:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-repository-hdfs:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-spark:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-spark-1.2:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-storm:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle': line 210
Changed strategy of configuration ':elasticsearch-yarn:provided' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0

FAILURE: Build failed with an exception.

* Where:
Build file '/home/nihal/projects/elasticsearch-hadoop/build.gradle' line: 334

* What went wrong:
A problem occurred evaluating root project 'elasticsearch-hadoop'.
> Cannot change dependencies of configuration ':elasticsearch-hadoop-mr:provided' after it has been resolved.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.404 secs

````

gradle --version
````
------------------------------------------------------------
Gradle 2.5
------------------------------------------------------------

Build time:   2015-07-08 07:38:37 UTC
Build number: none
Revision:     093765bccd3ee722ed5310583e5ed140688a8c2b

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.16.0-30-generic amd64

````

**Comment by costin** [comment]
The project relies on Gradle 1.12; see the readme use the provided `gradlew` if you have another version installed.

As a side note there's a issue to upgrade to Gradle 2.x for which the solution should hit the answer master fairly soon.

**Comment by costin** [comment]
Master has been upgraded to Gradle 2.6. I would however recommend waiting a bit until the build stabilizes with respect to ES 2.0 Master.

**Comment by hardik-pandya** [comment]
I went one step further and added all required dependencies 

and I got following error building jar (with dependencies)

* What went wrong:
Could not expand ZIP '/Users/username/.gradle/caches/modules-2/files-2.1/org.apache.storm/storm-core/0.9.5/d2bf27db853347dcf66990b4514db20a7897303e/storm-core-0.9.5.jar'.
> Could not copy zip entry /Users/username/.gradle/caches/modules-2/files-2.1/org.apache.storm/storm-core/0.9.5/d2bf27db853347dcf66990b4514db20a7897303e/storm-core-0.9.5.jar!META-INF/license/LICENSE.base64.txt to '/Users/username/project_dir/build/tmp/expandedArchives/storm-core-0.9.5.jar_b0z1uqporrtpdwe5yg2cmslz/META-INF/license/LICENSE.base64.txt'.

repositories{
    mavenCentral()
    mavenLocal()
    maven { url "http://conjars.org/repo" }
   //  storm dependencies
   maven { url "http://clojars.org/repo" }
   /maven { url 'http://repo.spring.io/plugins-release' }

    // Hive depends on JDO ec2 missing from Maven Central
    maven { url "http://www.datanucleus.org/downloads/maven2" }
    maven { url "http://oss.sonatype.org/content/groups/public/" }
}
dependencies {
  compile "org.elasticsearch:elasticsearch-hadoop:2.1.1"
}

Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.10.3 x86_64

**Comment by costin** [comment]
@hardik-pandya If you encounter a problem, open a new issue don't comment on a closed one (you can potentially link it).
Not sure what you mean by adding dependencies - the project already contains all the required dependencies and it is built nighlty.
