### ISSUE TITLE
Writing data into elastic search through hive partition

### ISSUE THREAD

**Issue by anand248** [elastic/elasticsearch-hadoop#532]
Hello,

I have two tables
1) external table which is partition table 
2)second table is storing data in to elastic search

First i am copying my data from first table to second table which is also partitioned inorder to  get copy.
When i submit insert into query it copies data in to second table,it shows in logs but when i do select * frm second table result is 0.
When i remove elastic search connectivity prop from second table and do above steps, i can able to see data in second table

Any one help me with the issue...

**Comment by costin** [comment]
Sorry but I'm not following. Can you please use the [forums](discuss.elastic.co) to discuss your problem at length and if it is indeed a bug, update this issue?
Some code samples and logs would definitely help.

Cheers,

**Comment by costin** [comment]
As there hasn't bee any follow-up, I'm closing the issue.
