### ISSUE TITLE
Clarify compress option in configuration properties

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-hadoop#535]
The description (https://github.com/elastic/elasticsearch-hadoop/tree/master/repository-hdfs#configuration-properties) of the compress option suggests that there is compression of data snapshoted to HDFS.  I think we mean to say whether to compress the metadata files (eg. index settings/mappings), not the data itself.

    compress: "false"               # optional - whether to compress the data or not (default)

>repositories
  hdfs:
    uri: "hdfs://<host>:<port>/"    # optional - Hadoop file-system URI
    path: "some/path"               # required - path with the file-system where data is stored/loaded
    load_defaults: "true"           # optional - whether to load the default Hadoop configuration (default) or not
    conf_location: "extra-cfg.xml"  # optional - Hadoop configuration XML to be loaded (use commas for multi values)
    conf.<key> : "<value>"          # optional - 'inlined' key=value added to the Hadoop configuration
    concurrent_streams: 5           # optional - the number of concurrent streams (defaults to 5)
    compress: "false"               # optional - whether to compress the data or not (default)
    chunk_size: "10mb"              # optional - chunk size (disabled by default)

**Comment by costin** [comment]
Fixed - cheers for the report!
