### ISSUE TITLE
Check for getIndexAutoCreate on initSingleIndex

### ISSUE THREAD

**Issue by kjelle** [elastic/elasticsearch-hadoop#536]
Hello.

I'm running tag v2.1.0.rc1 with ES v1.7.1 from Storm using Hortonworks HDP 2.2.

I have an alias (storm-today) for my index (storm-2015-08-18) and I want to use storm-today as the resource in my EsBolt(..). Elasticsearch casts an InvalidIndexNameException "Invalid index name [storm-today], already exists as alias" and as far as I can see I have no way (without changing the code) to stop this.

The problem seems to be in, or around, RestService - which forces a call to repository.touch() in line 406 without checking for getIndexAutoCreate (which I set to "no" / "false").

**Comment by costin** [comment]
Why are using 2.1.0.rc1 instead of the GA? This has been fixed in 2.1.0
https://github.com/elastic/elasticsearch-hadoop/commit/dece07a5400e200f68d0823c0804bba4a917687d

A simple upgrade should fix this issue

**Comment by kjelle** [comment]
It sure does. Sorry for not noticing. Thanks.
