### ISSUE TITLE
Support script id/file/inline options

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#538]
Scripting has added new options such as `id`, `file` or `inline`. This should be supported as well by the connector.

**Comment by costin** [comment]
Also include the new options such as `detect_noop`, `scripted_as_upsert`, etc...

**Comment by costin** [comment]
related #553

**Comment by Weizilla** [comment]
@costin Is the [Scripted Upsert](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#scripted_upsert) feature supported? I found a [discussion](https://discuss.elastic.co/t/hadoop-elasticsearch-upsert-not-working-using-scripted-upsert/44600) about it referring to this PR but there's no mention of it on the [official configuration page](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html).

**Comment by jbaiera** [comment]
@Weizilla This issue is very old. I would recommend against resurrecting old closed issues, especially with direct mentions to contributors. Much better to start a forum post or open a new issue.

Scripted Upsert is unfortunately not supported at the moment, but I don't think it would be so hard to add. Feel free to open a new issue for that. PR's are also very welcome. I believe that would be a pretty easy setting to add.

**Comment by Weizilla** [comment]
@jbaiera Sorry about that, I figured it was better to reference existing issues than make duplicates.

I found a PR that's similar https://github.com/elastic/elasticsearch-hadoop/pull/1080 but you talked about `This will need to work for frameworks other than Spark.`. Could you elaborate on that? Frameworks in this context means Map/Reduce, Hive, etc?

**Comment by jbaiera** [comment]
That specific PR was opened in an incomplete state and doesn't look like it ever was revisited. In terms of PRs working for frameworks other than Spark, yes, you are correct. Changes to the core packages must be compatible with all integrations, and new features in those core packages are encouraged to be added in a way that they can be used by all integrations as well.
