### ISSUE TITLE
Change field index to not analyzed

### ISSUE THREAD

**Issue by chiragvaya** [elastic/elasticsearch-hadoop#539]
Hi

I am indexing data to ES through hive by using the query :

CREATE EXTERNAL TABLE json2 ( time_id_1 STRING, acnt_nm) STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = 'es_testing/test', 'es.nodes' = 'xxx');

 insert overwrite table json2 select time_id_1 , acnt_nm from table_x; 

I want my string column acnt_nm to be "not analyzed".
I found out there is a way of doing this through Mapping API by setting the "index": "not_analyzed"

I know this can be done through explicit mapping. But that is very cumbersome as i will have to do that every time before indexing any new data.
But can i do the same through the hive external table creation command ?

**Comment by costin** [comment]
For questions please use the [forum](discuss.elastic.co) not the issue tracker.

And no, such a feature is not supported in the connector for several reasons, the main one being there is no clear hook that can be used across integrations for declaring the mapping. Considering that the mapping is typically a one-time thing, doing it outside the connector is not too difficult and actually recommended.
