### ISSUE TITLE
Incomplete source jar

### ISSUE THREAD

**Issue by lemieud** [elastic/elasticsearch-hadoop#542]
The source jar in maven is incomplete.
http://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-spark_2.10/2.2.0-m1/elasticsearch-spark_2.10-2.2.0-m1-sources.jar

It does not contain most of the spark-sql classes.
```
$ unzip -l ~/Downloads/elasticsearch-spark_2.10-2.2.0-m1-sources.jar | grep sql
        0  08-27-15 19:23   org/elasticsearch/spark/sql/
     1660  06-20-15 10:57   org/elasticsearch/spark/sql/Utils.java
        0  05-01-15 01:09   org/elasticsearch/spark/sql/api/
        0  08-27-15 11:30   org/elasticsearch/spark/sql/api/java/
       99  05-01-15 01:09   org/elasticsearch/spark/sql/api/java/package-info.java
```

**Comment by costin** [comment]
Ooops. Thanks for reporting - looks like only the java sources were included.
Should be fixed now.
