### ISSUE TITLE
Problem in setting the id---in mapreduce with elasticsearch

### ISSUE THREAD

**Issue by raghuprodhutoori** [elastic/elasticsearch-hadoop#548]
I have written a mapreduce code which writes the account id followed by values(hashtable of <string,boolean>) to context...now i want to write this data to elastic search... i have set the type and index but i am facing a hardtime in setting the accountid from mapper as id for elastic search in conf.set("es.mapping.id"," ???")....because the id is in mapper and we will be setting this property in driver...any ideas for setting id in this case...?

**Comment by costin** [comment]
@raghuprodhutoori This looks like a question which can be clarified through a discussion not a bug.
Please use the [forum](discuss.elastic.co) along with some code sample - it is unclear what you mean by "the id is in mapper and we will be setting...".

Thank you
