### ISSUE TITLE
Multi search query with spark

### ISSUE THREAD

**Issue by tuan3w** [elastic/elasticsearch-hadoop#549]
Hi all!
I want to scan documents that match for a list of queries.I know that elasticsearch support endpoint _msearch to make multi search query, but I don't know to set up this type of query for spark intergration case (https://www.elastic.co/guide/en/elasticsearch/hadoop/master/spark.html). 
The second question is that can you give some advices on chosing number of queries in a multi query (I only concern on the cases when my query type is search or scan).
Thanks!

**Comment by costin** [comment]
For questions and discussions, please use the [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop). The issue tracker is reserved for bug reports, code improvements, etc...

Thanks.
