### ISSUE TITLE
Upgrade dependency on jackson

### ISSUE THREAD

**Issue by yasserg** [elastic/elasticsearch-hadoop#554]
The current dependency on org.codehaus.jackson is very old and causes conflicts in projects that are using new jackson versions.

I can prepare a PR to update this.

**Comment by costin** [comment]
The jackson dependency is based on the version in various Hadoop distributions. If your runtime has a newer version that is incompatible with the new one, let me know below.

**Comment by costin** [comment]
As there hasn't been any update on this, I'm closing the issue. Feel free to open a new one if needed.
