### ISSUE TITLE
Run time error with Spark 1.5

### ISSUE THREAD

**Issue by mlieber** [elastic/elasticsearch-hadoop#558]
After compiling with Spark 1.5 / Scala 2.10.4, at run time i get:

Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:52)

Any idea what is causing this ? 
thanks - 
Matt

**Comment by costin** [comment]
Looks like it might be an issue with your runtime environment; master is
compiled and running its nightly builds against Spark 1.5

**Comment by costin** [comment]
@mlieber  any update on this issue?

**Comment by mlieber** [comment]
Yes, sorry -
You were right - i was compiling, and running, with 2 different spark
versions. I changed my sbt config and everything started to work fine.
thanks -

**Comment by costin** [comment]
Glad to hear things got resolved.
