### ISSUE TITLE
ES Newbie

### ISSUE THREAD

**Issue by afdebbas** [elastic/elasticsearch-hadoop#561]
Hello

I am new in this technology and I am kind of lost. I have downloaded Hadoop VMs from cloudera and hortonworks and i want to be able to write\read data from\into any of them.

I have downloaded this project (elasticsearch-hadoop) in hopes of advancing forward in this project but I am still lost. 

I should import these jar files i have downloaded into a project in Eclipse and use them to develop code that would read\write into the hadoop VMs i have downloaded?

Can anyone clarify this picture for me as it feels like I'm driving through a fog.

Thanks

**Comment by costin** [comment]
Your question is kind of vague and generic. 
I recommend you start with the main [project page](https://www.elastic.co/products/hadoop) and take it from there. There is a reference documentation which goes at length to explain what this project is about plus webinars and recorded talks.
Note in all cases basic knowledge about Hadoop and Elasticsearch is expected - if that's not the case I recommend spending some time getting familiar with them.
It might seem overwhelming at first but with a bit of time and patience things become clearer.

Further more for questions there's a [dedicated forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop).
This is an issue tracker for bugs and improvements - hence why I'm closing this issue.

Hope this helps,
