### ISSUE TITLE
No data node with id found

### ISSUE THREAD

**Issue by larghir** [elastic/elasticsearch-hadoop#563]
Hi, 
I'm getting this error when trying to connect to a remote ES host:

org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: ElasticsearchIllegalArgumentException[No data node with id[...] found

Same configuration for localhost works without problems.
- Am using version 2.2.0-m1
- ES version 1.7.1
- Node is reachable via HTTP

Any hints appreciated

**Comment by costin** [comment]
Can you provide more information about the setup? The exception occurs if the data node is detected during discovery but the connector cannot reach it - maybe the IP is incorrect (private vs public) - typically occurs in cloud environments.

**Comment by larghir** [comment]
Reverted to version 2.1.1 and it works.

**Comment by costin** [comment]
Okay. Can you please enable logging in 2.2.0-m1 on the [rest package](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/logging.html) and post the log as gist? It would be useful to understand what is going on?

Thanks,

**Comment by larghir** [comment]
https://gist.github.com/larghir/a755add6f42e41f1a857

**Comment by costin** [comment]
Unfortunately there's no relevant information - the rest package should be set on TRACE level to see the actual replies from the cluster (and thus why the data node is not found in 2.2.m1 vs 2.1.1).

**Comment by larghir** [comment]
I can't read anything from trace logs either but there it is
https://gist.github.com/larghir/e718e8839a13aa03c580

**Comment by larghir** [comment]
I can't read anything from the trace logs either but there it is 
https://gist.github.com/larghir/c9b43279222641d60f9f

**Comment by costin** [comment]
Thanks - that's much better. Looks like there's an error in the generated QueryDSL.
I'll keep you posted.

P.S. Thanks for your patience in getting the logs.

**Comment by larghir** [comment]
:) Sure. Thanks also

**Comment by costin** [comment]
By the way, would you please post a gist with the logs from es-connector 2.1.1? Thanks!

**Comment by larghir** [comment]
https://gist.github.com/larghir/3bf522f132dfb8c2da79

**Comment by larghir** [comment]
https://gist.github.com/larghir/b726d6b912df35ce1a15

**Comment by costin** [comment]
@larghir Something's a miss. Would you mind turning `TRACE` on the entire `org.elasticsearch.hadoop` and `org.elasticsearch.spark` packages and upload the logs as a gist again?
If possible, can you please join the [#elasticsearch IRC channel](https://www.elastic.co/community) - I'm using the same user as on github.

It looks like you are running ES both locally and on a remote cluster and for some reason, the connector falls back to the local cluster which clearly doesn't have the same node as the remote one.

**Comment by larghir** [comment]
Hi again, don't seem to find you on the IRC channel. Indeed I am using two ES configurations for two ES clusters, one of them is local. I will try to get the logs soon (I assume you want those from 2.2.0-m1)

**Comment by costin** [comment]
Are you sure you are using the proper #elasticsearch channel on freenode? I'm there 24/7 (current stat is 7h due to a network hiccup).
I'll be afk for a short while but should be back in a matter of hours max.

**Comment by costin** [comment]
@larghir Any update?

**Comment by larghir** [comment]
Sorry for the delay. What I have noticed is that when I set the es configuration (es.nodes, es.port) on the sparkContext (as advised in the docu), then it apparently falls back to the wrong node (producing the above error). However, if I give the es configuration to the EsSpark.esRDD method as last parameter, everything seems to be fine. Again, this is the case for version 2.2.0-m1.

**Comment by costin** [comment]
Fixed through #591
