### ISSUE TITLE
Number of partitions in RDD

### ISSUE THREAD

**Issue by mavencode01** [elastic/elasticsearch-hadoop#564]
Specify how the number of partitions is set in the documentation. Currently, this is the same as as the number of shards. Future release might offer a way to achieve this reliably #528

**Comment by costin** [comment]
Not sure what you are asking. The relationship between shards and tasks/partitions is [explained](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/arch.html) in the docs

**Comment by jbaiera** [comment]
Closing this as it does not have any actionable items.
