### ISSUE TITLE
es.mapping.id populates wrong value

### ISSUE THREAD

**Issue by n0rb3rt** [elastic/elasticsearch-hadoop#581]
Using Spark 1.5.1 and elasticsearch-spark 2.1.1 I'm setting the es.mapping.id to a field in my JSON called "feature_id".  IDs are getting populated, but they don't match the value of the "feature_id" field in the document.

```
EsSpark.saveJsonToEs(
  rdd.map(_.toJson),
  "myindex/features",
  Map(
    "es.nodes" -> "myhost.com",
    "es.mapping.id" -> "feature_id"
  )
)
```
```
{
  "_index": "myindex",
  "_type": "features",
  "_id": "144136021837088505",
  "_score": 1,
  "_source": {
    "feature_id": 144136021837088500,
    ...
  }
}
```

**Comment by costin** [comment]
Can you please post a sample doc? Is there another `feature_id` inside the document? Does it contain by any chance another 144136021837088500 - or is this number somewhere in an another document?
It looks like a bug but I'm trying to narrow down where do these numbers are coming from and thus what causes the bug to occur.

**Comment by n0rb3rt** [comment]
Actually I think this is a false alarm.  I think the problem is my (Javascript) client incorrectly munging the Long value of feature_id.  When I do it with curl everything looks good.

**Comment by costin** [comment]
@n0rb3rt Thanks for the update. Cheers!
