### ISSUE TITLE
es hadoop query all type

### ISSUE THREAD

**Issue by adol001** [elastic/elasticsearch-hadoop#583]
it seems it must be point a index type follow index name, even if you can use multi type for search like this（https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-multi-index-type） in es hadoop

For example："table/partition" is a good resource for esRdd to read，but only "table" can't satisfy the format (Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid resource given; expecting [index]/[type] - received table)

**Comment by costin** [comment]
Sorry I'm not following. Can you explain what index/type are you trying to use and it's not working?

Thanks,

**Comment by adol001** [comment]
I have a index named "error_info7" with a type named "20150104", if I run spark code 
sc.esRDD("error_info7/20150104,20150105", q)
is ok
But I run 
sc.esRDD("error_info7", q)
it will return error message
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid resource given; expecting [index]/[type] - received error_info7

How can I query all type in an index with es-hadoop?

**Comment by costin** [comment]
`error_info7/_all` ?

**Comment by adol001** [comment]
It doesn't work. According to official document, you can use _all to replace index for cross multi index query, but I find nothing about all type placeholder 

Using es-hadoop 2.2.0-m1

**Comment by costin** [comment]
@adol001 thanks. I'll look into it and report back.

**Comment by costin** [comment]
I've pushed a fix in master that allows the resource to be skipped. Note that this will only work for reading and when the schema is likely the same across types.
