### ISSUE TITLE
Missing 2.1.2 release

### ISSUE THREAD

**Issue by sjoerdmulder** [elastic/elasticsearch-hadoop#584]
On the frontpage it mentions the 2.1.2 release but i don't see it in Maven or the Release section.

**Comment by costin** [comment]
@sjoerdmulder Yeah, the commit went through a few hours in advanced. It will be released today but not quite yet. I have updated the page accordingly

**Comment by sjoerdmulder** [comment]
Ahhh i was too fast / eager :)
