### ISSUE TITLE
Getting PermGen space issues when building latest master

### ISSUE THREAD

**Issue by koertkuipers** [elastic/elasticsearch-hadoop#596]
with master at d2053a60681d2d3e66fb82283b3708b27e2b9168

$ ./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':elasticsearch-spark-1.2:compileScala'.
> PermGen space

Could this be an issue that is specific to my local environment?

**Comment by costin** [comment]
Looks like you are using Java 7 in which case yes, you need to increase the PermGen since the scala compiler runs inside the Gradle JVM (it is not forked).
The quick solution is to use Java 8 (recommended as it adds several improvements including on the security side) and gets rid of PermGen.
Going forward, there are some improvements in Gradle 2.8 that hopefully will eliminate this issue, at least in master/2.2.

**Comment by koertkuipers** [comment]
yes i am using java 7

this worked for me:

-        maxHeapSize = "768m"
+        maxHeapSize = "1024m"
         if (!java8)
-            jvmArgs '-XX:MaxPermSize=368m'
+            jvmArgs '-XX:MaxPermSize=512m'

**Comment by costin** [comment]
Strange. Compiling the project with gradlew works fine on my end and on the CI - at least PermSize doesn't seem to be a problem.

**Comment by costin** [comment]
I've increased the PermSize to 496m which should be more then enough. Again it's strange that on the CI and on my machine the build works fine with both `gradle` and `gradlew` but not in your case. Are you using some kind of instrumentation or agents in your JVM? Something is eating that PermGen but it's unclear what.

**Comment by koertkuipers** [comment]
not that i am aware of... just plain oracle jdk 1.7.0_75

anyhow, thanks!

**Comment by koertkuipers** [comment]
i just noticed when building elasticsearch-hadoop 2.2.0-rc1 today that i had permgen issues again. but it is not with test but instead with scalac. so changing the parameters mentioned before did not solve anything.
i fixed it for myself by doing:
$ export JAVA_OPTS="-Xmx1024M -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512M"
