### ISSUE TITLE
ES-HADOOP and ES V2?

### ISSUE THREAD

**Issue by BobNovas** [elastic/elasticsearch-hadoop#597]
org.elasticsearch.hadoop.rest.InitializationUtils.java, line 171, checks that the ES version  it's running against starts with "0.90" or "1.".  That kinda rules out V2.

**Comment by costin** [comment]
That's because ES 2 is not fully compatible with ES 1 from the rest point. For ES 2.x use ES-Hadoop 2.2 (currently in beta1) which is compatible with both ES 1.x and 2.x

**Comment by costin** [comment]
The docs have been updated to better indicate the version requirements in both 2.x and master.
