### ISSUE TITLE
[DOCS] Possible typo Apache Spark vs. Apache Storm

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-hadoop#600]
_From @lukas-vlcek on November 2, 2015 15:41_

May be it is just a typo, but why the first paragraph here refers to Apache Spark while it is inside Apache Storm part?
https://www.elastic.co/guide/en/elasticsearch/hadoop/current/requirements.html#requirements-storm

_Copied from original issue: elastic/elasticsearch#14439_

**Comment by clintongormley** [comment]
_From @girirajsharma on November 2, 2015 16:39_

The following PR https://github.com/elastic/elasticsearch-hadoop/pull/588 fixes above issue.

**Comment by costin** [comment]
Thanks - merged the PR (#588) in master and 2.x
