### ISSUE TITLE
installation instruction does not work

### ISSUE THREAD

**Issue by leojli** [elastic/elasticsearch-hadoop#609]
Hey,

I tried this command and did not work:
bin/plugin -i elasticsearch/elasticsearch-repository-hdfs/2.2.0-beta2

Then I tried another one:
sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-repository-hdfs/2.2.0-beta2
-> Installing elasticsearch/elasticsearch-repository-hdfs/2.2.0-beta2...
Trying https://download.elastic.co/elasticsearch/elasticsearch-repository-hdfs/elasticsearch-repository-hdfs-2.2.0-beta2.zip ...
Trying https://search.maven.org/remotecontent?filepath=elasticsearch/elasticsearch-repository-hdfs/2.2.0-beta2/elasticsearch-repository-hdfs-2.2.0-beta2.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/elasticsearch/elasticsearch-repository-hdfs/2.2.0-beta2/elasticsearch-repository-hdfs-2.2.0-beta2.zip ...
Trying https://github.com/elasticsearch/elasticsearch-repository-hdfs/archive/2.2.0-beta2.zip ...
Trying https://github.com/elasticsearch/elasticsearch-repository-hdfs/archive/master.zip ...

Thanks
Leo

**Comment by costin** [comment]
Thanks. Updated the README accordingly
