### ISSUE TITLE
repository-hdfs: elasticsearch 2.1.0 support

### ISSUE THREAD

**Issue by moliware** [elastic/elasticsearch-hadoop#620]
It seems that elasticsearch 2.1.0 is not supported (although the readme says that versions 2.0 or higher are supported)

I tried to install the latest version (2.2.0-beta1) but it wasn't possible. I tried to compile the project locally for 2.1.0 but it doesn't compile because [BlobContainer interface has changed](https://github.com/elastic/elasticsearch/pull/13434)

**Comment by costin** [comment]
Have you actually tried running es-hadoop against ES 2.1? Or are you interested in repository hdfs?

**Comment by moliware** [comment]
No, I haven't. I'm interested only in the plugin (I'm basically doing daily snapshots of my indices to hdfs)

**Comment by costin** [comment]
I see. I'll work on updating it as well to ES 2.1 and ping you once it's done. Sorry for the inconvenience.

**Comment by moliware** [comment]
Thanks :D

**Comment by costin** [comment]
Pushed the fix in master and published the artifacts. Can you please try `2.2.0.BUILD-SNAPSHOT`?

**Comment by moliware** [comment]
Tried and it worked :) Thanks!
