### ISSUE TITLE
Release of elasticsearch-repository-hdfs plugin for 2.1.0 elastic version

### ISSUE THREAD

**Issue by awislowski** [elastic/elasticsearch-hadoop#621]
Could you prepare release of elasticsearch-repository-hdfs plugin for 2.1.0 elastic version?

Now I only see posibility to install snapshot version for this plugin

**Comment by jramos** [comment]
+1

**Comment by costin** [comment]
Scheduled for 2.2.0-rc1 which should be out shortly
