### ISSUE TITLE
IP Address badly parsed in org.elasticsearch.hadoop.serialization.dto.Node

### ISSUE THREAD

**Issue by srakonjac-bb** [elastic/elasticsearch-hadoop#630]
Hello,

There's a bug in class `org.elasticsearch.hadoop.serialization.dto.Node:56` where ipAddress is being parsed as a portion of httpAddr starting from ':'. 

Library version is `elasticsearch-spark_2.11-2.2.0-m1`

Lines 55-57 follow:

```
        int portIndex = httpAddr.indexOf(":");
        ipAddress = httpAddr.substring(portIndex);
        httpPort = Integer.valueOf(httpAddr.substring(portIndex + 1));
```

**Comment by costin** [comment]
Correct however this has been fixed in 2.2.0-beta1. Thanks for reporting!
