### ISSUE TITLE
ES Hadoop with reverse proxy

### ISSUE THREAD

**Issue by pricecarl** [elastic/elasticsearch-hadoop#633]
Hi Costin,

I have ElasticSearch setup hidden behind an Apache web server.

I can access the normal page you see when hitting <hostname>:9200 by going to <hostname>/adminaccess/

But I cant seem to write any data from Hive to this when using the ES-Hadoop connector.

I tried:
    ...
    'es.resource' = 'monitorlogs/event',
    'es.index.auto.create' = 'true',
    'es.nodes' = '<hostname>/adminaccess/',
    'es.field.read.empty.as.null' ='true',
    'es.batch.size.entries' = '10000',
    ...

but no luck. Is ES-Hadoop able to work when ES is behind a proxy? Am I missing a setting?

I have an ES 2.x cluster and am using ES-Hadoop  2.2.0-beta1, any help with this would be gratefully appreciated.

Thanks Carl

**Comment by costin** [comment]
No matter the type of proxy used, one needs to set it up so that ES-Hadoop connections go through the proxy first instead of directly to the target.
The documentation [indicates](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_proxy) the parameters needed.

**Comment by pricecarl** [comment]
#642 will fix this for me, thanks Costin.

**Comment by costin** [comment]
Duplicated by #642
