### ISSUE TITLE
Allow 'prefixed' Elasticsearch installs

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#642]
It's fairly common to host ES under a prefix address - `foobar:123/some/path` instead of always going to the root. While it can be supported by adding an HTTP service for this, having it in the client,makes things significantly simpler.

**Comment by pricecarl** [comment]
Hey Costin,

Thanks for looking into this. Do you have an estimated date when this feature/rc1 will be released/available for testing please?

**Comment by costin** [comment]
Days, 1 week at most. Please watch the issue to be notified in real time of when it happens.

Thanks,

**Comment by pricecarl** [comment]
Excellent, thank you very much.

**Comment by costin** [comment]
@pricecarl Pushed the feature in master; the nightly build is running and will be soon available; please try it out and report how it works for you. Simply set the prefix through `es.nodes.path.prefix` (`/my/custom/path'). The docs also contain this information (but it might take some time before they get refreshed).
