### ISSUE TITLE
Compressed snapshot for backing up and restoring

### ISSUE THREAD

**Issue by weiqiangyuan** [elastic/elasticsearch-hadoop#646]
I have two questions as followed:
We use the hdfs as our elasticsearch repositories to back up and restore.We have alread installed the 'elasticsearch-repository-hdfs' plugin in the elasticsearch data nodes.
1)If the snapshot files in the hdfs were compressed, such as in '.gz' format, can we still use the compressed snapshot to restore?

2) By the way, as mentioned above, we have installed plugins in the data nodes, do we also need to install the 'elasticsearch-repository-hdfs' on the master nodes in order to create snapshot? 

Thank you very much!

**Comment by costin** [comment]
For questions and discussions please use the [forum](http://discuss.elastic.co) and _not_ the bug tracker.

1. No. The output folder needs to be in the same format as it was when the snapshot occurred. In this case this means simply gunziping the files.

2. For consistency, it is best to have the plugin installed across your entire cluster. while the master might not use this plugin, if the node changes behaviour or if somebody tries to access the plugin (in case it's a site one) on the master and it is not there, things might break.
So to keep things simple, best practice is to install the plugin through out your entire cluster.

**Comment by weiqiangyuan** [comment]
Thank you for your answers. As you have said, if the snapshot files in the hdfs were compressed, such as in '.gz' format, we can't use the compressed snapshots to restore.

I have another question: 
As the backup progress is incremental, if the existing snapshots were compressed, can we still continuing backing up new snapshots?

Thank you!
