### ISSUE TITLE
RestService: missing index log message displays wrong setting

### ISSUE THREAD

**Issue by sawyercade** [elastic/elasticsearch-hadoop#656]
In RestService.findPartitions(), if reads/writes are requested on an index that does not exist, `es.index.read.missing.as.empty` is checked to determine whether further action should be allowed. However, when further action is not configured as allowable, the log message displays `Index [index/type] missing and settings [es.field.read.empty.as.null] is set to false`.

The field name displayed in the log message should be `es.index.read.missing.as.empty`, not `es.field.read.empty.as.null`.

**Comment by costin** [comment]
Fixed. Thanks!
