### ISSUE TITLE
Spark-ES Schema problem

### ISSUE THREAD

**Issue by JoaquinSV** [elastic/elasticsearch-hadoop#661]
Hello,
 I'm using the connector with Spark, and I'm trying to read fields that has arrays and Strings, like this:

Field_name
  ["value"]
    value

when I set 
es.field.read.as.array.include = Field_name
It thows me an error that some fields are not arrays, because some of them are String:

Caused by: scala.MatchError: value (of class java.lang.String)

And when I set
es.field.read.as.array.exclude = Field_name
It thows me an error that some fields are not Strings, because some of them are arrays:

Caused by: scala.MatchError: Buffer(["value"]) (of class scala.collection.convert.Wrappers$JListWrapper)

How can I solve this? My goal is to write indexes of ES into parquet or json files using Spark.

Regards

**Comment by costin** [comment]
Can you please format your code? I'm not sure what you mean. What is your json/mapping in ES and what version of ES-Hadoop are you using? 2.2-rc1 only has this functionality.
Additionally, try using the latest [dev build](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) and report back with a snippet of code.

Cheers,

**Comment by JoaquinSV** [comment]
spark: 1.5.2
ES-connector: 2.1

Code:

import org.apache.spark.SparkContext._
import org.apache.spark.SparkContext
import org.apache.spark.SparkConf
import org.elasticsearch.spark._
import org.elasticsearch.spark.sql._
import org.apache.spark.sql.SQLContext 

val options4 = Map("pushdown" -> "true", "es.nodes" -> "10.0.0.17, 10.0.0.14, 10.0.0.15", "es.port" -> "9200","es.field.read.as.array.include" -> "attachments,message","es.field.read.as.array.exclude" -> "action_fields,fired,recipients,untested")

val smg = sqlContext.read.format("org.elasticsearch.spark.sql").options(options4).load("ccu-smg-2016.01.13/smgsyslog")

I'm running it inside the ES cluster, so thats why I use the local ip. 
The fields which I have problems are like this, 
+-------------------------+
| Field_name             |
+-------------------------+
| ["value"]                   |
| value                       |
|             ...                 |
+-------------------------+
they have array and non array rows. So if I set 

es.field.read.as.array.include = Field_name
It throws me an error that some fields are not arrays, because some of them are String:
Caused by: scala.MatchError: value (of class java.lang.String)

And when I set
es.field.read.as.array.exclude = Field_name
It throws me an error that some fields are not Strings, because some of them are arrays
Caused by: scala.MatchError: Buffer(["value"]) (of class scala.collection.convert.Wrappers$JListWrapper)

It works fine when I have fields that have only arrays rows.

I hope that u can now understand the problem.

Regards,

**Comment by costin** [comment]
> 2.2-rc1 only has this functionality.
> Additionally, try using the latest dev build and report back with a snippet of code.

**Comment by costin** [comment]
Since there hasn't been any update I'm closing the issue. Please open a new one if the problem persists.
