### ISSUE TITLE
Compressed snapshot for backing up

### ISSUE THREAD

**Issue by weiqiangyuan** [elastic/elasticsearch-hadoop#662]
As the question in https://github.com/elastic/elasticsearch-hadoop/issues/646:
If the snapshot files in the hdfs were compressed, such as in '.gz' format, we can't use the compressed snapshots to restore.

I have another question: 
As the backup progress is incremental, if the existing snapshots were compressed, can we still continuing backing up new snapshots?
If not, how can we do back up work on conditions that the existing snapshots were compressed?

Thank you!

**Comment by costin** [comment]
@weiqiangyuan Please use the forum for questions, not the issue tracker.
