### ISSUE TITLE
NumberFormatException when reading from ES for no noticable reason

### ISSUE THREAD

**Issue by sebastianmueller** [elastic/elasticsearch-hadoop#663]
Hi,

I'm stuck with an Exception [1] I cannot further track down. I guess some additional information regarding the field causing the exception (as mentioned in #395 for a different Exception/Stacktrace) would be of great help in understanding the problem.

I could find two documents I could directly compare, one causing the Exception [2], one not [3]. The only reason I could think of why parsing some Long values could go wrong is the field **payload.price.price**, which I explicitly mapped as Long [4]. BUT: The examples show that there seems to be no problem with null-values in those fields. When querying the mappings it becomes clear that there are no other Longs in that mapping.

I'm using
elasticsearch-spark_2.10 v2.1.1
with 
es.field.read.empty.as.null=true
es.index.read.missing.as.empty=true

Best regards,
Sebastian

[1] STACK TRACE

    java.lang.NumberFormatException: For input string: "null"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.parseLong(Long.java:483)
        at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:230)
        at scala.collection.immutable.StringOps.toLong(StringOps.scala:31)
        at org.elasticsearch.spark.serialization.ScalaValueReader.parseLong(ScalaValueReader.scala:92)
        at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$longValue$1.apply(ScalaValueReader.scala:91)
        at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$longValue$1.apply(ScalaValueReader.scala:91)
        at org.elasticsearch.spark.serialization.ScalaValueReader.checkNull(ScalaValueReader.scala:70)
        at org.elasticsearch.spark.serialization.ScalaValueReader.longValue(ScalaValueReader.scala:91)
        at org.elasticsearch.spark.serialization.ScalaValueReader.readValue(ScalaValueReader.scala:53)
        at org.elasticsearch.hadoop.serialization.ScrollReader.parseValue(ScrollReader.java:580)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:568)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:636)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:559)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:636)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:559)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:636)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:559)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:358)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:293)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:188)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:167)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:406)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:43)

[2] CAUSING NUMBER FORMAT EXCEPTION

    {
      "_index": "foo",
      "_type": "fooEvent",
      "_id": "AVJDHIbJZthPOJ788cBp",
      "_score": null,
      "_source": {
        "useragent": "Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4",
        "sessionid": "e4a97561-eeee-42de-be73-6ddaa2901e8c",
        "timestamp": "2016-01-01T00:53:08.769+0100",
        "payload": {
          "agent": {
            "id": "foo",
            "email": "foo",
            "name": "foo"
          },
          "price": {
            "price": "55000000",
            "comparablePrice": "55000000",
            "currency": "EUR"
          },
          "linkUrl": "/foo/",
          "userLocationSettings": {
            "language": "it",
            "country": "IT"
          },
          "businessAreaType": "foo",
          "shop": {
            "id": "foo",
            "email": "foo",
            "name": "foo"
          },
          "property": {
            "country": "italy",
            "id": "foo",
            "title": "foo",
            "type": "foo"
          },
          "viewtype": "foo",
          "path": "/foo/",
          "mediaInfo": {
            "virtualTour": "false",
            "floorplans": "0",
            "pictures": "20",
            "siteplans": "0"
          }
        },
        "eventType": "fooEvent"
      },
      "fields": {
        "timestamp": [
          1451605988769
        ]
      },
      "sort": [
        1451605988769
      ]
    }

[3] WORKING

    {
      "_index": "foo",
      "_type": "fooEvent",
      "_id": "AVJDHIbJZthPOJ788cFl",
      "_score": null,
      "_source": {
        "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10",
        "timestamp": "2016-01-01T00:53:57.581+0100",
        "payload": {
          "agent": {
            "id": "bar",
            "email": "bar",
            "name": "bar"
          },
          "price": {
            "price": "null",
            "comparablePrice": "110000000",
            "currency": "EUR"
          },
          "linkUrl": "/bar/",
          "userLocationSettings": {
            "language": "en",
            "country": "DE"
          },
          "businessAreaType": "foo",
          "shop": {
            "id": "bar",
            "email": "bar",
            "name": "bar"
          },
          "property": {
            "country": "spain",
            "id": "bar",
            "exposeeId": "bar",
            "title": "bar",
            "type": "bar"
          },
          "exposeeLanguage": "en",
          "viewtype": "VIEW",
          "path": "/bar/",
          "mediaInfo": {
            "virtualTour": "false",
            "floorplans": "0",
            "pictures": "8",
            "siteplans": "0"
          }
        },
        "eventType": "fooEvent"
      },
      "fields": {
        "timestamp": [
          1451606037581
        ]
      },
      "sort": [
        1451606037581
      ]
    }

[4] MAPPING

    {
      "mappings": {
        "fooEvent": {
          "properties": {
            "payload": {
              "properties": {
                "price": {
                  "properties": {
                    "price": {
                      "type": "long",
    		          "ignore_malformed": "true"
                    },
                    "comparablePrice": {
                      "type": "long",
    		          "ignore_malformed": "true"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

**Comment by costin** [comment]
@sebastianmueller Should be the other way around no? the one with `null` should throw the exception, the one with `5000...` should be working.
Adding diagnostics about what field is wrong should clarify the issue. Let me see if there's something I could do about it so we can revise the issue.
By the way, you can enable logging on the REST and SERIALIZATION packages to pinpoint the problematic document.

**Comment by sebastianmueller** [comment]
@costin Thanks for the lightning-fast response! ;-)

> Should be the other way around no? the one with null should throw the exception, the one with 5000... should be working.

Exactly what I thought - thus I double checked before contacting you...but:

> By the way, you can enable logging on the REST and SERIALIZATION packages to pinpoint the problematic document.

Thanks for the suggestion, I just configured both loggers to TRACE and found (to my very suprise, obviously) that the document being parsed has **payload.price.price**="null" - in opposite to my previous findings.

So: elasticsearch-hadoop does what it has to do when trying to parse that String into a Long value, but:
1) Why is there a String "null" in a field mapped as Long?
2) What do you think of a config flag that allows me to handle parse Exceptions as Null-Values instead of crashing the whole Spark-Job?

**Comment by costin** [comment]
> So: elasticsearch-hadoop does what it has to do when trying to parse that String into a Long value, but:
1) Why is there a String "null" in a field mapped as Long?
2) What do you think of a config flag that allows me to handle parse Exceptions as Null-Values instead of crashing the whole Spark-Job?

This depends on what data came upstream and how it was mapped to. ES can be configured to map missing data to a default value (so for numbers could be 0 or -1); this is much more convenient and powerful than trying to sort this out in the clients.
Exceptions are really fail-fast mechanisms; one can always put in their own custom code to handle custom parsing by implementing the `ValueReader` interface - not something I would recommend though since the aforementioned solution is much better in my opinion.

**Comment by costin** [comment]
@sebastianmueller Pushed a fix in master so in case of an exception, one gets information about the field name (and its value) that caused the exception.

**Comment by sebastianmueller** [comment]
@costin thanks for helping me out!
I'll take your advice and will clean up my indexing soon. For now I need fast results (and can afford dropping some documents) and a simple extension of the ScalaValueParser does the job quite well.

**Comment by costin** [comment]
Closing the issue.

Cheers,
