### ISSUE TITLE
unable to pass DataFrame or RDD to elasticsearch using Spark  !!

### ISSUE THREAD

**Issue by gaurav6351** [elastic/elasticsearch-hadoop#665]
Hi,

I am not able to use "saveToES" function cause when  i open pyspark prompt by passing  bin/pyspark --jars ../elasticsearch-hadoop-2.1.2.jar command .

I am not able to import org.elasticsearch.spark.* module.Can someone guide how to do that in python code using spark and elasticsearch connector

I run the coomand as :   saveToEs(df, "offers/product");

**Comment by costin** [comment]
@gaurav6351 For help and questions, please use the [forum](https://discuss.elastic.co) not the issue tracker.

Thank you,
