### ISSUE TITLE
Configuration Options - field include and field include as array

### ISSUE THREAD

**Issue by ogirardot** [elastic/elasticsearch-hadoop#671]
There seems to be a few things off when looking at the ConfigurationOptions :
https://github.com/elastic/elasticsearch-hadoop/blob/master/mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java#L198
and 
https://github.com/elastic/elasticsearch-hadoop/blob/master/mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java#L201
seems to be the opposite ?
And https://github.com/elastic/elasticsearch-hadoop/blob/master/spark/sql-12/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala#L60 is not using the ConfigurationOptions.

I'd be glad to submit a PR but first I'd like to check if it's supposed to be this complicated ?

Regards, 

Olivier.

**Comment by costin** [comment]
Ooops. Thanks @ogirardot - you are right. Interestingly enough most of the tests were passing due to the usage of constants vs inlined strings.
The SQL-12 module is in the process of being updated - thanks for pointing out this mistake, I'll beef out the test suite further.
