### ISSUE TITLE
When set "es.mapping.date.rich" to false, DataFrame schema not change to String or Long

### ISSUE THREAD

**Issue by arman1371** [elastic/elasticsearch-hadoop#672]
I set "es.mapping.date.rich" to false
My mapping in elasticsearch(version: 2.1.1) is:
```json
"collectionTimestamp" : {
    "type" : "date",
    "format" : "strict_date_optional_time||epoch_millis"
}
```
when i want to read from elasticsearch by this code:
```java
sqlContext.read()
    .format("org.elasticsearch.spark.sql")
    .load("events");
```
i get:
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.sql.Timestamp
```
because my dataframe schema is: 
```
StructField(collectionTimestamp,TimestampType,true)
```

it seems "es.mapping.date.rich" not change the dataFrame schema

**Comment by costin** [comment]
Fixed in master. A [nightly build](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) has been pushed as well. Please try it out.

Thanks,

**Comment by arman1371** [comment]
Fixed.
Thanks
