### ISSUE TITLE
Somehow elasticsearch-spark_2.10 depends on 2.11 version of scala-library

### ISSUE THREAD

**Issue by nfx** [elastic/elasticsearch-hadoop#674]
Strange things happen:

java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
	at org.apache.spark.util.TimeStampedWeakValueHashMap.<init>(TimeStampedWeakValueHashMap.scala:42)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:287)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:61)
	at ....SparkJunitRule$SparkContextWrapper.start(SparkJunitRule.java:...)

mvn dependency:tree shows:
[INFO] +- org.elasticsearch:elasticsearch-spark_2.10:jar:2.2.0-m1:compile
[INFO] |  \- org.scala-lang:scala-library:jar:2.11.7:compile

but generated pom has:

    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.10.4</version>
      <scope>compile</scope>
    </dependency>

what could be wrong and where?

**Comment by nfx** [comment]
Found out that transitive dependency was getting scala-library:2.11

**Comment by costin** [comment]
Make sure to use 2.2.0-rc1 or even better, the dev build. It contains a lot of fixes.

**Comment by nfx** [comment]
@costin is it safe to rely on dev build for production? ;)

**Comment by costin** [comment]
@nfx What version are you using? The Scala 2.11 artifacts should have the right Scala dependency (see for example version 2.2 [here](http://search.maven.org/#artifactdetails|org.elasticsearch|elasticsearch-spark_2.11|2.2.0|jar) ).
