### ISSUE TITLE
Can EsSpark.saveToEs report what doc fail to save to ES 

### ISSUE THREAD

**Issue by ningjun** [elastic/elasticsearch-hadoop#675]
I am using Spark with ElasticSearch. I need to save an RDD of document object to ES as follow
EsSpark.saveToEs(myRDD, "myindex/mytype")

The problem is that if some document fail to save in ES, it throw an exception and stop. I want it to continue to save the rest of documents and at the end report which documents fail to save.

How can I do that?

**Comment by costin** [comment]
You cannot. Mainly because there is no reliable way to report the errors/documents back to the user at the end. There's an issue for this (#613) however still, that implies ignoring the error and moving on which will means controlling the side-effects will be tricky.

**Comment by ningjun** [comment]
I ma thinking of uisng raw elastic4s to save RDD to ES suah as below
myRDD.foreachPartition(iter => {
  try {
    saveDocsUginElastic4s(iter.toSeq) // using elastic4s bulk index call
  }
  catch
    ....
}
Will teh performance be as good as using EsSpark.saveToEs(myRDD, "myindex/mytype")?

**Comment by costin** [comment]
I would advice you to look at the feature set, usage and code reduction of libraries and _then_ at the actual performance differences. The human/developer time is typically much more important than performance itself (which should be fairly small).
Either way there's only one way to find out - to try it out yourself but do know that benchmarks are deceiving.

**Comment by ningjun** [comment]
I have two question
1. How does EsSpark.saveToEs() save RDD to ES? Does it use elastic4s bulk index API to index the items in RDD?
2. If I save the RDD myself using raw elastic4s as above, will it hurt performance when I read the RDD back using sc.esRDD("myindex.mytype")? In another word, Does EsSpark.saveToEs() index the items in any special way to optimize retrieving performance of sc.esRDD("myindex.mytype")?
