### ISSUE TITLE
SIMPLE authentication is not enabled.  Available:[TOKEN]

### ISSUE THREAD

**Issue by rohitvarma1986** [elastic/elasticsearch-hadoop#676]
I used the ElasticSearch Hadoop plugin to save SNAPHOTS in hadoop ( plugin contains hadoop 2.7.1 JAR) whereis the Docker Hadoop configured on remote server is also 2.7.1. Get the following error when I try creating the Repository in Elastic Search

Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): SIMPLE authentication is not enabled.  Available:[TOKEN]

It seems according to the error that on Hadoop server, SIMPLE authentication is not enabled but then I have ready in some docs that SIMPLE authentication is enabled by default.

**Comment by costin** [comment]
This indicates your Hadoop configuration is not properly passed on to the repository HDFS plugin. In short, HDFS hdfs repository should have the same client configuration as any other client (including `hadoop jar` or `hdfs` or `hadoop dfs`).

**Comment by costin** [comment]
Since there hasn't been any update on this issue, I'm closing it down. If the issue still persists, please open a new one (and potentially link this as well).

Cheers
