### ISSUE TITLE
ElasticSearch+Spark in Java: error: package org.elasticsearch.spark.java.api does not exist

### ISSUE THREAD

**Issue by Make42** [elastic/elasticsearch-hadoop#678]
I want to read from ElasticSearch into Spark according to https://www.elastic.co/guide/en/elasticsearch/hadoop/master/spark.html#spark-read-java

however I get the error

    error: package org.elasticsearch.spark.java.api does not exist

and I get it using

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-hadoop</artifactId>
            <version>2.1.2</version>
        </dependency>

or

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-spark_2.10</artifactId>
            <version>2.2.0-rc1</version>
        </dependency>

Am I missing another dependency? Is there no Java support anymore?

**Comment by fmyblack** [comment]
I found the true package is `org.elasticsearch.spark.rdd.api.java`, you can read from open source.

**Comment by costin** [comment]
Fixed now in master. It was a mistake, the correct package is `org.elasticsearch.spark.rdd.api.java`
