### ISSUE TITLE
can only handle one dynamic portion of an index pattern for lowercase validation

### ISSUE THREAD

**Issue by rbraley** [elastic/elasticsearch-hadoop#679]
This commit assumes there will only be one dynamic portion so index patterns like this:
https://github.com/elastic/elasticsearch-hadoop/commit/c1697b68c879955b1f78491f7446a76bbdf507ac

index_{fieldOne}_{fieldTwo}/type

will result in a  org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Invalid index [index_{fieldOne}_{fieldTwo}] - needs to be lowercase

**Comment by costin** [comment]
Fixed in master as a side effect of #684
