### ISSUE TITLE
ElasticSearch Bailing Out

### ISSUE THREAD

**Issue by amajumdarinfa** [elastic/elasticsearch-hadoop#680]
Hi

We are frequently getting the following exception while saving even moderate volume of data to ElasticSearch from a Spark application. We use ElasticSearch 1.4.4; Spark 1.4.1 and Elasticsearch-Hadoop connector version is 2.2.

Our application uses Spark Streaming to continuously receive events and for each event after analyzing it calls saveJsonToES to insert event to the Elasticsearch. When the volume of event increases even a little bit, saving data to ElasticSearch is no longer possible; it throws the following exception.

We tried to increase the retry count and timeout, but that does not solve the issue; it is not a scalable solution anyway. 

- Has anybody found a solution for this?

- Does ES-Hadoop connector sends write requests in batch? Is there any API to buffer and send the requests in batch?

- I saw a suggestion in another thread about reducing number of executors. We have only a few of them.

org.apache.spark.util.TaskCompletionListenerException: Could not write all entries [1/64320] (maybe ES was overloaded?). Bailing out...
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:83)
	at org.apache.spark.scheduler.Task.run(Task.scala:72)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by costin** [comment]
> Has anybody found a solution for this?

> I saw a suggestion in another thread.

@amajumdarinfa This is the issue tracker not the forum, which you can find [here](https://discuss.elastic.co).

> Does ES-Hadoop connector sends write requests in batch?

This and much more is documented in the [reference docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/index.html).
