### ISSUE TITLE
Hadoop Elastic Search 2.2.0 rc1 Issue with Hive 1.2.1

### ISSUE THREAD

**Issue by mullykid** [elastic/elasticsearch-hadoop#683]
Hi,
First time posting here and trying to evaluate Elastic Search & Kabana with HDFS data, initially through Hive queries, in a small  single mode environment.

Hadoop 2.7.1
Hive 1.2.1
ElasticSearch 2.1.1
ElasticSearch Hadoop 2.2.0-rc1

I have hive tables of data that I can query fine. I created a script to execute the following for es testing:

USE default;

DROP TABLE IF EXISTS SRM_ES_ArrayLUN;

CREATE EXTERNAL TABLE SRM_ES_ArrayLUN (
  lun STRING,
  array_sn STRING,
  capacity_gb INT
  )
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES  ('es.resource' = 'idx_srm/arraylun',
		'es.index.auto.create' = 'true',
                'es.field.read.empty.as.null' ='true'
		);

INSERT OVERWRITE TABLE SRM_ES_ArrayLUN
	SELECT lun,
	       array_sn,
               capacity_gb
	FROM SRM_ArrayLUN;

The INSERT command fails with the following:

Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupporte                                                 d/Unknown Elasticsearch version 2.1.1

I put the es hadoop files into HDFS and added the path to the hadoop file in hive-site.xml as follows:

 <property>
    <name>hive.aux.jars.path</name>
    <value>/user/hduser/elasticsearch-hadoop/elasticsearch-hadoop-2.2.0-rc1/dist/elasticsearch-hadoop-2.2.0-rc1.jar</value>
    <description>The location of the plugin jars that contain implementations of user defined functions and serdes.</description>
  </property>
  <property>

Posting this is a last resort, as I have no idea why I am getting unsupported with the correct Jar file. I have gone through all previous posts and I appear to have everything in order. Any help apprecicated! :)

Note: If I add the Jar file locally (into the Hive LIB folder for e.g.) and modifiy the path above I get file does not exists error when executing the script above?? 

Many thanks!!

**Comment by costin** [comment]
You have multiple ES-Hadoop versions in your classpath. Likely they are copied in the Hive/Hadoop `lib` folder and thus take precedence over the ones included in your job.
Make sure you only have _on_ version of ES-Hadoop.

P.S. For questions like these, there's the [forum](https://discuss.elastic.co)

**Comment by mullykid** [comment]
Ah ok, sorry for misplacing the post, 
That may well be the case as I did try and use ES Hadoop 2.1.2 before realising I had the wrong version with ES 2.1. 
In this setup, how would I check/remove the previous Jar from the class path? Note that the JAR file etc. no longer exists locally or in HDFS.
Thanks.

**Comment by costin** [comment]
No worries, thanks for understanding.
Unfortunately Hive/Hadoop don't offer any tools for this. They are java apps themselves so by the time they start, the classpath is already computed.

You basically need to good practice - don't store the libraries under the server folder but rather always embed them into your job. In particular ES-Hadoop is quite small so it shouldn't be an issue.

**Comment by mullykid** [comment]
Ok thanks, so to fix my issue here I will need to re-install Hive due to the invalid/old Jar file in its path?

**Comment by costin** [comment]
No, that would be overkill. Simply check what your classpath is and where you installed ES Hadoop before - remove that jar and you are all set.

**Comment by mullykid** [comment]
Ok, thank you. I thought I had deleted those ES hadoop 2.1 jars but I will double check the class path to see.
