### ISSUE TITLE
Illegal start of declaration

### ISSUE THREAD

**Issue by rsegura** [elastic/elasticsearch-hadoop#688]
Hi,
 I use Spark 1.5 and org.elasticsearch:elasticsearch-spark_2.10:2.2.0-rc1
I try to do something like: 

conf = new SparkConf()
conf.setMaster("local[*]").setAppName("Test").set("es.nodes", "localhost").set("es.query", { "query" : { "term" : { "name" : "luke" } } })

I always obtain <console>:1: error: illegal start of declaration
but I read in stackoverflow this: 
http://stackoverflow.com/questions/25154261/using-elasticsearch-dsl-query-with-hadoop-mapreduce

where is my error?

thanks

**Comment by costin** [comment]
This is the bug tracker not the [forum](https://discuss.elastic.co). Please use the latter for questions, especially when getting started. The [docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/index.html) also help.
