### ISSUE TITLE
Could not index date field with Elasticsearch-hadoop

### ISSUE THREAD

**Issue by haasaif** [elastic/elasticsearch-hadoop#690]
Hi,

I have been trying to add field **start_date** field whose value is **2014-03-12**, but the hive insert query into external table fails with following exception.There is no timezone value in the actual file or hive table, it is coming only when I am inserting from a hive table into elasticsearch external table.

Any help would be appreciated.

> Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Bad Request(400) - [MapperParsingException[failed to parse [**start_date**]]; nested: MapperParsingException[failed to parse date field [**2014-03-12+05:30**], tried both date format [yyyy-MM-dd], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2014-03-12+05:30" is malformed at "+05:30"]; ]]; Bailing out..
> 	at org.elasticsearch.hadoop.rest.RestClient.retryFailedEntries(RestClient.java:203)
> 	at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:167)
> 	at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:209)
> 	at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:232)
> 	at org.elasticsearch.hadoop.rest.RestRepository.close(RestRepository.java:250)
> 	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.doClose(EsOutputFormat.java:214)
> 	at org.elasticsearch.hadoop.hive.EsHiveOutputFormat$EsHiveRecordWriter.close(EsHiveOutputFormat.java:74)
> 	at org.apache.hadoop.hive.ql.exec.FileSinkOperator$FSPaths.closeWriters(FileSinkOperator.java:164)
> 	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.closeOp(FileSinkOperator.java:842)
> 	at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:579)
> 	at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:591)
> 	at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:591)
> 	at org.apache.hadoop.hive.ql.exec.Operator.close(Operator.java:591)
> 	at org.apache.hadoop.hive.ql.exec.mr.ExecMapper.close(ExecMapper.java:

**Comment by costin** [comment]
That's because ES tries to parse your field as a date but it does not fail under the ISO8601 spec. You can get around this by either handling the date properly or by using a dedicated mapping in ES as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#mapping-date).

**Comment by costin** [comment]
Since there hasn't been any update on this issue, I'm closing it down. If the issue still persists, please open a new one (and potentially link this as well).

Cheers
