### ISSUE TITLE
Failing to parse timestamp values without milliseconds

### ISSUE THREAD

**Issue by brunborg** [elastic/elasticsearch-hadoop#694]
There is a bug in the parsing of timestamp values without milliseconds while using select

E.g. the value **[2016-02-03T08:16:26.389]** is successfully parsed, but the next value **[2016-02-03T08:19]** fails:

`
Failed with exception java.io.IOException:org.elasticsearch.hadoop.rest.EsHadoopParsingException: Cannot parse value [2016-02-03T08:19] for field [receivedTimestamp]
`

The error is consistent across different timestamp fields.

Using elasticsearch-hadoop-hive-2.2.0.jar

**Comment by costin** [comment]
That's because there is no mapping defined in ES and thus, the first value is used to determine the time. Since the second value doesn't match exactly the first value, ES cannot properly map it and hence the exception.
To work-around this, one would define the mapping before hand as explained in the [docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#mapping-date).

**Comment by costin** [comment]
As there hasn't been any update, closing the issue.

**Comment by srodiere** [comment]
I have same trouble and i don't understand why . There is something that i don't master at all about ES working

**Comment by wangxuegang1214** [comment]
'es.mapping.date.rich'='false'

**Comment by brianolsen87** [comment]
For a more concrete example.
```
#assuming you have a string field called customer and a date field called createdAt in elasticsearch

hive> DROP TABLE IF EXISTS my_table;

hive> CREATE EXTERNAL TABLE my_table (id string, customer string, createdat string)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES (
    'es.resource' = 'my_table_es_index',
    'es.nodes' = 'es_url:9200',
    'es.read.metadata' = 'true',
    'es.mapping.names' = 'id:_metadata._id,customer:customer,createdat:createdAt',
    'es.mapping.date.rich' = 'false'
);

#print date as string
select id, createdat, customer from my_table limit 10;

#convert the string described above to long (this type of logic can better reside inside a UDF
select id, unix_timestamp(createdat, "yyyy-MM-dd'T'HH:mm:ss"), customer from my_table limit 10;
```
