### ISSUE TITLE
Data and index into hdfs

### ISSUE THREAD

**Issue by pacosoplas** [elastic/elasticsearch-hadoop#695]
Hi:

after run bin/plugin -install elasticsearch/elasticsearch-hadoop/1.2.0 it say an ERROR: not plugin descriptor.properties is there.

Any other solution to store the data and index into hdfs?? i donw want snapshop, i want store the data al indexing from hdfs

thanks

**Comment by costin** [comment]
Please use the [dedicated forum](https://discuss.elastic.co) for questions, not the issue tracker or comment commits.

Thanks,
