### ISSUE TITLE
null pointer writing spark data frame (with Maps containing null values)

### ISSUE THREAD

**Issue by ethanocentricity** [elastic/elasticsearch-hadoop#698]
When using dataframe.saveToES, I got a null pointer from DataFrameValueWriter.writePrimitive trying to write a null string when it was called from doWriteMap.
I fixed it locally by adding a check at the start of writePrimitive:    _if (value == null) generator.writeNull()_
Alternatively, I assume it could probably be fixed in doWriteMap by changing:
 _if (value != null)_    
to        
 _if (v != null)_

**Comment by amatissart** [comment]
I'm facing the same problem.
Checking `if (value != null)` in the loop makes no sense, right ?
`doWriteMap` should probably behave similarly to `writeStruct`.
See PR #722

**Comment by costin** [comment]
Merged in master (and 2.x)
