### ISSUE TITLE
contributing guidelines link is broken

### ISSUE THREAD

**Issue by gmridul** [elastic/elasticsearch-hadoop#708]
https://github.com/elastic/elasticsearch-hadoop/blob/master/CONTRIBUTING.md

This link has [contributing guidelines] (https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) link in second paragraph which is broken

**Comment by costin** [comment]
Can you expand? All the links work for me (including the one you mentioned). Am I missing something?

**Comment by gmridul** [comment]
The information I mentioned in the issue was correct when I posted.
[contributing guidelines] (https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) is working now for me too.
It might have been fixed. Thanks!

**Comment by costin** [comment]
Thanks. Closing the issue.
