### ISSUE TITLE
org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 

### ISSUE THREAD

**Issue by santhoshtangudu** [elastic/elasticsearch-hadoop#712]
Hi,
I am trying to dump from Hadoop to ES using elasticsearch-hadoop. I tested Java code in my local and it is working perfectly fine. The data size is around 200MB.

I used the same code to dump the data in production (where Hadoop cluster is not under my control). I am getting below exception. Then I tried to tweak various parameters(batch size, retry count, wait time, number of reducers etc) as mentioned in [documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#configuration-serialization). Whatever the number of reducers I maintain, Job is getting succeed till n-1 reducers and nth reducer started failing with the below exception. 

**Stack trace :**

16/03/03 15:08:02 INFO mapred.JobClient: Task Id : attempt_201512041415_403627_r_000000_1, Status : FAILED
org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[10.231.15.149:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:423)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:403)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:407)
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:114)
	at org.elasticsearch.hadoop.rest.RestClient.esVersion(RestClient.java:553)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:177)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:379)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
	at org.apache.hadoop.mapred.ReduceTask$NewTrack

I verified the health of ES using Marvel. Everything looks fine. 

**Environments:**
**Local:**
Java : 1.8.0_65
Hadoop : 2.7.1
ES Hadoop : 2.2.0
ES Version: 2.2.0

**Production:**
Java : 1.7.0_60
Hadoop : 2.0.0-cdh4.7.0
ES Hadoop : 2.2.0
ES Version: Verified with 2.2 and 2.0 also

Please help me to solve this problem.

**Comment by costin** [comment]
You should never use localhost/127.0.0.1 in production since it means ES runs locally on whatever host Hadoop picks up to execute your job tasks. Which is never the case - you should specify the global accessible IP of your ES from Hadoop.

**Comment by santhoshtangudu** [comment]
I changed the IP address of machine also. Still it is giving the same error.

**Comment by santhoshtangudu** [comment]
@costin, please help me to resolve this.

**Comment by costin** [comment]
@santhoshtangudu Double check that the ES host is accessible from all your nodes. The fact that you tweaked the default settings is a good indication that you have increased the bulk size way too much and ES lags behind and eventually fails.
Reset your settings, start with a small dataset and reduce the number of jobs and its bulk size until it succeeds.

**Comment by santhoshtangudu** [comment]
@costin , Thanks for helping me.

I verified that the machine is not accessible from some of the nodes. I fixed this and it is working fine.

**Comment by bobby259** [comment]
@santhoshtangudu  How did you verify that the machine is not accessible form some of the nodes? I am facing the same issue. Please help.

**Comment by bkard** [comment]
Hi, 
I have the same issue and I can't figure out how to solve it. 
My ES IP is 10.10.90.182, and it has one node with IP 192.111.1.111
I created an external table using 10.10.90.182:9200 as IP and Port numbers.
When I try to select from the table I receive this ERROR:

Failed with exception java.io.IOException:org.elasticsearch.hadoop.rest.EsHadoopNoNdesLeftException: Connection error (check network and/or proxy settings)- all nodesfailed; tried [[192.111.1.1117:9200]]

How can I verify that all nodes are accessible? 

Thanks.

**Comment by santhoshtangudu** [comment]
In the config file of ES, there is a value associated with this. I changed the IP address. Then it started working.

**Comment by bobby259** [comment]
@KrishnaShah123 are you able throw in some logs here? Also, elasticsearch.yml config if possible.

**Comment by santhoshtangudu** [comment]
@KrishnaShah123 I have done this long back. I vaguely remember this. AFAIR, please change the network.host value.

**Comment by KrishnaShah123** [comment]
@jbaiera  Sure  I would ffollow that. I'm new here, so dint know. Accept my apologies for the same.

**Comment by bpaul1991** [comment]
@KrishnaShah123 Kindly help me with the issue. Iam facing the same problem. Kindly give me inputs as to how to resolve the problem. This is an humble request from my end

**Comment by bpaul1991** [comment]
@costin Kindly help as Iam facing the same problem. Please help me out. I have mentioned the static IP address, but still it shows the same error. Please provide your valuable input.

**Comment by jbaiera** [comment]
@bpaul1991 As mentioned in the comments above: Please avoid petitioning specific users on old issues on github. In the future, we ask that you keep these kinds of questions to the forums. We reserve github for tracking confirmed bugs and feature planning.
