### ISSUE TITLE
Metadata change in ES 2.x

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#715]
In ES 2.x, metadata can no longer be specified per document but rather [per call](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html). This makes things somewhat tricky in terms of bulk indexing since it means different calls need to be made per call

**Comment by sachingsachin** [comment]
We have around 40 storm nodes feeding to a 30-shard, 1-replica-each Elastic-Search cluster.
Without routing, each indexing request from storm is being further divided into 30 shards by the receiving shard.
That means even if we send 30 MB per request, it ends being 1 MB / shard / request.
This is really a performance killer for us.

If we can get routing back, there will be 29 lesser network requests per call and each shard will index 30 MB / request without distributing.
So getting routing to work is really important for us.

Will appreciate if there is some hint on when it is planned to be put back.
I can offer a patch if someone is ready to help me review the same.
