### ISSUE TITLE
saveToEs does compute the RDD twice

### ISSUE THREAD

**Issue by mniehoff** [elastic/elasticsearch-hadoop#728]
Feature Request

Due to calling `take(1)` in the runJob method of EsSparkSQL the data may be computed twice in the worst case. Imo the check for an empty RDD is not necessary and should be removed or at least made optional. Caching the incoming RDD might not be sufficient as it may be to big.

You could also use rdd.isEmpty() to check for empty RDDs. Furthermore the check differs from sql12 to sql13 (I guess sql13 is for spark >= 1.3?)

**Comment by costin** [comment]
@mniehoff do you experience this behaviour? I ask since `rdd.isEmpty()` is implemented as:
`partitions.length == 0 || take(1).length == 0` namely exactly as in `EsSparkSQL#saveToEs` (I assume that's what you meant by `runJob` method).
As regarding the difference between Spark 1.2 and 1.3, the APIs are different - `SchemaRDD` provides access to the underlying partitions while the `DataFrame` does not. Further more, getting a hold of an `RDD` from within a `DataFrame` will trigger a conversion hence why only `take(1)` is used.

Last but not least, `saveToES` triggers a spark job - doing that if there's no content is quite expensive. And using `isEmpty` and co is allowed since these are public APIs.

**Comment by mniehoff** [comment]
you are right. The implementation of the check is not the problem, it is - as you say - the same as in, but that was not my main concern.

yes, I've seen this behaviour. I have a Spark Job doing some joins and aggregates. The `take(1)` takes about 10 minutes to execute, then the final save takes about 10 minutes + the time to write to es. The save job has the same count of tasks as the `take(1)` job, plus 200 for saving to es (using the DataFrame API with the default `spark.sql.shuffle.partitions=200`) instead of 1 task for executing the `take(1)`. 

![jobs](https://cloud.githubusercontent.com/assets/1019130/14233473/bec01048-f9c9-11e5-8176-77530ca488f4.png)

Here Job 6 was the take, Job 7 is the write to ES (takes about 50 minutes when completed; Jobs 1, 3 and 5 failed due to problem with our ES instance). The problem is, that the `take(1)` might be quite fast, i.e. if you just read a file and import each row to ES it just has to compute one partition. But it might take a long time in a complex job to actually compute one row. And in our case `take(1)` has to compute the whole dataset to get one row.

What exactly is expensive triggering an job with no data? 
I see the problem that while doing batch jobs there normally is content, but when doing streaming,  batches without content might be quite common.

**Comment by costin** [comment]
Fair enough - I've remove the empty checks in master (upcoming 2.3). 2.2.1 will remain as is.

Even triggering a job has a slight overhead - create the partitions, each one connect to ES to determine the cluster state, etc... only to not write anything in return.
It is really annoying that such a basic check has such a huge impact - I've now removed `take(1)` and only check the partitions which in SparkSQL 1.3+ is not available so basically a job is triggered for any non-null `DataFrame` - looks like the cheapest call to make...
It would be great if you could try the nightly build (available in a couple of hours) and report back the performance improvements.

**Comment by mniehoff** [comment]
I do not have access to the cluster atm, will try asap. changes LGTM!

**Comment by costin** [comment]
Closing the issue.
Closing the issue - if the issue persists, please open a new issue referring this one.

Thanks
