### ISSUE TITLE
Es.index.read.missing.as.empty is not working with multiple indices

### ISSUE THREAD

**Issue by DynamicScope** [elastic/elasticsearch-hadoop#730]
Elasticsearch version: 2.2.0

JVM version: 1.8.0_73

OS version: Linux 4.1.17-22.30.amzn1.x86_64

Description of the problem including expected versus actual behavior:
This Issue has been discussed [here](https://discuss.elastic.co/t/es-index-read-missing-as-empty-seems-not-working-with-multiple-indices/42612/1).

**Comment by costin** [comment]
I've added some tests and polished the code a bit in master. A couple of remarks:

1. if a space is used, the resulting query is invalid which is no good.
2. in ES 2.2, a non existing index will trigger an exception in the logs however that's expected - this is teh result of every index check (HEAD index/type). ES-Hadoop however behaves correctly.

Please try out the [dev build](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) when you have time.

**Comment by costin** [comment]
Closing the issue - if the issue persists, please open a new issue referring this one.

Thanks

**Comment by qgong-aa** [comment]
@costin hi costin. I've met a relevant problem. During multiple indices search, by restful API, i can set 
"ignore_unavailable" option to search only those exists indices. For example, to search "index-1,index-2,index-3,index-4", when "index-3" is missing, the result will contain data from "index-1,index-2,index4". However in es-hadoop, i can't find relevant options. If some of the index missed, the whole read will either fail or return empty by setting "Es.index.read.missing.as.empty".
