### ISSUE TITLE
Why does EsBolt still use the old JAR

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch-hadoop#754]
### EsBolt uses old JAR

EsBolt still uses the old jar as

`import backtype.storm.topology.IRichBolt;`

backtype.storm is not supported anymore

It should be org.apache.storm as far as i know. So, if i use the new jars for the latest storm version,i cant use the EsBolt

### Version Info

OS:         :  Win7
JVM         :  1.8
Hadoop/Storm: 1.0.0 
ES-Hadoop   :  2.3
ES          :  2.3.1

**Comment by costin** [comment]
The package change in Storm 1.0.0 is quite disruptive and the reason the upgrade hasn't been made yet.
Basically by upgrading to 1.0.0, the 0.x versions stop being supported - and while it would be nice to upgrade, there are a LOT of projects that simply can't do that.
I'm not sure how to proceed to be fair; the storm folks could have still provided the old jars without making the transition so disruptive.
Maintaining two jars (storm-1x and 0.x) is too much trouble and really not the right approach.

**Comment by abtpst** [comment]
thanks Costin. we can continue to use storm 0.9 as it functionally, it does not hinder us.

**Comment by mazhechao** [comment]
I have sent a pr https://github.com/elastic/elasticsearch-hadoop/pull/769

**Comment by costin** [comment]
Storm 1.0.x was added in master (and thus support for 0.9.x was dropped).
Fixed through #769.
