### ISSUE TITLE
hive elasticsearch external table creation

### ISSUE THREAD

**Issue by stuenofotso** [elastic/elasticsearch-hadoop#761]
### What kind an issue is this?
- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.  
  The easier it is to track down the bug, the faster it is solved. 

### Issue description

When I create external table in hive stored by ElasticSearch Handler, it works without error:
CREATE  TABLE test (day STRING, idCust STRING)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'test/test',
'es.mapping.names' = 'day:@timestamp',
'es.nodes' = 'localhost');

When I insert data in it , it works

But when I try to query it, I get error:

Failed with exception java.io.IOException:org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Index [test/test] missing and settings [es.index.read.missing.as.empty] is set to false

When I check indices list, 'test' does not appear

curl 'localhost:9200/_cat/indices?v'
### Steps to reproduce

```
CREATE  TABLE test (day STRING, idCust STRING)
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES('es.resource' = 'test/test',
'es.mapping.names' = 'day:@timestamp',
'es.nodes' = 'localhost');

curl 'localhost:9200/_cat/indices?v'

select * from test;
```

Strack trace:

```
Failed with exception java.io.IOException:org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Index [test/test] missing and settings [es.index.read.missing.as.empty] is set to false
```
### Version Info

OS:         :  Redhat 6
JVM         :  1.7
Hadoop/Spark:  2.4/1.6
ES-Hadoop   :  2.3
ES          :  2.2

**Comment by costin** [comment]
Likely the insert of data does not succeed. How can you tell that the data actually hit ES?
Also, do you use Hive on the same machine as ES or not?

**Comment by stuenofotso** [comment]
Hive and ES are in cluster mode 

In what conditions does Es/hive create index?

**Comment by jbaiera** [comment]
As of 2.3, the connector creates the index if it does not already exist in the case of reading from a singular (i.e. non patterned) index. It does this during job start up in the driver before launching any tasks. I would have to agree with costin that either the index creation is either failing or being lost somewhere. Does it still occur on newer versions of ES-Hadoop?

**Comment by jbaiera** [comment]
Closing this on lack of feedback. Will re-open if this is still an issue.
