### ISSUE TITLE
Provide Kerberos configuration documentation

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch-hadoop#762]
### What kind an issue is this?

- [x] Feature Request. 

### Feature description
The ES_Hadoop connector works with Kerberos-enabled Hadoop but there is not any documentation on configuration.

**Comment by costin** [comment]
The readme for the plugin documents the recently introduced [options](https://github.com/elastic/elasticsearch-hadoop/tree/2.x/repository-hdfs#configuration-properties). Is there anything else that is needed?

**Comment by sherry-ger** [comment]
No.  Closing.  Thank you!
