### ISSUE TITLE
Upgrade to ES 2.3.3

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#763]
Upgrade ES dependency in ES-Hadoop to 2.3.3

**Comment by jmssil** [comment]
Does ES-Hadoop v2.3.2 require ES v2.3.3 or can we use it with ES v2.3.0?

**Comment by costin** [comment]
Yes, you can use it.
Note,for questions, please use the dedicated [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) not the issue tracker.

Thanks,

**Comment by jmssil** [comment]
OK, thanks.

I just used the issue tracker because I read this in the changelog: 
"Upgrade to ES 2.3.3 [ISSUE] #763". So I wondered whether this issue was 
specifically created to enforce the dependency on ES v2.3.3.
