### ISSUE TITLE
elasticsearch-hadoop exception about mapping

### ISSUE THREAD

**Issue by JackWang917** [elastic/elasticsearch-hadoop#766]
I got the following exception, I'm very confused about this:
`org.elasticsearch.hadoop.rest.EsHadoopParsingException: Cannot parse value [2016-03-13T02:32:56] for field [create_time]`
My mapping as following:
```
"mappings": {
    "users": {
        "properties": {
          "create_time": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          }
      }
 }
```

**Comment by JackWang917** [comment]
I'm using elasticsearch-hadoop 2.2.0, is this a bug?

**Comment by armaseg** [comment]
Hello,

I think it may be a problem on your date format because "ES-Hadoop can work only with ISO8601 dates" https://github.com/elastic/elasticsearch-hadoop/issues/690 

https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#mapping-date
https://en.wikipedia.org/wiki/ISO_8601

**Comment by costin** [comment]
Indeed, the date is incorrect as it is not a valid ISO8601 (whenever specifying the time, make sure it includes a timezone).
For questions, please use the dedicated [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) not the issue tracker.

Thanks,
