### ISSUE TITLE
The Writing to dynamic/multi-resources example is not working for spark.

### ISSUE THREAD

**Issue by withccm** [elastic/elasticsearch-hadoop#767]
### What kind an issue is this?
- Bug report

### Issue description

[The Writing to dynamic/multi-resources example](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html#spark-write-dyn) is not working for spark.

I was confused because it was used with 'media-type' and 'media_type'.

**Comment by costin** [comment]
Resolved through PR #768
