### ISSUE TITLE
[DOCS] : 2.3.1 release notes list many bugs as fixed without commits

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch-hadoop#770]
In the 2.3.1 release notes, the following bug fixes are listed:

URLDecoder: Illegal hex characters in escape (%) pattern - For input string: " S" [ISSUE] #747
ERROR NetworkClient: Node [127.0.0.1:9200] failed (Read timed out); no other nodes left - aborting... [ISSUE] #753
Elasticsearch Mapreduce write "es.mapping.exclude" not working [ISSUE] #752
PROBLEM: Failed to write data back to ES by using Spark DataFrame save() API !! [ISSUE] #749
NetworkClient: Invalid target URI POST@null/pharmadata/test/_search [ISSUE] #748
Pushdown option not working as expected with Spark data frames [ISSUE] #734
Unhandled Exception in org.elasticsearch.spark.rdd.EsRDDWriter.write, and rdd wouldn't stop. [ISSUE] #719

Of these, only #747 appears to have a fix checked in.  The rest are mostly questions or invalid bugs.  Listing issues that were closed but did not result in a code change is confusing as it makes it hard for users to tell what has really changed in the code when upgrading.

**Comment by costin** [comment]
Sorry for the confusion and noise Sean. I'll look into improving the report so the closed issues are included but better differentiated.

Cheers,

**Comment by costin** [comment]
I've added the non-issue label to properly differentiate issues that are raised but are not actually code related (questions, issues that don't get resolved, etc...). Unfortunately it looks like Github is having issues right now but once it stabilizes, I'll post a draft report with what it will look like.

**Comment by costin** [comment]
Hopefully this is better:

```
[[non-issue-2.3.3]]
[float]
=== Non-issue
* [DOCS] : 2.3.1 release notes list many bugs as fixed without commits [OPEN] [ISSUE] {pull}770[#770]
```

**Comment by seang-es** [comment]
That sounds like a good solution to me, thanks!
