### ISSUE TITLE
Storm 1.x causes race conditions in test suite

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#771]
### What kind an issue is this?
- [x ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.  
  The easier it is to track down the bug, the faster it is solved. 
### Issue description

Storm 1.x not only breaks API backwards compatibility but also internally adds some new changes in terms of threading causing again the test suite as a whole to fail due to race conditions (same tests work fine on Storm 0.9).

The integration tests need to be revised - potentially translating them to unit tests to stop fiddling with Disruptor & co.

**Comment by jbaiera** [comment]
Since we have removed support for Storm in the latest versions of ES-Hadoop, I will go ahead and close this issue.
