### ISSUE TITLE
Use new parallel reader API in ES 5.x

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#778]
ES 5.x has a proposal/PR elastic/elasticsearch/pull/18237 for allowing parallel reads for an alias/index based on a query based on an arbitrary number of slices. This goes beyond the capabilities of scan/scroll in ES 1.x/2.x and it's something that is desired in highly parallel environments or those that have memory/processing constrains (but high number of instances).

**Comment by garyelephant** [comment]
When will this feature be added ?

**Comment by 666666666666** [comment]
It will help me a lot

**Comment by costin** [comment]
@jimferenczi Can you please link(if you already have a ticket in place) or update this issue with your progress? Thanks.

**Comment by jimferenczi** [comment]
@costin you can find the progress here:
https://github.com/elastic/elasticsearch-hadoop/issues/812
