### ISSUE TITLE
Got exception when I tried to invoke _mtermvector

### ISSUE THREAD

**Issue by JackWang917** [elastic/elasticsearch-hadoop#796]
I was trying to get _mtermvector by using the following code:
```
 val query= """_mtermvectors {
        "ids" : ["1256"],
        "parameters": {
            "fields": [
                 "tname"
            ],
            "term_statistics": true
        }
    }"""
    var idRdd = sparkContext.esRDD("uindex/type1",query)
```
But it didn't work, any ideas please, appreciate!

**Comment by jbaiera** [comment]
Hello! "_mtermvectors" is a document api call, not a query. ES-Hadoop uses the scroll api along with an optionally provided query. A provided query must be either a valid `?uri_query`, a valid Query DSL, or an external resource file which contains either of the two preceding query types. Please see [this documentation entry](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_querying) for more information.

Also, this is a question that is more suited for [posting on our forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop). We try to keep GitHub for issue tracking and bug reports only. If you're not sure of where to post something, the forum is always the best place to start. Thanks!
