### ISSUE TITLE
Add support for 16-bit/half floats in ES 5.x

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#800]
ES 5.x alpha4 introduced 16-bit float (https://github.com/elastic/elasticsearch/pull/18887) which ES-Hadoop should start supporting.

**Comment by acchen97** [comment]
Additionally, in the vein of new data types, ES 5.0 is also splitting strings into text (analyzed field, no doc values) or keywords (non-analyzed, doc values enabled by default). https://github.com/elastic/elasticsearch/issues/12394

@jbaiera what do you think about adding this? Happy to create a new issue as this type of stuff is probably worthwhile getting into the major.

**Comment by jbaiera** [comment]
@acchen97 It seems that support for the `text` and `keyword` types was added a while ago. Winner by default!

**Comment by acchen97** [comment]
Thanks for checking. I remember mentioning it a while back, but couldn't find the issue/PR for it right now.
