### ISSUE TITLE
Use ES 5.x rest client instead of our own

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#801]
With ES 5.x alpha4, an official Java REST client is now available. It needs to be integrated into ES-Hadoop and see to what degree we can use it over the internal one.
Things to consider are:
1. usage of the underlying HTTP transport (http rest client, 3.0.x vs 4.x)
2. using the async support
3. autodetection or embedding to avoid issue with the classpath madness in various Hadoop envs.

**Comment by jbaiera** [comment]
Closing this in favor of #932
