### ISSUE TITLE
Provide interface for plugging in custom http request transformers.

### ISSUE THREAD

**Issue by thomasdziedzic** [elastic/elasticsearch-hadoop#803]
### Feature description

I am using AWS Elasticsearch as a Service (EaaS). I have authentication required for my cluster using aws's custom signature method (http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html).

I found a post in the forum by someone with the same issue as me, and a response stating that elasticsearch-hadoop will definitely _not_ support the aws signing method. So I took a look at adding it myself, but unfortunately I couldn't find a method that didn't involve modifying the original library.

A pluggable http transformer interface would allow me to write a custom aws signing transformer along with any other use case that deviates from the standard http requests that get sent out without having to delve into the guts of the library.

Thanks for your time!

**Comment by wbchn** [comment]
+1 

[Here](https://blogs.aws.amazon.com/security/post/Tx3VP208IBVASUQ/How-to-Control-Access-to-Your-Amazon-Elasticsearch-Service-Domain) is a demo, I think @awslabs maybe have a better idea about solve this.

**Comment by jbaiera** [comment]
Relates #626

**Comment by jbaiera** [comment]
Closing this as it's a duplicate
