### ISSUE TITLE
Integrating with ES ingest node pipeline

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#806]
Exposing the interface for Elasticsearch's ingest node pipelines within ES-Hadoop can easily bring Logstash-like functionality (i.e. pattern matching with grok, parse date fields with date processors) to the data ingest flow from the Hadoop world. This should expose the option of specifying an ingest pipeline for pre-processing before writing to an index (suffixing the query param "...?pipeline=test_pipeline"). It's potentially useful among the entire component suite, but initially Spark and MapReduce seem like good entry points for this feature. As always, open to additional input here.

https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html

**Comment by jbaiera** [comment]
This is really two points:

1. Add an option to specify a pipeline to write to and 
2. Add an option to target ingest nodes only (similar to client.only or data.only, etc..)

**Comment by jbaiera** [comment]
Leaving this open until I get the documentation updated with the new settings.

**Comment by acchen97** [comment]
Awesome, happy to help review the doc changes if you'd like.

**Comment by acchen97** [comment]
Looks good thanks
