### ISSUE TITLE
Snapshot Creation Exception

### ISSUE THREAD

**Issue by c-val** [elastic/elasticsearch-hadoop#813]
I want to snapshot my ES to a kerberized Hadoop HDFS. I get an exception while creating the snapshot (full text below).

**Here is my /_snapshot/my_backup :**
{
  "type":"hdfs",
  "settings":{
    "uri": "hdfs://my_hdfs_front_address:port/",
    "path": "my_hdfs_path_on_the_front/",
    "conf.dfs.client.read.shortcircuit": "true",
    "load_defaults": "false",
    "conf_location": "/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml",
	"user_keytab": "/etc/security/my_keytab.keytab",
    "user_principal": "my@principal",
    "user_principal_hostname": ""
  }
}

**I get the following :**

```
{
    "error": {
        "root_cause": [
            {
                "type": "repository_exception",
                "reason": "[my_backup] failed to create repository"
            }
        ],
        "type": "repository_exception",
        "reason": "[my_backup] failed to create repository",
        "caused_by": {
            "type": "creation_exception",
            "reason": "Guice creation errors:\n\n1) Error injecting constructor, java.lang.IllegalArgumentException: Cannot find classpath resource or file 'conf_location' [/etc/hadoop/conf/core-site.xml] defined for hdfs snapshot/restore\n  at org.elasticsearch.repositories.hdfs.HdfsRepository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.hdfs.HdfsRepository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error",
            "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "Cannot find classpath resource or file 'conf_location' [/etc/hadoop/conf/core-site.xml] defined for hdfs snapshot/restore"
            }
        }
    },
    "status": 500
}
```

**Comment by jbaiera** [comment]
Hello. The Github issues section is reserved for specific feature requests and bug tracking only. Please post these sorts of questions in the [discuss forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop) along with which version of the technologies you are using. Thank you.
