### ISSUE TITLE
Get fields with documents in Elasticsearch

### ISSUE THREAD

**Issue by MSaifAsif** [elastic/elasticsearch-hadoop#825]
- [x] Feature Request. 

### Feature description

I am using pig to read documents from my Elasticsearch servers. The documents look something like this

    {
        "_index": "sa-test",
        "_type": "logs",
        "_id": "AUujDbzSR5FzDDhtC1LH",
        "_score": 1,
        "_source": {
            "fieldA": "....",
            "fieldB": "....",
            "fieldC": ".....",
            "fieldE": "....."
        }
    }, {
        "_index": "sa-test",
        "_type": "logs",
        "_id": "AUujDbzSR5FzXXXtC1LH",
        "_score": 1,
        "_source": {
            "fieldB": "....",
            "fieldC": ".....",
            "fieldD": "....."
        }
    }

which is fine. The problem occurs when I try to read this data in via Pig

    -- load the data in
    raw_logs = LOAD 'sa-test' USING org.elasticsearch.hadoop.pig.EsStorage('es.query=?q=someFilter', 'es.mapping.date.rich=false');
    -- for now just dump it
    DUMP raw_logs;

this yields data in the form

    (fieldA,fieldB,fieldC,fieldE)
    (fieldB,fieldC,fieldD)

now at this point, I don't have any idea which fields were missing or which ones are present since data in each row in inconsistent. This is proving a problem for further processing.

Is there any way to get field values along with the rows or some sort of mapping that can tell me which value belongs to which field. Something of the sort

    (A=fieldA,B=fieldB,C=fieldC,E=fieldE)
    (A=fieldB,C=fieldC,D=fieldD)

**Comment by jbaiera** [comment]
You can specify a schema when loading data into pig:

    raw_logs = LOAD 'sa-test' USING org.elasticsearch.hadoop.pig.EsStorage('es.query=?q=someFilter', 'es.mapping.date.rich=false') AS (fieldA:...,fieldB:...,fieldC:...,fieldD:...fieldE:...);

ES-Hadoop will match up document fields from Elasticsearch with the provided schema for Pig. At that point, you can refer to the fields by name:

    all_fieldA_values = FOREACH raw_logs GENERATE fieldA;

Also, just for future reference, Github issues are reserved for clearly defined bugs and actionable new feature requests. These sorts of questions are best asked on the [forum](https://discuss.elastic.co/c/elasticsearch-and-hadoop).

**Comment by MSaifAsif** [comment]
@jbaiera Thanks for getting back to me on this one. I will try it out as soon as I get back on my ES machine. Also, sure I'll use the forum for posting any further questions.

**Comment by MSaifAsif** [comment]
We can close this. Solved my issue by using aliases as you suggested.

**Comment by jbaiera** [comment]
Good to hear, Cheers!
