### ISSUE TITLE
Spark dataframe upsert with _ttl field for each document

### ISSUE THREAD

**Issue by joohnnie** [elastic/elasticsearch-hadoop#828]
### Version Info

OS:         :  Mac OX 10.11.6
JVM         :  JDK 1.7.0_79
Hadoop/Spark:  Spark 1.6.2
ES-Hadoop   :  2.3.4
ES          :  2.3.1
### Feature description

Currently, i have index with 3 fields. There is a spark streaming job to update the document in a fix interval. Also, we need to set _ttl to expire the document.

Code without _ttl is as below
#### Case class map to index

```
case class A(a:String,b:Option[String],c:Option[String])

```
#### Insert one document

```
import org.apache.spark._
import org.elasticsearch.spark._
import org.elasticsearch.spark.sql._

val sparkConf = new SparkConf().setAppName("SparkEs1").setMaster("local")
sparkConf.set("es.nodes", "localhost")
sparkConf.set("es.port", "9200")
sparkConf.set("es.index.auto.create", "true")
sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
sparkConf.set("es.write.operation","upsert")

val sc = new SparkContext(sparkConf)
import org.apache.spark.sql._
val sqlContext = new SQLContext(sc) 

import sqlContext.implicits._

case class A(a:String,b:Option[String],c:Option[String])

val a=A("a1",Some("b1"),None)
val rdd = sc.makeRDD(Seq(a))
val df = sqlContext.createDataFrame(rdd)
df.saveToEs("test/1",Map("es.mapping.id" -> "a"))
```
#### Here we get the result

```
"_source": {
               "a": "a1",
               "b": "b1"
}
```
#### Update the document

```
val a1=A("a1",None,Some("c1"))
val rdd1 = sc.makeRDD(Seq(a1))
val df1 = sqlContext.createDataFrame(rdd1)
df1.saveToEs("test/1",Map("es.mapping.id" -> "a"))
```
#### Result is

```
"_source": {
               "a": "a1",
               "b": "b1",
               "c": "c1"
}
```
#### Add _ttl for each document

Each document need to have a _ttl field.
Using dataframe, i cannot find the place to specify the Metadata.
#### Use RDD to set the _ttl field

However RDD have the function to specify the MetaData for each document. But it doesn't have the function to update with null value which provided by dataframe via config : es.spark.dataframe.write.null

The following is the code by RDD

Enable _ttl

```
PUT /test
{
  "mappings": {
    "2": {
      "_ttl": {
        "enabled": true
      }
    }
  }
}
```

Code

```
import org.apache.spark._
import org.elasticsearch.spark._
import org.elasticsearch.spark.rdd.Metadata._

val sparkConf = new SparkConf().setAppName("SparkEs1").setMaster("local")
sparkConf.set("es.nodes", "localhost")
sparkConf.set("es.port", "9200")
sparkConf.set("es.index.auto.create", "true")
sparkConf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
sparkConf.set("es.write.operation","upsert")

val sc = new SparkContext(sparkConf)

case class A(a:String,b:Option[String],c:Option[String])

val a=A("a2",Some("b2"),None)

val rdd = sc.makeRDD(Seq(a)).map(x=> (Map(ID -> "a", TTL -> 50000000L), x))

rdd.saveToEsWithMeta("test/2")

val a1=A("a2",None,Some("c2"))
val rdd1 = sc.makeRDD(Seq(a1)).map(x=> (Map(ID -> "a", TTL -> 1000000000L), x))

rdd1.saveToEsWithMeta("test/2")
```

Final result is :

```
"_index": "test",
            "_type": "2",
            "_id": "a",
            "_score": 1,
            "_ttl": 999996843,
            "_source": {
               **"a": "a2",
               "b": null,
               "c": "c2"**
            }
```

Not the expected 

```
"_index": "test",
            "_type": "2",
            "_id": "a",
            "_score": 1,
            "_ttl": 999996843,
            "_source": {
               **"a": "a2",
               "b": "b2",
               "c": "c2"**
            }
```
### Question

For spark dataframe, is there any way to specify the Metadata for each document?

Thanks

**Comment by jbaiera** [comment]
Sadly there is no way to specify a document's Metadata via the Dataframe API. Dataframes are collections of rows, the fields of which are considered to all be part of the same document. 

A work around for your current situation could be to set field `b2` as an excluded field when writing using the `es.mapping.exclude` setting. This would direct the library to ignore the null value and not write anything for it at all.

**Comment by joohnnie** [comment]
Hi James,
Thanks for your response.

To simplify the question, the use case is 

Insert below to ES

```
a: a1
b:b1
c:null 
```

Update with 

```
a:a1
c:c1
```

The expected result is

```
a:a1
b:b1
c:c1
```

Update with below

```
a:a1
b:b2
```


The expected result is

```
a:a1
b:b2
c:c1
```

Update with 

```
a:a1
b:b3
c:c3
```

The expected result is

```
a:a1
b:b3
c:c3
```

In addition it should have _ttl field. The ttl for each document is different.

"es.mapping.exclude" setting might not work for the case.

Do you have any suggestions?
Thanks

**Comment by jbaiera** [comment]
I'm going to go ahead and close this for now since _ttl is currently deprecated and removed in 6.0.
