### ISSUE TITLE
Documentation Issue : Wrong package name

### ISSUE THREAD

**Issue by nikitaGoyal2** [elastic/elasticsearch-hadoop#838]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

Description

Wrong package name provided in the documentation.

### Steps to reproduce

Please change import statement defined in Spark block to "import org.elasticsearch.spark.rdd.api.java.JavaEsSpark; " .

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

ES-Hadoop   :  All
ES          :  All

**Comment by jbaiera** [comment]
This should be fixed now with https://github.com/elastic/elasticsearch-hadoop/commit/73169c369aa7a01bdca3f7666d8e5767a058cb59 and https://github.com/elastic/elasticsearch-hadoop/commit/3676ce0673fa609a4f853dfe349838db9106dab1
