### ISSUE TITLE
Dropping a whole column of a DataFrame while indexing the DF into ES

### ISSUE THREAD

**Issue by AliGouta** [elastic/elasticsearch-hadoop#841]
### Issue description

While indexing a DataFrame into ES, if a null value occur in one Row, then the whole column relative tio to that null won't be indexed.
Description

Example of DF:

```
+--------------------+----------+------------+--------+--------------------+--------------------+
|         date_normal|  date1        | streamer    |    cseq     |             date2         |             url             |
+--------------------+----------+------------+--------+--------------------+--------------------+
|2016-07-08 00:00:...|1467929015|     BDX1STR|15933124|2016-07-08 00:00:...|rtsp://10.212.16....|
|2016-07-08 00:00:...|1467929612|      null  |15913572|2016-07-08 00:00:...|rtsp://10.212.16....|
|2016-07-08 00:00:...|1467928823|     BDX1STR|15933133|2016-07-08 00:00:...|rtsp://10.212.16....|
|2016-07-08 00:00:...|1467928850|     BDX1STR|15913578|2016-07-08 00:00:...|rtsp://10.212.16....|
|2016-07-08 00:00:...|1467929275|     BDX1STR|15900573|2016-07-08 00:00:...|rtsp://10.212.16....|
|2016-07-08 00:00:...|1467929382|     BDX1STR|15900584|2016-07-08 00:00:...|rtsp://10.212.16....|

```

Here, in the second row we have null in Streamer column => in Elasticsearch, the whole column in the all rows won't be indexed. Ideally, the streamer field should exist in all indexed documents, however, for document 2, we need to see all fields except the field streamer.

Code:

```
         Dataset<Row> sqlDF = spark.sql("SELECT xxxx ");

         Map<String, String> cfg = new HashedMap();
         cfg.put("es.nodes", "10.x.x.x");
         cfg.put("es.port", "9200");
         cfg.put("es.resource", "vod/all");
         cfg.put("es.spark.dataframe.write.null", "true");

         JavaEsSparkSQL.saveToEs(sqlDF, cfg);

```
### Version Info

OS:         :  CentOS 6
Hadoop/Spark:  Spark 2.0
ES-Hadoop   :  

```
       <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-spark-20_2.10</artifactId>
            <version>5.0.0-alpha5</version>
        </dependency>
```

ES          :  elasticsearch-2.4.0

**Comment by jbaiera** [comment]
The ability to choose between writing null data and skipping it was added just before the Spark 2.0 branch came back to master. It seems that the 2.0 branch did not end up picking this change up, and thusly, only contains the logic to skip writing the null. I've reproduced the problem locally and should have a fix in soon. Nice find @AliGouta!
