### ISSUE TITLE
Connection error with Elasticsearch 2.4.0

### ISSUE THREAD

**Issue by ligyxy** [elastic/elasticsearch-hadoop#846]
Environment: Spark 2.0, Elasticsearch 2.4.0, elasticsearch-hadoop 2.4.0

here is my connection code:

```
es_rdd = sparkcontext.newAPIHadoopRDD(
        inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
        keyClass="org.apache.hadoop.io.NullWritable",
        valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable",
        conf={
            "es.resource": "index/profile",
            "es.net.ssl": "true",
            "es.net.http.auth.user": conn['es']['user'],
            "es.net.http.auth.pass": conn['es']['pass'],
            "es.nodes": conn['es']['host'],
            "es.port": conn['es']['port'],
            "es.query": query
        }
    )
```

It works with Elasticsearch 2.3.5, but returns following error with 2.4.0:

```
Traceback (most recent call last):
  File "/root/spark/es-test.py", line 41, in <module>
    es_data = es_query(sparkcontext=sc, query=query)
  File "/root/spark/crowdskout-prediction-models/es-test.py", line 36, in es_query
    "es.query": query
  File "/root/spark/python/lib/pyspark.zip/pyspark/context.py", line 646, in newAPIHadoopRDD
  File "/root/spark/python/lib/py4j-0.10.1-src.zip/py4j/java_gateway.py", line 933, in __call__
  File "/root/spark/python/lib/py4j-0.10.1-src.zip/py4j/protocol.py", line 312, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed;
```

I also noticed that the port in the output is 9201, but not the port I set in config.

**Comment by jbaiera** [comment]
Spark 2.0 support is only available in the ES-Hadoop 5.0.0-alpha5 release and above. ES-Hadoop 2.x does not currently support Spark 2.0. Please note that 5.0.0-alpha5 is an early access release meant for testing purposes only.

**Comment by ligyxy** [comment]
@jbaiera Just test it again with ES-Hadoop 5.0.0-alpha5, got the same error.

I am quite curious where the port 9201 comes from.

**Comment by jbaiera** [comment]
>I also noticed that the port in the output is 9201, but not the port I set in config.
...
I am quite curious where the port 9201 comes from.

I'm not sure what you are referring to? 9200 is the default port that Elasticsearch listens on for HTTP traffic. In the event that this port is not available, Elasticsearch will choose the next highest port (up to 9300) until it finds a port that it can listen on.

Could you elaborate more on what your current setup is and what you're trying to accomplish? Posting your actual configuration information helps much more than posting `..."es.nodes": conn['es']['host'],"es.port": conn['es']['port']...` (although you can leave off the security info).

**Comment by ligyxy** [comment]
OK, I am using HTTPS and port 9250 for elasticsearch. While surprisingly, in the Spark output, it shows the connection error with my nodes and 9201 port.
```
conf={
            "es.resource": "index/profile",
            "es.net.ssl": "true",
            "es.net.http.auth.user": “user”,
            "es.net.http.auth.pass": “passwd”,
            "es.nodes": "elastic.example.com",
            "es.port": "9250"
        }
```


```
Connection error (check network and/or proxy settings)- all nodes failed; tried [[NODE_IP:9201]]
```

**Comment by jbaiera** [comment]
Is this a single elasticsearch node that you're trying to connect to or is it a cluster? Is the node local? Could you query the `_nodes/http` endpoint and paste the results here? It would help to identify if this is a problem with node discovery.

**Comment by ligyxy** [comment]
You can close this issue actually. I have confirmed it's due to a wrong setting of my elasticsearch.

**Comment by jbaiera** [comment]
Thanks! Happy to hear you figured it out. Cheers :)
