### ISSUE TITLE
Support fields that are sometimes arrays

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch-hadoop#856]
Using spark-1.6.2-bin-hadoop2.6, ES-Hadoop 2.4.0 and pyspark.

Somewhere in my dataset there are fields that are normally arrays, but occasionally aren't - see below for an example. In real life, I think one offender is the logstash geoip filter generating the location field which is normally an array, but in some error cases isn't.

If I set es_read_field_as_array_include I get `scala.MatchError: jim`, if I don't set it I get `scala.MatchError: Buffer(tom, peter)`. Therefore I have no way of reading the field, and can only process the index if I blacklist the offending fields.

Also the stacktrace doesn't say what field it's having the issue with, which makes debugging very hard.

``` bash
curl -XPOST localhost:9200/sparktest/spark -d '{"friends":"jim"}'
curl -XPOST localhost:9200/sparktest/spark -d '{"friends":["tom","peter"]}'
./bin/pyspark --driver-class-path=../elasticsearch-hadoop-2.4.0/dist/elasticsearch-hadoop-2.4.0.jar
>>> df = sqlContext.read.format("org.elasticsearch.spark.sql").options(es_read_field_as_array_include="friends").load("sparktest/spark")
>>> df.show()
```

**Comment by aalkilani** [comment]
Any updates on this?

**Comment by qindeqiang** [comment]
Great，Configuration Params “es.read.field.as.array.include” is so import!

**Comment by jbaiera** [comment]
This should now be fixed with cd26933baff515b9ed7f01385655e7863fcb91bd

**Comment by CQUTWangHong** [comment]
@jbaiera ,I also met this problem,how to solve this problem now , thanks

**Comment by jbaiera** [comment]
@CQUTWangHong Please upgrade to any of the versions tagged on this issue

**Comment by CQUTWangHong** [comment]
@jbaiera 
I had upgrade to v6.1.0,but it doesn't work

my dependency:
```
	<dependency>
	    <groupId>org.elasticsearch</groupId>
	    <artifactId>elasticsearch-hadoop</artifactId>
	    <version>6.1.0</version>
	</dependency>
```
read data:
val options = Map(
            "es.nodes" -> es_nodes,
            "es.port" -> es_port,
            "es.read.field.include" -> "string_field",
            "es.read.field.as.array.include" -> "array_field"")
    val df = spark.sqlContext.read.format("org.elasticsearch.spark.sql")
                         .options(options)
                         .load("index/type")

is there anything wrong with my code?

**Comment by jbaiera** [comment]
@CQUTWangHong Can you provide an example record that is not working with the following code?

**Comment by CQUTWangHong** [comment]
When I print dataframe's schema
`df.printSchema()`
It only show
```
root
 |-- string_field: string (nullable = false)
```
No display array_field
that means "es.read.field.as.array.include" -> "array_field" doesn't work
