### ISSUE TITLE
ES-Hadoop with SSL/PKI security issue. Key/Truststore clear text passwords exposed in Spark UI

### ISSUE THREAD

**Issue by isp300** [elastic/elasticsearch-hadoop#859]
### Version Info

OS:         :   Any
JVM         :  1.8
Hadoop/Spark: Hadoop 2.7.3/Spark 1.6.2  
ES-Hadoop   :  2.10
ES          :  2.4.0

### Issue description

Clear text password in Spark UI for ES-Hadoop with SSL/PKI configuration 

### Steps to reproduce

Configure ES-Hadoop with SSL/PKI. It require the next properties (among others):
es.shield.ssl.keystore.password
es.shield.ssl.truststore.password
which holds clear text passwords for key and trustsore
Take a look at the picture attached (marked red) - these passwords exposed in Spark UI.

### Business case scenario (production mode):
Actors: 
Support representative - responsible for support customer in case any issue with Spark application
Customer representative - responsible for Spark application results from Customer side 
Sustaining representative - second/thrird level of support
IT representative - responsible for Hadoop/Spark cluster set up including keys, passwords etc.

All actors have its own area of responsibility and appropriate permission to access sensitive information. Among all actors the only IT rep has permission to access key/trust store passwords.

Support acting on some Customer issue related to Spark application. In order to analyze the state of application he need an access to Spark application environment screen (among others). This screen could be shared with Customer and/or Sustaining engineer(s). At this moment is critical to hide (do not expose) some sensitive information - key/truststore password is one of it.

From Spark point of view there is no concept of sensitive properties since it is specific for appropriate add-on/plugin.
There is no way to hide/scramble these passwords since Spark does not expose such functionality (limited UI access does not help since user have to see some properties any way). Custom password scrambling cannot be implemented since these passwords are using deep inside ES-Hadoop (in org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport)

### Suggested solution
1. Provide password scrambling functionality with some static algorithm (like encoding). This require some tool to scramble password before pass it to SparkConf. 
2. Current approach suggest to have some place to store keystore and truststore accessible from all Spark executors (Hadoop nodes). Keystore and truststore have to be well protected (using file system permission for example). The only person who have access to it (key/truststore and passwords for it) is IT representative.
Due this i don't quite understand why we need to pass password(s) from Spark client side (with all related issues)? I'd rather suggest to implement concept of "secure store" which is some well protected location accessible for each Hadoop node containing keystore, truststore and passwords for it.
In simplest case "secure store" is a file directory with mask 100/400 for directory/files. Inside it we have keystore, truststore files with fixed names and some property file that contains passwords for it.
In that case we are passing the only "secure.storage.path" Spark property.
More sophisticated implementations, for example,  could provide something like LDAP/DB based storages (better accessibility and management) -> leads to (3) below.
3. Implement custom Java key management that implements all requirements.

I'd prefer solution (2) as most balanced in terms of effort/result. I've implemented directory-based storage for my application (require org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport patching among others) and can share it if you are interested.  

![sparkappenvui](https://cloud.githubusercontent.com/assets/7735832/18973579/1127bf32-8653-11e6-94d0-2eced3ce9d61.jpg)

**Comment by jbaiera** [comment]
The biggest item that needs to be accounted for is that the solution to this configuration issue must work across all supported technologies. Thank you for opening the request and providing some suggestions on implementations.

**Comment by isp300** [comment]
Looks like Spark guys have fixed security issue -> https://issues.apache.org/jira/browse/SPARK-16796
For now it became low priority improvement related to configuration, you can close it

**Comment by jbaiera** [comment]
Closed per user feedback
