### ISSUE TITLE
ES_CLASSPATH removed from ES 2.x

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch-hadoop#861]
### Issue description

Description

We removed `ES_CLASSPATH` from ES 2.x but we still recommend to use the light version (https://github.com/elastic/elasticsearch-hadoop/blob/master/repository-hdfs/README.md#what-version-to-use) with ES_Classpath in haddoop for 2.x. 

The only way to get this working is by copying the libraries into the lib folder as per https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_setting_changes.html#_literal_es_classpath_removed_literal. 

We should fix the readme and documentation to prevent communication issues.

**Comment by gmoskovicz** [comment]
@costin the issue as required.

**Comment by jbaiera** [comment]
I'm just going to update the readme in the es-hadoop project with a work around for lacking the classpath option. With 5.0.0, the plugin has moved to Elasticsearch proper, and has been remade to be compliant under the security manager, which means that the `light` version is no longer usable in 5.0.0. I'll also add a note mentioning that `light` and `1.x` are no longer supported in the 5.0.0 version.
