### ISSUE TITLE
Can't specify parent if no parent field has been configured

### ISSUE THREAD

**Issue by IoDmitri** [elastic/elasticsearch-hadoop#880]
Here is my [SO](http://stackoverflow.com/questions/40186500/elasticsearch-spark-failing-to-index-type-after-parent-is-set) question that has code samples of my setup. Im noticing that this is only an issue with es-spark and not an issue if I try other indexing methods.

**Comment by jbaiera** [comment]
Can you please fill out the template for the github issue? Posting a complete message with the versions of the technologies used, the steps to recreate the problem, and the full description allows us to troubleshoot this faster. Thanks.
