### ISSUE TITLE
Support for ElasticSearch 5.0.0 GA

### ISSUE THREAD

**Issue by michaelqiu94** [elastic/elasticsearch-hadoop#884]
Hi,
   Since ElasticSearch 5.0.0 GA was released today, the 5.0.0 rc1 connector for Spark doesn't work anymore. I was wondering if/when you guys have plans to add support for that. Thanks!

**Comment by costin** [comment]
Please use the forum for questions, not the issue tracker. Thanks,

https://www.elastic.co/blog/es-hadoop-5-0-0-released
