### ISSUE TITLE
Documentation error: wrong maven artefact for elasticsearch-spark connector

### ISSUE THREAD

**Issue by vkroz** [elastic/elasticsearch-hadoop#890]
* ES verison 5.0.0
* Elasticsearch-Hadoop connector 5.0.0 for Spark

It is about documenting correct maven artefacts for `elastcsearch-spark` connector.
According to documentation at https://www.elastic.co/guide/en/elasticsearch/hadoop/5.0/install.html#_minimalistic_binaries
it should be
```
<dependency>
   <groupId>org.elasticsearch</groupId>
   <artifactId>elasticsearch-spark_2.10</artifactId>
  <version>5.0.0</version>
</dependency>
```
however in reality, as of now, there are following artefacts are present in public maven repos:
- elasticsearch-spark-13_2.10, elasticsearch-spark-13_2.11 for Spark 1.* 
- elasticsearch-spark-20_2.10, elasticsearch-spark-20_2.11 for Spark 2.*

**Comment by jbaiera** [comment]
Thanks @vkroz, this is a known issue with the current docs. I'll have a fix landing soon.
