### ISSUE TITLE
Not able to Give two combination of Column using es.mapping.id

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [elastic/elasticsearch-hadoop#893]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by sumit-gupta-sgt** [comment]
Hi All,
I am not able to give combination of two column as docid..Tried with one column its working fine.
One Column Test:
df.write.format("org.elasticsearch.spark.sql").option("es.mapping.id","columnname").option("es.resource","indexname/indextype").save()

I am not sure two column cobination is supported by spark-es or not.Please let me know is this bug or not supported now.

Thanks,
Sumit

**Comment by jbaiera** [comment]
@sumit-gupta-sgt Could you fill out the issue template in full? You have attached an example that you say works, but you have not included an example that reproduces the problem. Please also denote the versions of the artifacts and services you are using. Thanks!

**Comment by jbaiera** [comment]
Closing due to lack of feedback
