### ISSUE TITLE
java.util.ConcurrentModificationException in REST connection pool code

### ISSUE THREAD

**Issue by apollos92** [elastic/elasticsearch-hadoop#894]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

I currently updated ES-Spark dependency from v5.0.0-alpha-5 to v5.0.1 (es-spark-20 in es-hadoop)
(until that moment, everything's OK)

And according to recommendation on DStream output API change, I also changed my output codes from `stream.foreachRDD(_.saveToES(..))` to `EsSparkStreaming.saveToES(stream, ...)`

After this change, `spark-submit` with standalone cluster in client deploy mode, occasionally produces following error in workers.
``` 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at org.elasticsearch.hadoop.rest.pooling.TransportPool.removeOldConnections(TransportPool.java:168)
	at org.elasticsearch.hadoop.rest.pooling.PooledHttpTransportFactory.cleanPools(PooledHttpTransportFactory.java:121)
	at org.elasticsearch.hadoop.rest.pooling.PooledTransportManager$PoolCleaner.run(PooledTransportManager.java:86)
	at java.lang.Thread.run(Thread.java:745)
```

### Steps to reproduce

How to Reproduce:
- partially described in `issue description`.
- It occurs in random manner, possibly with high probability in the state of indexing/updating operations are increased rapidly.

Spark/ES Cluster Configuration:
- A Spark cluster with 3 workers (16 cores per one worker, each worker's in physically separated Linux server)
- An ElasticSearch cluster with 3 nodes 
- Each server: 16 Cores, 32 GB memory space, 1 TB disk space

### Version Info

OS:         :  CentOS 6
JVM         :  1.8.0_40
Hadoop/Spark:  Spark 2.0.1
ES-Hadoop   :  5.0.1
ES          :  2.4.1

**Comment by jbaiera** [comment]
Thanks for opening this up. The problem was not so much a threading issue but a set of calls that mutating the collection of idle connections while iterating over that same collection. Should be fixed in the above commit.

**Comment by apollos92** [comment]
I'm happy for this report being a little bit of contribution to more robust codes. 
I'll wait for next version. Thank you!
