### ISSUE TITLE
Merge dataset col or rdd in single document. Also control store option on index

### ISSUE THREAD

**Issue by mozinrat** [elastic/elasticsearch-hadoop#907]
### What kind an issue is this?

- [x] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Feature description
Currently elasticsearch hadoop is converting dataset/rdd to documents with 1 to 1 mapping i.e. 1 row in dataset is converted to one doc. In our scenario we are doing something like this

PUT spark/docs/1
{
  "_k":"one",
  "_k":"two",
  "_k":"three" // large sets , we dont need to store much, we just want to map multiple keys to single value.
  "_v" :"key: 
}

GET spark/docs/_search
{
    "query" : {
        "constant_score" : {
            "filter" : {
                "terms" : { 
                    "_k" : ["one"] // all values work.
                }
            }
        }
    }
}

Any suggestion how can we implement above, if there is a better strategy, please suggest.

**Comment by jbaiera** [comment]
@mozinrat I'm assuming you are working with many tuples:
```
[("one" -> "value"), ("two" -> "value"), ("three" -> "value"), ...]
```
You could use a set of spark functions to collapse the keys into the same document by collecting each row together by value instead of key, then saving the newly combined documents.
