### ISSUE TITLE
Update script overrides upsert mode?

### ISSUE THREAD

**Issue by dmarkhas** [elastic/elasticsearch-hadoop#908]
I have the following document in ElasticSearch:

  "_source": {
    "id": 1234567,
    "newDrop": "FIRST"
  }

My code looks like this:

```
case class TestDoc(id: Int, newDrop: String)
val ds = List(TestDoc(1234567,"SECOND")).toDF()
val updatescript = "if (false) { ctx.op = 'none'}"
ds.saveToEs("ipg3/doc",Map("es.mapping.id" -> "id", "es.write.operation" -> "upsert", "es.update.script" -> updatescript))
```

What I expect to happen is for "newDrop" to get updated to "SECOND" when I run saveToEs, since the condition in the script is always false. However, the value doesn't get updated. If I remove the script entirely from the settings map, the value is updated correclty.

Is this a bug or am I missing something?

**Comment by jbaiera** [comment]
The write operation that is specified in the ES-Hadoop settings just defines how ES-Hadoop will construct the request, either as an upsert, update, index, or create operation. The update script that is provided is executed on the Elasticsearch server side while it is performing the operation. If the script instructs the context for the operation to perform no operation, then nothing will be done.

**Comment by dmarkhas** [comment]
Thanks, this was my misunderstanding of the Elastic script mechanism.
