### ISSUE TITLE
elastic search hive table shows date as null 

### ISSUE THREAD

**Issue by theebanparthi1988** [elastic/elasticsearch-hadoop#912]
I have a hive table named details with below schema
name STRING,
address STRING,
dob DATE

 My dob is stored in yyyy-mm-dd format.like 1988-01-27. In hive I can view this date with proper format.

I am trying to load this elastic search table . So i followed below instruction in HUE.

CREATE EXTERNAL TABLE sampletable (name STRING, address STRING, dob DATE)
ROW FORMAT SERDE 'org.elasticsearch.hadoop.hive.EsSerDe' 
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = 'test4/test4','es.nodes' = 'x.x.x.x:9200');

INSERT OVERWRITE TABLE sampletable SELECT * FROM details;

select * from sample table;
But DOB field shows NULL for all coloumn. Whereas I can verify that my original hive table has data in date field.

After some research I was able to find that Elasticsearch expects data field to be in yyyy-mm-ddThh:mm:zz since my data doesn't match that it throws error. And also it mentioned, I can change the format to "strict_date" format, then it will work fine my hive date format. But I am not sure where in hive query i execute I need to metion this.

Can you help me with this?

I have seen multuiple threads where link is provided to mapping of elasticsearch site. But I am newbie  dont understand how to mention the date format in hive query. . Can you please help me here?

**Comment by jbaiera** [comment]
@theebanparthi1988 This is a question that is better suited for our [discussion forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop). We reserve Github for bug and feature tracking.
