### ISSUE TITLE
Spark 2.1 support

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#915]
This issue tracks adding support for Spark 2.1.

http://spark.apache.org/releases/spark-release-2-1-0.html

**Comment by jbaiera** [comment]
The upgrade process didn't run into any issues. This should be easy to get in for 5.2.

**Comment by pfcoperez** [comment]
@acchen97 @jbaiera I've performed some simple examples and it seems to work nicely with Spark 2.1.  

Is it the case that this task cover the fact that it has to be thoroughly checked before being considered as officially supported? 

If not, what cases are failing in Spark 2.1?

Thanks

**Comment by acchen97** [comment]
@pfcoperez thanks for testing it. Yes, it's predominantly making sure everything works before we consider Spark 2.1 formally supported.

Let us know if anything else pops up for you.

**Comment by jbaiera** [comment]
Released in 5.2.0

**Comment by cjuexuan** [comment]
hi,I found last `elasticsearch-spark_2.11` version is `5.0.0-alpha4`,and use  `spark_1.6`,and in `elasticsearch-hadoop-5.2.0` ,scala version is `2.10`,so I think we need a version adaptation  `spark_2.11` and  `scala_2.11`

**Comment by jbaiera** [comment]
@cjuexuan Please see the `Spark` section of the [installation guide in the documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/install.html). It outlines the correct artifacts for usage when working with the different versions of Spark and Scala.

**Comment by cjuexuan** [comment]
@jbaiera ，thanks
