### ISSUE TITLE
Typo-error in PartitionDefinition.java

### ISSUE THREAD

**Issue by bnoreus** [elastic/elasticsearch-hadoop#919]
On the following lines (178,179,180,181) in PartitionDefinition.java there is the following code:
 ```
public Settings settings() {
        PropertiesSettings settings = new PropertiesSettings();
        return serializedMapping != null ? settings.load(serializedSettings) : settings;
}
```
Shouldn't the condition be `serializedSettings != null` . Otherwise this could cause return a null value theoretically. Also, if serializedMapping happens to be null, this will return settings that are not the same that were serialized in the constructor.

**Comment by jbaiera** [comment]
This is reasonable to assume to be a typo, but it does not seem to impact the program execution at all. Even if a type contains only one document with no fields and has an empty mapping, the serialized mapping field will be non null, and the properties will be returned correctly. In the event that the type does not exist at all (and thus have a potentially null mapping), the framework will have already chosen that there are no shards to target and thusly not create any partition definitions. Regardless, I'll push a quick fix for this. Thanks for bringing it up @bnoreus
