### ISSUE TITLE
Visualization issue with Kibana using Cassandra+Spark+ELK

### ISSUE THREAD

**Issue by ArslanSaleem** [elastic/elasticsearch-hadoop#920]
Hi,

I have a use case where i am parsing data from logstash and insert into Cassandra and after that i am getting data in Apache Spark and do some processing and send it to elasticsearch.

But i am not getting that data in kibana because when i write index name it doesn't display/find timestamp column.

Following is the code that i am using to read data from Cassandra and store in ES:

```
Dataset<Row> df=sc.read().format("org.apache.spark.sql.cassandra").option("keyspace","excelsior").option("table", "testlogstash").load();
		df.show();
		
		df.registerTempTable("testlogstash");
		Dataset<Row> dataframe=sc.sql("select * from testlogstash limit 100");
		dataframe.show();
		JavaRDD<CpuResources> list=dataframe.javaRDD().map(rawFlowdata);
		JavaEsSpark.saveToEs(list, "spark/docs");
```
This is the sample data stored in Cassandra and displayed using Apache Spark.
```
+-------------------+--------------------+---------+----------+----------+--------------------+--------------------+-----+
|               time|                host|loaderage|loaderage2|loaderage3|             message|                path|users|
+-------------------+--------------------+---------+----------+----------+--------------------+--------------------+-----+
|  16:56:19 up  6:05|arslan-HP-15-Note...|     0.33|      0.70|      0.79| 16:56:19 up  6:0...|/home/arslan/upti...|    4|
|  10:59:46 up 9 min|arslan-HP-15-Note...|     1.45|      2.17|      1.37| 10:59:46 up 9 mi...|/home/arslan/upti...|    4|
|  14:35:25 up  3:44|arslan-HP-15-Note...|     0.34|      0.48|      0.52| 14:35:25 up  3:4...|/home/arslan/upti...|    4|
|  12:57:42 up  2:07|arslan-HP-15-Note...|     3.02|      3.31|      2.73| 12:57:42 up  2:0...|/home/arslan/upti...|    4|
|  16:46:50 up  5:56|arslan-HP-15-Note...|     1.73|      1.38|      0.90| 16:46:50 up  5:5...|/home/arslan/upti...|    4|
|  12:23:46 up  1:33|arslan-HP-15-Note...|     1.10|      0.87|      0.77| 12:23:46 up  1:3...|/home/arslan/upti...|    4|
|  12:46:09 up  1:55|arslan-HP-15-Note...|     3.19|      2.62|      1.76| 12:46:09 up  1:5...|/home/arslan/upti...|    4|
|  13:37:04 up  2:46|arslan-HP-15-Note...|     1.07|      0.74|      1.36| 13:37:04 up  2:4...|/home/arslan/upti...|    4|
```

**Any information regarding such issue, why kibana is not picking up the time stamp field?**

**Comment by jbaiera** [comment]
@ArslanSaleem Could you share your Elasticsearch mappings? Please note that ES-Hadoop only handles dates that are in a specific format (ISO 8601 Date Time). This may be the root issue you are experiencing.

**Comment by ArslanSaleem** [comment]
Yes, you are right i stored date in text format in Cassandra and reading that in string. I think this is the issue let me just test it. Thanks jbaiera.
This is my mapping:
`{"spark":{"aliases":{},"mappings":{"list":{"properties":{"host":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"loaderage":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"loaderage2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"loaderage3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"message":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"path":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"time":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"users":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"docs":{"properties":{"host":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"loaderage":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"loaderage2":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"loaderage3":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"message":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"path":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"time":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"users":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}},"settings":{"index":{"creation_date":"1484740345753","number_of_shards":"5","number_of_replicas":"1","uuid":"64UgPkUxQWaN_a0cLfbRFQ","version":{"created":"5010199"},"provided_name":"spark"}}}}`

**Comment by jbaiera** [comment]
Closing this issue as I believe the date format was the problem. Feel free to comment on here if there are any other issues.

**Comment by ArslanSaleem** [comment]
Yes Date was the issue and sorry for not closing the issue.
Thanks
