### ISSUE TITLE
Schema discovery fails when using aliases

### ISSUE THREAD

**Issue by dmarkhas** [elastic/elasticsearch-hadoop#938]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

When reading data from an ElasticSearch alias that maps to multiple indices with potentially different schemas (assume that there are no conflicts), the schema discovery process only uses the first index returned by GET /<alias_name>/<type>/_mapping and ignores the mapping of all other indices (meaning only a subset of the actual schema provided by the alias is discovered).

### Steps to reproduce

- Create two indices in ElasticSearch with different attributes (without conflicts)
- Create an alias in ElasticSearch that maps to the two indices
- Create a dataframe based on the alias and view it's schema

Code:

```
val aliasDF = session.read.format("es").options(options).load("alias/type")
aliasDF.printSchema()
```

The problem is with the Field class:

```
    public static Field parseField(Map<String, Object> content) {
        Iterator<Entry<String, Object>> iterator = content.entrySet().iterator();
        return (iterator.hasNext() ? skipHeaders(parseField(iterator.next(), null)) : null);
    }
```

When working with aliases, content actually has multiple indices records, not just one.
What the code currently expects (and what is returned from ES when dealing with indices):

{
"index_name":{
     "mappings": {
          "type_name": {
           ...
          }
     }
  }
}

But when working with aliases, the response actually looks like:

{
"index_name1":{
     "mappings": {
          "type_name": {
           ...
          }
     }
  },
"index_name2":{
     "mappings": {
          "type_name": {
           ...
          }
     }
  }
}

### Version Info

OS:         :  Windows
JVM         :  1.8.0_102
Hadoop/Spark:  2.10
ES-Hadoop   :  5.2.1
ES          :  5.2.1

**Comment by jbaiera** [comment]
This seems to me to be an oversight in how the mapping code handles mappings. I also believe this is related to potential errors in the serialization layer as discovered in #850.
