### ISSUE TITLE
Issues with connecting to ES running locally

### ISSUE THREAD

**Issue by koldkoder** [elastic/elasticsearch-hadoop#941]
I am trying to use ESBolt to write data to ElasticSearch.  I have started ES instance locally inside a docker, as below. 

> docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.2.1

I am using elasticsearch-storm dependency in my pom file 

        
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-storm</artifactId>
            <version>5.2.1</version>
        </dependency>

This is what my EsBolt looks like

>        Map conf = new HashMap();
>         conf.put("es.nodes", "127.0.0.1");
>         conf.put("es.port", "9200");
>         conf.put("es.net.http.auth.user", "elastic");
>         conf.put("es.net.http.auth.pass", "changeme");
>         conf.put(Keys.ES_INPUT_JSON, "true");
>         conf.put(Keys.ES_INDEX_AUTO_CREATE, "true");
>         conf.put(Keys.ES_STORM_BOLT_WRITE_ACK, "true");
> 
>         EsBolt esBolt = new EsBolt("my_collection/index", conf);
>         return esBolt;

When running my topology i get this exception

> org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[172.17.0.2:9200]] 
> 	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:150) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:444) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestClient.executeNotFoundAllowed(RestClient.java:452) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestClient.exists(RestClient.java:519) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestClient.touch(RestClient.java:525) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestRepository.touch(RestRepository.java:412) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:580) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:568) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.elasticsearch.storm.EsBolt.prepare(EsBolt.java:103) ~[radpub-0.0.1-SNAPSHOT-jar-with-dependencies.jar:?]
> 	at org.apache.storm.daemon.executor$fn__8058$fn__8071.invoke(executor.clj:795) ~[storm-core-1.0.2.jar:1.0.2]
> 	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) [storm-core-1.0.2.jar:1.0.2]
> 	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]

Not sure where the ip address 172.17.0.2 came from. I am abel to connect to ES perfectly fine using curl command

**Comment by ebuildy** [comment]
Hello, 

Your Docker ES has 2 IP, the container IP, and the host IP where you bind the port 9200.

It works like Zookeeper does:

1) Client --> elasticsearch (who are you ? tell me your data nodes please ?)
2) ES --> client (I am v2.4, here my data nodes: LOCAL_IP)
3) client --> LOCAL_IP (haaa where are you ??)

All that to say, use:

``es.nodes.wan.only=true`` ;-)

So Es4Hadoop will not sniffing data nodes and use IP you set.

**Comment by jbaiera** [comment]
I'm going to mark this as resolved since there has been no follow up from the original author.
