### ISSUE TITLE
Convert search requests to use QueryDSL instead of URL params.

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#943]
### Feature description

In certain circumstances, a search request URL can grow beyond the maximum URL length. This is because we leverage certain framework schemas as a way to perform field projection to the underlying ES cluster by setting field names in the `_source` filter field. In situations where some users are interacting with very very large schemas with field names that are rather long, this can blow right past the URL length limit.

Anything that is on the search URL that is a list style format, or can be specified by the user (such as the names of fields to use for projection) should be placed into the search request's body as QueryDSL instead of in the URL's parameters. In fact, it may make sense to transition all that we can into the QueryDSL from the URL parameters to simplify the requests going forward.

**Comment by samkenhuang** [comment]
I am facing the same problem now. Do you have some solutions?

**Comment by jbaiera** [comment]
This issue was missed when #1154 was merged. This should be resolved now as of 6.3.1 and 6.4.0.
