### ISSUE TITLE
Spark JavaRDD give partial documents

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch-hadoop#946]
### What kind an issue is this?

Bug report

### Issue description

Using Spark and JavaRDD, documents returned are missing fields !

Posted first here: https://discuss.elastic.co/t/bug-when-reading-if-a-field-has-no-mapping-empty-array-by-ex/76393.

### Steps to reproduce

Code:

Create a dummy index:

```
PUT /toto/events/1
{
   "toto": 1,
   "data": [],
   "name": "webapp_loaded"
}
```

Query it via Spark shell:

```
scala> sc.esRDD("toto").first.toString
res22: String = (1,Map(toto -> 1))
```

It looks like es4Hadoop parse mapping to figure out the structure, and if a field is not in the mapping, it skips others.

### Version Info

OS:         :  MacOS / CentOS
JVM         :  1.8
Hadoop/Spark:  2.6
ES-Hadoop   :  2.4.4 / 5.0.0
ES          :  2.4.4

**Comment by ebuildy** [comment]
Gloups, specifying ``index/type`` fix this weird behaviour 🥇 yeah !! 

Is it a bug or index/type is required?

**Comment by jbaiera** [comment]
@ebuildy There should really be a check to make sure there is both an index and a type available when setting the `es.resource` for the connector. It looks like it's pretty lax about that right now, but it's also technically a contract change for the connector.

**Comment by jbaiera** [comment]
After reviewing this a bit more over time I'm starting to think that there is more going on under the surface. We leave index parsing pretty lax to support situations like specifying "_all", but I'm starting to wonder if we should allow supporting that at all. Either way, this should probably be looked at for 6.0 where we can make a drastic enough change to require stricter index and type names to be given.

**Comment by jbaiera** [comment]
I'm pretty sure that 093e9881665c496c4354c8d474ac551919355166 fixed the root problem here. I've added explicit parsing rules for writing and requiring types, but for reads, we assume all types under the matching indices given.
