### ISSUE TITLE
[DOC] Wrong doc link

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch-hadoop#960]
Not a big one but at:

https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html

Some links are pointing to documentation version 2.0 (should be master ?)

By example, the link for "Ingest Node" points to 2.0 where there is no ingest node yet :/ 

I believe you must change the variable ``ref``

**Comment by jbaiera** [comment]
Looks like a misconfigured reference in the docs. Thanks for pointing this out!

**Comment by jbaiera** [comment]
Fixed in 5.3.1. I'll backport to the other 5.x branches.
