### ISSUE TITLE
Add status checks for when ES cluster is red.

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#976]
If the Elasticsearch cluster has a status of `red`, we execute blindly and break in some cases. We should be checking early on in the job if the cluster is red, and throw an exception. We should also make sure that we can at least handle running over a red cluster, even if there is loss of data fidelity, allowing users to acknowledge that clusters are red and read them anyway with a setting might be wise as well.

**Comment by jimmyjones2** [comment]
@jbaiera Thanks!

**Comment by jbaiera** [comment]
This is released in version 5.4.0
