### ISSUE TITLE
what can i do for reading a few columns by spark or spark-sql ? 

### ISSUE THREAD

**Issue by oaksharks** [elastic/elasticsearch-hadoop#979]
In  the es cluster , it has a large scale data , we used spark to compute data but in the way of 
`elasticsearch-hadoop` following by [https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/spark.html) we have to read full columns of an index , is there anything that help ?

**Comment by dmarkhas** [comment]
Doesn't es.read.fields.include work for you?

**Comment by jbaiera** [comment]
@oaksharks We reserve Github for feature tracking and bug reports. Please ask these sorts of questions on our [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop)
