### ISSUE TITLE
Maven dependencies broken: missing cascading-hadoop-2.6.3

### ISSUE THREAD

**Issue by phoerious** [elastic/elasticsearch-hadoop#984]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

When trying to resolve Maven dependencies of any 5.x release via Gradle, I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find cascading:cascading-hadoop:2.6.3.
  Searched in the following locations:
      https://repo1.maven.org/maven2/cascading/cascading-hadoop/2.6.3/cascading-hadoop-2.6.3.pom
      https://repo1.maven.org/maven2/cascading/cascading-hadoop/2.6.3/cascading-hadoop-2.6.3.jar
  Required by:
      project : > org.elasticsearch:elasticsearch-hadoop:5.4.0
> Could not find cascading:cascading-local:2.6.3.
  Searched in the following locations:
      https://repo1.maven.org/maven2/cascading/cascading-local/2.6.3/cascading-local-2.6.3.pom
      https://repo1.maven.org/maven2/cascading/cascading-local/2.6.3/cascading-local-2.6.3.jar
  Required by:
      project : > org.elasticsearch:elasticsearch-hadoop:5.4.0
> Could not find org.pentaho:pentaho-aggdesigner-algorithm:5.1.5-jhyde.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom
      https://repo1.maven.org/maven2/org/pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
  Required by:
      project : > org.elasticsearch:elasticsearch-hadoop:5.4.0 > org.apache.hive:hive-service:1.2.1 > org.apache.hive:hive-exec:1.2.1 > org.apache.calcite:calcite-core:1.2.0-incubating

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by jbaiera** [comment]
@phoerious Thanks for opening an issue, but we politely request that you ask these sorts of questions on our [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop). We try to reserve Github issues for bug reports on the project code as well as for feature tracking.

To answer your question, I believe that you need to add some other repositories to resolve those artifacts: 

* For the cascading artifacts try adding `http://conjars.org/repo` to your repositories.
* For the pentaho artifact, it looks like it is available in [this repo](https://mvnrepository.com/artifact/org.pentaho/pentaho-aggdesigner-algorithm/5.1.5-jhyde).

**Comment by phoerious** [comment]
It used to work with previous versions. I was about to add those external repositories, but didn't want to if not really needed.
