### ISSUE TITLE
Log when a retry failed for a 429

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch-hadoop#999]
We have the `es.batch.write.retry.count (default 3)` setting , but currently there is no way to see which where the failed documents. We could write a special log format in order to be able to retrieve, visualize, or even retry in some sort of way all failed messages after that third time.

CC @jbaiera

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
I may be missing something that will help resolve this, but this issue is severely limiting the usefulness of the library.  The only way we have found to recover from these errors is to blow away the index and hope there are no failures the next time.  We can reduce parallelism of indexers, but that does not guarantee an error-free run and comes at a large cost in terms of indexing time.

Is this something that is able to be fixed?

Thank you

**Comment by jbaiera** [comment]
> The only way we have found to recover from these errors is to blow away the index and hope there are no failures the next time.

@b-l-a-c-k-b-e-a-r-d I'm interested in knowing more about your situation here. I'm not sure how the problem you are describing is related to this ticket. Could you elaborate?

**Comment by b-l-a-c-k-b-e-a-r-d** [comment]
Sure.  

We process a lot of data in Spark and often need to index the results into Elasticsearch.  We have been able to use the ES-Hadoop library to do this, but we never know until indexing completes whether or not all of the documents made it into the index (we determine this by counting the number of docs in the index and comparing to the number we expected to go in).  

If we find there are fewer documents in the index than we expect, we have been deleting the index and starting over as we have not found a way to determine which documents failed to index.  If we knew which documents failed, we would be able to handle them (inspect/retry indexing/etc) without needing to start over.

**Comment by jbaiera** [comment]
@b-l-a-c-k-b-e-a-r-d If you index into Elasticsearch using an ID, that should allow you to safely rerun the job. Also, this ticket is in regards to documents that currently fail the job when they cannot be inserted. I would update your processing to store your documents using a pre-generated ID to begin with, and then to open an issue if you are still seeing dropped documents.

**Comment by jbaiera** [comment]
@b-l-a-c-k-b-e-a-r-d we're also looking to get something like this ticket working soon. If not with an underlying queue, at least in a way that lets users log and ignore data that breaks or fail with more helpful messages.

**Comment by gmoskovicz** [comment]
For example in Logstash there is a Dead Letter queue that contains failed messages, so we could do something similar here.

**Comment by jbaiera** [comment]
Closing this in favor of #1064
